### ISSUE TITLE
Prebuild only run when first time of project add into self-host Gitpod

### ISSUE THREAD

**Issue by newbe36524** [gitpod-io/gitpod#10024]
### Bug description

I deploy a self-host Gitpod in Azure as https://github.com/gitpod-io/gitpod-microsoft-aks-guide says.

Everything works but some problem of prebuilds raised. 

Prebuilds of DEFAULT branch only run at the first time when a new repo added as a project in gitpod.  After that, when I make some changes on the DEFAULT branch, it doesn't trigger prebuild. it's always in the READY state. But the actual content is old.

I'm curious if I'm overlooking some configuration or if this is a bug.

### Steps to reproduce

1. install gitpod as https://github.com/gitpod-io/gitpod-microsoft-aks-guide says
2. sign in self-host gitpod by github account
3. add github intergration oauth permission with private_repo and repo
4. add a private repo into gitrepo
5. DEFAULT branch starts to run prebuild and get into READY state.
6. edit README.md in the repo in DEFAULT branch and push
7. prebuild stats is still READY but nothing run, and prebuild list view, there is nothing but the first record of prebuild when repo init.

### Expected behavior

1. when I push changes to DEFAULT branch, it would trigger prebuild.

**Comment by AlexTugarev** [comment]
@newbe36524, is there a .gitpod.yml in the default branch? Prebuilds are started on push events only if there are tasks in a .gitpod.yml file on the branch of the commit pushed.

You can run `gp init` to create a .gitpod.yml from template, just in case.

If there is/was none, we definitely need to improve the messaging to make it clear why a prebuild is running initially.
Also, then this is not a self-hosted bug. (cc. @lucasvaltl )

**Comment by jldec** [comment]
Will assume that this is a duplicate of https://github.com/gitpod-io/website/issues/2125 unless @newbe36524 confirms that there is an `init` task in the gitpod.yml on the default branch of this repo.

**Comment by newbe36524** [comment]
@AlexTugarev @jldec 
There is always a file as below when I push new commint to my default branch 'main'

```yml
image: dfx_rust:bullseye-dfx-0.9.3-gitpod-5
ports:
  - port: 8000
    visibility: public
    onOpen: ignore
tasks:
  - name: dfx dev
    init: |
      . ~/fix_gitpod_path.sh
      cd src
      ./start.sh
      ./sh_setup_dev.sh
      ./sh_reinstall.sh
      dfx stop
    command: |
      . ~/fix_gitpod_path.sh
      pip3 install pipenv && \
      pip3 install pre-commit && \
      pre-commit install
      cd src
      ./start.sh
      ./sh_setup_dev.sh
vscode:
  extensions:
    - matklad.rust-analyzer
    - GitHub.copilot
    - panicbit.cargo
    - bungcip.better-toml
    - usernamehw.errorlens
    - ms-azuretools.vscode-docker
jetbrains:
  pycharm:
    plugins:
      - org.rust.lang
      - ru.adelf.idea.dotenv
      - com.chrisrm.idea.MaterialThemeUI
      - com.mallowigi
```

<img width="779" alt="msedge_9oPsR3jjNT" src="https://user-images.githubusercontent.com/7685462/171575286-7f3b59c2-fb41-4b73-b873-2abda57e5800.png">

But it never run again but the first time of project added to self-host gitpod
