### ISSUE TITLE
Java Swing GUI not showing up using VNC

### ISSUE THREAD

**Issue by McPringle** [gitpod-io/gitpod#1004]
**Describe the bug**
I would like to use Gitpod for a project, which includes a Java Swing GUI. Locally the Java Swing GUI works fine. On Gitpod, there is only the border of the window visible showing the elements of the window without the content. Please take a look at the following Screenshot:

![Gitpod Java GUI](https://user-images.githubusercontent.com/1254039/70852909-3b362f80-1ea7-11ea-88a9-6822f9f8e6fe.png)

**To Reproduce**
1. [Open GPX Animator in Gitpod](https://gitpod.io/#https://github.com/zdila/gpx-animator)
2. Run `./mvnw exec:java`

**Expected behavior**
The window with the yellow background should look like the following screenshot, which I took on my Linux PC:

![GPX Animator locally on Linux](https://user-images.githubusercontent.com/1254039/70852933-b992d180-1ea7-11ea-8d0e-0825514bd955.png)

**Additional Information**
I am using an own `.gitpod.Dockerfile`:

````
FROM gitpod/workspace-full-vnc
USER root
RUN apt-get update \
    && apt-get install -y openjfx libopenjfx-java matchbox \
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
````

And my `.gitpod.yml` looks like this:

````
image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean package

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
````

**Comment by jankeromnes** [comment]
I was able to reproduce this with https://github.com/jankeromnes/MetaChess (a Swing-based chess game).

Looks like a recent regression, but I'm not sure on whose side. Will take a look.

**Comment by jankeromnes** [comment]
Could this potentially be related to JavaFX? I noticed that our images dropped JavaFX support. I've just added it back (along with a Gradle upgrade). Hopefully this will fix the yellow window problem.

If not, I'm a bit lost as to what to try next. This bug is really weird, and I didn't see any error logs or warnings anywhere. 😕

**Comment by jankeromnes** [comment]
Doesn't seem to be the missing JavaFX, as we've reintroduced it, but the problem is still there.

For what it's worth, the empty window is beige now instead of yellow. Any help or ideas here would be much appreciated. 🙏

**Comment by McPringle** [comment]
In the meantime, we migrated from Maven to Gradle (new run command: `./gradlew run`) and from Java 8 to Java 11. Today I tried it again with the actual version of GitPod and OpenJDK 11.0.5. Still the same problem. Unfortunately, I have no idea how I can help to fix this bug.

**Comment by McPringle** [comment]
I updated my project to Java 15 (AdoptOpenJDK 15.0.1 with HotSpot). Still the same problem. I would like to help with the solution, but I do not know what is needed. Please give me information about what else I can try.

**Comment by davidmoten** [comment]
I have a solution. After reading https://stackoverflow.com/questions/35852534/java-swing-applications-not-rendering-properly-with-vnc I inserted the System property `-Dsun.java2d.xrender=false` in the command run in the Java Process  Console and the yellow content stuff was sorted.

**Comment by jankeromnes** [comment]
Wow, thank you so much @davidmoten for researching a solution and sharing it here. 💯

I'm also still affected by this problem, but it would be great to find a way to fix it in the image itself.

**Comment by davidmoten** [comment]
The environment variable that would help (JAVA_TOOL_OPTIONS)  is not set in the VNC image but rather in `/home/gitpod/.bashrc` which is controlled by the *gitpod* project in github.

Debian:

https://github.com/gitpod-io/gitpod/blob/c999d32a6e86dc7485d993ff036a9f1f4f5f3107/components/image-builder/workspace-image-layer/gitpod-layer/debian/gitpod/.bashrc-prepend

Alpine:

https://github.com/gitpod-io/gitpod/blob/c999d32a6e86dc7485d993ff036a9f1f4f5f3107/components/image-builder/workspace-image-layer/gitpod-layer/alpine/gitpod/.bashrc-prepend

**Comment by davidmoten** [comment]
ok after a bit of investigating I got this to work for me:

.gitpod.yml
```yaml
image: gitpod/workspace-full-vnc
# start up tasks

tasks:
  - init: 'echo export JAVA_TOOL_OPTIONS=\"$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false\" >>/home/gitpod/.bashrc'
    command: 'source /home/gitpod/.bashrc && mvn package && java -jar target/*with-dependencies.jar'
    
ports:
  - port: 6080
    onOpen: open-preview
```

Interestingly the console in the IDE has been started without calling .bashrc so I force that in the `command`. When you run a class manually from the IDE it starts a fresh console (and has the .bashrc stuff) so the setting is good for that too.

Of course my call to `mvn package && java -jar ...` is optional. I just wanted it to start running immediately.
