### ISSUE TITLE
Can't install openvsx extensions

### ISSUE THREAD

**Issue by Ryder05** [gitpod-io/gitpod#10219]
### Bug description

I am using a self hosted gitpod.
When i create a new workspace and i try to install an extensions from the marketplace nothing happens.
This is the error that shows up after a while.

![image](https://user-images.githubusercontent.com/59898800/170045742-4b2e19f0-7cb5-4399-b3cf-537772077ff1.png)

When this is the corresponding logs.

![image](https://user-images.githubusercontent.com/59898800/170045935-9e86dd61-fdfc-416a-bab8-5209ce9a638c.png)

And this is the log from the WS pod
![image](https://user-images.githubusercontent.com/59898800/170046251-7de2b906-2c41-44aa-891c-9a86121f2035.png)

### Steps to reproduce

1) Deploy gitpod using the instructions present here https://github.com/gitpod-io/gitpod/tree/main/install/installer
2) Open a new workspace
3) go to extensions and install an extension 

### Expected behavior

i get my extension installed on my workspace 

### Anything else?

```
apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: false
  external:
    url: osamaregistry.azurecr.io
    certificate:
      kind: secret
      name: regcred
database:
  inCluster: true
disableDefinitelyGp: true
domain: "gp.REDACTED"
kind: Full
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  maxLifetime: 36h0m0s
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: fuse
```
