### ISSUE TITLE
Dockerhub doesn't work as container registry for self hosted installation

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#10215]
### Bug description

When dockerhub is configured as a container registry, the image-builder-mk3 fails to create image build pods.

gitpod configuration:

```yaml
containerRegistry:
  inCluster: false
  external:
    url: docker.io/psinha36
    certificate:
      kind: secret
      name: registry-secret
```

also tried urls: docker.io, registry.docker.io, registry-1.docker.io. Configured the experimental section too:

```yaml
experimental:
  webapp:
    server:
      disableDynamicAuthProviderLogin: false
      enableLocalApp: true
      defaultBaseImageRegistryWhitelist:
      - https://index.docker.io/v1/
      - https://registry.docker.io
      - https://registry-1.docker.io/
      - https://registry.docker.io/psinha36
      - https://registry-1.docker.io/psinha36
      - https://azurecr.io/
```

### Steps to reproduce

Use above configuration.

### Expected behavior

It should create an image build pod.
