### ISSUE TITLE
[GitHub.com only] Prebuilds no longer triggering if gitpod.yml uses a 'before' task without an 'init'

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10336]
The following [.gitpod.yml](https://github.com/jldec/test-before/blob/main/.gitpod.yml) used to trigger prebuilds on each commit (on GitHub only) but as of 21d3f00d47f7b073fa517dd186963bcb87abc652 it no longer does.  

```yaml
# .gitpod.yml
tasks:
  - before: |
      echo `gp url` >> before.txt
    command: |
      echo `gp url` >> command.txt
```

Since the old behavior was somewhat unexpected, and GitHub-specific, and atypical (the standard way to configure a prebuild is with `init`) the proposal for this issue is NOT to fix this, but rather to clarify the recommended use of `init` in our docs.
