### ISSUE TITLE
Allow github.prebuilds.defaultBranch configuration in .gitpod.yml

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10358]
Let's make `defaultBranch` synonymous with `master`.

The currently supported GitHub prebuild configuration settings are (with defaults)  

```yaml
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
```

See also #7426
