### ISSUE TITLE
better .gitpod.yml generation

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#10374]
## Is your feature request related to a problem? Please describe
https://github.com/vuejs/core, when open this repo.
Generated `.gitpod.yml`
```yml
tasks:
  - init: npm install && npm run build
    command: npm run dev
```

## Describe the behaviour you'd like
Actually it's using `pnpm`, so it should be

```yml
tasks:
  - init: pnpm install 
    command: pnpm run dev
```

You may ask how should I know it's pnpm. It can infer from root `pnpm-lock.yaml`
