### ISSUE TITLE
Epic: Allow for custom annotations & env variables on K8s Resources for Self-Hosted Installations

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10461]
### Summary

Allow users to customise to adapt their deployment of self-hosted to the specifics of the environment/cluster it is applied to. 

### Context

Customers are finding it difficult to sometimes use KOTS because it does not allow them to add custom annotations or env variables to K8s resources. The installer produces a fixed manifest and that then gets applied to the kubernetes cluster. Any changes made forces them to re-apply those changes after an update to Gitpod, which can lead to confusion.

Specific reasons they need to customise / make changes:
- Annotate service to use internal [networking](quizlet)
- Add an environment variable to S3 when used as a registry storage backend (internal reference)

### Value

Allow Kots to work in more setups, because it can be customised to environment specific circumstances.

### Acceptance Criteria

- Customers can add generic annotations and env variables to resources via a configuration field in the KOTS UI. 
- This is well documented in our documentation.

### Measurement

- Even more customers start using kots

### Proposed solution
Allow for generic annotations on resources - have a way to set this in the KOTS UI & Installer Config. Then apply together with the installation. 

### Alternatives considered
1. Open issues for the missing configuration options customers are doing currently with post-processing and solve this properly
3. Rely on replicated git-ops flow (requires a feature request from us) for post-processing.

### Additional Context
- Likely related to https://github.com/gitpod-io/gitpod/issues/9981 and https://github.com/gitpod-io/gitpod/commit/0b599a83ace29230bab192231449fa55202a9e3a
- [Examples](https://github.com/gitpod-io/gitpod/issues/10461#issuecomment-1150003811) of what customers are currently customising: 

### Tasks

- [x] #10853
- [x] #10826
- [x] #10902
- [x] #10903
- [x] #10942
- [x] #10910
- [ ] #10908
- [x] #10840
- [x] #10941

**Comment by corneliusludmann** [comment]
I doubt that we want to support post-processing in the near future. Instead, we should open issues for the missing configuration options customers are doing currently with post-processing and solve this properly. [See also this internal comment](https://github.com/gitpod-io/customers/issues/55#issuecomment-1146216048).

**Comment by lucasvaltl** [comment]
Here is the current list of known example customisations that are being done by customers via post-processing: 

1. Change proxy service to a cluster IP instead of a loadbalancer type when using your own load balancer (this was changed via https://github.com/gitpod-io/gitpod/pull/10537): 

```
experimental:
  common:
    serviceConfig:
      proxy:
        serviceType: "ClusterIP" # case in-sensitive
```

2. Annotate proxy service with internal networking tag to force internal IP:

```
experimental:
 webapp:
   proxy:
     serviceAnnotations:
       [networking.gke.io/load-balancer-type:](http://networking.gke.io/load-balancer-type:) "Internal"
```

3. s3 will not work for registry because of old libs in distribution/regsistry. I therefore need to add environment variable:
```
echo "Gitpod: Add s3 endpoint"
    yq eval-all -i 'select(.kind == "Deployment" and .metadata.name == "registry").spec.template.spec.containers[].env += {"name": "REGISTRY_STORAGE_S3_REGIONENDPOINT", "value": "s3.eu-north-1.amazonaws.com"}' gitpod.yaml
```

**Comment by MrSimonEmms** [comment]
I'm going to propose this as the new config structure:

```yaml
experimental:
  annotations:
    common:
      key: value
    kind:
      <k8s_kind>:
        <component_name>:
          key1: value1
```

This would allow a common annotation on __ALL__ components, but also fine-grained control of components based upon the kind (eg, `deployment`) and the component name (eg, `ws-daemon`). I've specifically added this as a separate config object (ie, not under `experiment.webapp.kind.annotation`) as this makes it a simpler, more isolated config.

I'm going to propose only applying this to `deployments`, `daemonsets`, `statefulsets` (and their `pods`) and also `services`. This will exclude the likes of `jobs`, `networkpolicies`, `rolebindings` and `configmaps` which I don't think will require much annotating.

Are we happy with this as a config definition and implementation? @lucasvaltl @corneliusludmann

**Comment by MrSimonEmms** [comment]
# PRFAQs

There are times when it is desirable for custom annotations and envvars should be added to an installation.

## Installer Config

This can be added to the root of the `config.yaml`. If nothing is passed in, no custom parameters are added in.

Annotations are structured in the format `components.annotations.<kind>.<name>`. The `kind` is the given Kubernetes "Kind", all converted to lowercase (eg, `service`, `daemonset`). The `name` is the given name of the Kubernetes resource (eg, `ws-daemon`, `server`).

Environment variables are only injected into resources that support environment variables (ie, pods).

```yaml
components:
  annotations:
    '*':
      '*':
        key1: value1 # annotation added to all components
    service:
      '*':
        key2: value2 # annotation added to all service components
    '*':
      server:
        key3: value3 # annotation added to all components called "server"
    service:
      proxy:
        key4: value4 # annotation added to proxy service
  envvars:
    '*':
      env1: value1 # envvar added to all pods
    ws-daemon:
      env2: value2 # envvar added to the "ws-daemon" pods
```

In the event of a conflict, they will be overridden in order of precedence from least to most specific - eg, `service.ws-manager.key` would override `*.ws-manager.key`, and that would override `*.*.key`.

All keys and values **MUST** be a string.

## KOTS Config

This is a raw YAML object that will be applied to the Installer config as-is. The format is described as above.

**Comment by lucasvaltl** [comment]
Thanks for writing this up @MrSimonEmms ! Helps me understand how this would work in context I hope you found it helpful as well! 

This raises a couple questions (happy to jump on a call):
- Is the way to write the config K8s standard or is it something we came up with? Context: just trying to understand how familiar users would be with this. Although granted it does not look complicated. 
- What would our error handling look like, for example if someone were to have the wrong formatting? 
- How would one apply this in KOTS? From the comments above, there would be a separate field (in the Kots admin ui) called installer config? 
- This requires intimate knowledge of the components that Gitpod uses right? I think this is fine though - if you are doing custom annotations, you will know what you want to annotate.

**Comment by mrzarquon** [comment]
This also supporting labels would complete it as a feature for use by CS, different customers have different org requirements for how their workloads are deployed - some use labels to track things like hosting cost chargeback to the department that provisioned the app for example. The difference between Labels and Annotations is that Labels would need to be applied to all resources, not just a subset (but should also be harmless if we prevent users from changing the app and component keys, that gitpod uses itself).

Re: preflight, assuming the gitpod-installer is doing the evaluation of these customizations to apply them, wouldn't adding a `installer --validate-customizations` command to the installer which is then executed as a kots preflight (using [run-pod](https://troubleshoot.sh/docs/collect/run-pod/)) be sufficient? This ensures we're always using the same component to check the data hash as would be acting on it it.

But +1 from me for going in this direction

**Comment by corneliusludmann** [comment]
> * KOTS will be a simple `<textarea>`

What do you think about a file upload instead?

Reasoning:
- Writing YAML in a text field (that does not indent with `<tab>`) is quite cumbersome
- It's easier for us to provide customers with a file instead of something they need to copy in a text field properly

Drawback:
- You need to create that file in a separate text editor.

**Comment by MrSimonEmms** [comment]
Good call @corneliusludmann. I'll change the docs comment to reflect that

**Comment by MrSimonEmms** [comment]
Edit to docs

> In the event that a Kubernetes resource has multiple annotations (eg, a `Deployment` has it on the `Deployment` spec and the `Pod` spec), the same annotation will be applied for both and can be overridden with the parent kind (in this example, `deployment`). Only Gitpod-generated annotations (eg, `gitpod.io/checksum_config`) will only be applied to the spec that they're required on.

**Comment by MrSimonEmms** [comment]
Suggest to only support:

All components except:
- cluster
- gitpod

Resources to include - others are likely to have unintended consequences:
 - jobs
 - deployment
 - daemon set
 - stateful set
 - config map
 - services
 - service account

**Comment by csweichel** [comment]
The format seems a bit cryptic. How about something that's closer to Kubernetes?
```YAML
customization:
  - kind: Pod
    metadata:
      annotations:
        appliesToAllPods: "notice the omitted name"
  - kind: Pod
    metadata:
      annotations:
        appliesToAllPods: "will override the previous value"
  - kind: Service
    name: proxy
    metadata:
      labels:
        stage: production
        companyPolicy: foobar
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
  - kind: Pod
    name: ws-manager
    metadata:
      labels:
        foo: bar
    spec:
      env:
      - name: DEMO_GREETING
        value: "Hello from the environment"
      - name: DEMO_FAREWELL
        value: "Such a sweet sorrow"
```

All applicable customisations are applied in order. Using the example above, for the `ws-manager` pod we'd end up with:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    foo: bar
  annotations:
    # whatever came from the installer
    appliesToAllPods: "will override the previous value"
spec:
  containers:
  - name: ws-manager
    env:
    # whatever came from the installer
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
```

By default the `spec` section applies to the actual "service container". 
If we ever need to customise env var of an init container, we can specify the name and match that one.
