### ISSUE TITLE
[Theia] Show Check in PR widget

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1049]
allow to view CI checks from preview field I.E.
![image](https://user-images.githubusercontent.com/50386709/71782971-f5502100-2fa5-11ea-9261-999913440469.png)

**Comment by akosyakov** [comment]
Don't we already support it?
<img width="1552" alt="Screen Shot 2020-01-06 at 14 14 24" src="https://user-images.githubusercontent.com/3082655/71808176-e6916900-308e-11ea-8ad9-cc63aed080bd.png">

Have you tried following configuration:
```yaml
github:
  prebuilds:
    pullRequests: true
    addCheck: true
```
 
See docs for more options: https://www.gitpod.io/docs/46_prebuilds/#configure-prebuilds
