### ISSUE TITLE
Mirror GCP registry to `proxy.replicated.com`

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#10610]
## Is your feature request related to a problem? Please describe

A user in China has raised an issue that their KOTS downloads the Installer image from `proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/installer:release-2022.05.1.1`. It appears that, as China blocks access to the GCP registry, KOTS automatically mirrors images to `proxy.replicated.com`.

It's important to check that this doesn't break for non-blocked GCP users. The registry should use the GCP registry as the primary delivery mechanism and fallback to the Replicated mirror if unavailable (this appears to be how it's working now)

## Describe the behaviour you'd like

As we don't currently support the Replicated private registry, we should configure this to enable users to access our images.

See also [Replicated docs](https://docs.replicated.com/vendor/packaging-private-images)

## Describe alternatives you've considered

This isn't a problem in an airgapped environment. By connecting to a VPN and downloading the airgap bundle, this would pull all the images and the KOTS dashboard would allow users to upload to their own registry.

Replicated does not make this available for community licenses, so it's only available with a paid license.

## Additional context

[Front conversation](https://app.frontapp.com/open/msg_yg9drd6)

**Comment by majorbird-team** [comment]
Hello everyone, if someone has the time to look into this, it would be much appreciated :)

**Comment by majorbird-team** [comment]
Hello @MrSimonEmms ,

I setup a proxy on all nodes of the cluster so images can be pulled from google (eu.gcr.io). 
I tried manually on each nodes, it works, I can pull these images using crictl:
- eu.gcr.io/gitpod-core-dev/build/installer:release-2022.05.2.5
- eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-37164c872f55851dbd8126e1b5a8c062bc36fc1b

Still, when I run the install through kots, I see that it still tries to pull the 2 images from proxy.replicated.com, not from eu.gcr.io (google):
- proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/installer:release-2022.05.2.5
- proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-37164c872f55851dbd8126e1b5a8c062bc36fc1b


I searched in the files on the kots webpage, and found references to proxy.replicated.com, in the file ```/overlays/midstream/kustomization.yaml```:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonAnnotations:
  kots.io/app-slug: gitpod
images:
- name: eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader
  newName: proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader
- name: eu.gcr.io/gitpod-core-dev/build/installer
  newName: proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/installer
kind: Kustomization
patchesStrategicMerge:
- pullsecrets.yaml
resources:
- secret.yaml
transformers:
- backup-label-transformer.yaml
```

I am not sure what this file is meant to do, but I believe it could be the source of the issue we face.

I downloaded these files using the kots command ```kubectl kots download --namespace gitpod --slug gitpod```
Then I modified the files to remove the replicated proxy, as follows:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonAnnotations:
  kots.io/app-slug: gitpod
images:
- name: eu.gcr.io/gitpod-core-dev/build/installer
  newName: eu.gcr.io/gitpod-core-dev/build/installer
- name: eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader
  newName: eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader
kind: Kustomization
patchesStrategicMerge:
- pullsecrets.yaml
resources:
- secret.yaml
transformers:
- backup-label-transformer.yaml
```

Then upload the files back to kots using ```kubectl kots upload --namespace gitpod --slug gitpod ./gitpod```
The command is successful.
Though, when I visit the Kots UI again, it seems the change is not applied. Deployments still fail.


I managed to workaround the issue, by tagging the images on each nodes (in lack of better solution):
```
ctr --namespace=k8s.io image tag eu.gcr.io/gitpod-core-dev/build/installer:release-2022.05.2.5 proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/installer:release-2022.05.2.5
ctr --namespace=k8s.io image tag eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-37164c872f55851dbd8126e1b5a8c062bc36fc1b proxy.replicated.com/proxy/gitpod/eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-37164c872f55851dbd8126e1b5a8c062bc36fc1b
```

Then I ran the deploy again on kots, and it worked as the images are detected as already on the machines.
Not great, but we want to get it to work.

Now, I saw the installation requires a lot of images (found a list in the kots-app.yaml file), so we are first letting the nodes pre-download all the images (even with the proxy, the connection to google repositories from here is slow).
Will update you tomorrow !
