### ISSUE TITLE
Installer does not specify Prometheus metrics ports

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#10628]
### Bug description

Our [monitoring docs](https://www.gitpod.io/docs/self-hosted/latest/monitoring) talk of using port `9500` to listen for metrics on self-hosted instances - they may be enabled in some cases, but certainly not in `ws-manager`, which is what we tell people to use. It seems that SaaS deploys an additional service to configure the Prometheus ports in order to connect up our own monitoring systems.

- [x] #12404
- [ ] The "bicycle" and beyond would be to get this working with everything.

### Steps to reproduce

Install Gitpod to self-hosted

### Example repository

See `ws-manager`:

 - Definition of the RPC port in [objects.go](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/ws-manager/objects.go#L18)
 - Definition of the RPC port in [deployment.go](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/ws-manager/deployment.go#L46)

This appears to be enabled in [Open VSX Proxy](https://github.com/gitpod-io/gitpod/blob/4820e804bb86ecee9548ce9f1f9aca761d8436b9/install/installer/pkg/components/openvsx-proxy/objects.go#L21) by comparison

### Anything else?

**IMPORTANT** liaise with @gitpod-io/platform to ensure that we don't fix for @gitpod-io/engineering-self-hosted, but break for SaaS

[Internal discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1655132010452449?thread_ts=1655130178.138969&cid=C01KLC56NP7)

[Services added for SaaS](https://github.com/gitpod-io/observability/blob/645eb421f05bac4131e4265aa6b09e18448981f8/components/gitpod/gitpod.libsonnet#L1110-L1157)

**Comment by AndyDevman** [comment]
could the issues scraping the /metrics from some of the pods be related to the `kube-rbac-proxy`  ?
It looks like the openvsx-proxy pod doesnt have the kube-rbac-proxy container in it whereas the ws-manager does.
I think this is the what the kube-rbac-proxy is based on - https://github.com/brancz/kube-rbac-proxy
One of the use cases indicated is to protect prometheus /metrics endpoints

**Comment by MrSimonEmms** [comment]
Until this is added, this can be achieved by creating a service for monitoring - eg,

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ws-manager-monitoring
  namespace: gitpod
  labels:
    app.kubernetes.io/component: ws-manager
    app.kubernetes.io/monitoring: ws-manager
spec:
  selector: 
    component: ws-manager
  ports:
    - name: metrics
      port: 9500
      targetPort: 9500
      protocol: TCP
```
