### ISSUE TITLE
[installer] Move `defaultBaseImageRegistryWhitelist` out of `experimental` section

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#10791]
We use `defaultBaseImageRegistryWhitelist` in production but it is part of the `experimental` section. We should move this out of `experimental` and replace all occurrences.

Proposal:
```yaml
containerRegistry:
  # If you want to pull workspace base images from a private registry (with credentials), you need to make sure the credentials are available in containerRegistry.external.certificate and add this registry to privateBaseImageRegistries.
  privateBaseImageRegistries:
    - my-registry.example.com
```

I'm open to other naming proposals. However, I would like to avoid the term “whitelist”.

It is likely best to tackle this together with https://github.com/gitpod-io/gitpod/issues/11408

## Value
- Tech-debt
- Allows the use of private base images
