### ISSUE TITLE
[installer] Support adding image pull secrets even when the internal (in-cluster) registry is used

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#10792]
Currently, we can add image pull secrets only when an external registry is used like this:

```yaml
containerRegistry:
  inCluster: false
  external:
    url: my-registry.example.com
    certificate:
      kind: secret
      name: my-registry-credentials
```

However, when we use an in-cluster registry, customers would probably still want to add pull secrets for workspace base images.

I would suggest to deprecate the `certificate` block under `external` and moving it directly under `containerRegistry`. Like this:

```yaml
containerRegistry:
  inCluster: false
  external:
    url: my-registry.example.com
  certificate:
    kind: secret
    name: my-registry-credentials
```

(probably rename “certificate” to “credentials”, however, we probably want to keep this consistent to other occurences of “credentials”, e.g. for the object storage)

That would also allow adding workspace pull secrets when the in-cluster registry is used like this (see also https://github.com/gitpod-io/gitpod/issues/10791):
```yaml
containerRegistry:
  inCluster: true
  certificate:
    kind: secret
    name: my-registry-credentials
  privateBaseImageRegistries:
    - my-registry.example.com
    - my-other-registry.example.com
```

In this case, we need to merge the in-cluster container secret with the secret given here to allow accessing both registries.
- [code pointer](https://github.com/gitpod-io/gitpod/blob/7363937d54ef02e151d343019b0eb31e2bbbddc2/install/installer/pkg/components/blobserve/deployment.go#L26-L33)
- see also [this change](https://github.com/gitpod-io/gitpod/pull/10685/files#diff-633cc9aa71daacd7993fd8af48e3d65d636b1e9a895f0752ff59a98d8c929766R307-R308) where we do this in KOTS already. Once we have this natively supported in the installer, we can replace this hack in KOTS.
- See also - [internal discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1659459083167509) about this
