### ISSUE TITLE
Open/preview forwarded port with a sub path.

### ISSUE THREAD

**Issue by ccll** [gitpod-io/gitpod#10849]
## Is your feature request related to a problem? Please describe

I'm running some third party service in my workspace, and the service opened a port for it's dashboard, which serves on path `/dashboard`, and `open-preview/open-browser` will simply open `/`, incur a 404.

![image](https://user-images.githubusercontent.com/5366582/175233524-3f06f825-dacc-40e8-b2ef-2c76b4f74e53.png)

## Describe the behaviour you'd like

There should be a way to specify the subpath so one can directly open the proper page instead of manually edit the url.

**Comment by akosyakov** [comment]
Try to add the following task in your .gitpod.yml:
```
```

**Comment by akosyakov** [comment]
Thank you for the feature request, as a workaround try to add a task in .gitpod.yml like:
```yml
tasks:
  - command: gp await-port 2379 && && gp preview "$(gp url 2379)/dashboard"
    name: Open in Preview
  - command: gp await-port 2379 && && gp preview "$(gp url 2379)/dashboard" --external
    name: Open in Browser
```

It won't happen each time when a port is served but only once on first client to connect.
