### ISSUE TITLE
Installer customization YAML does not recognise 'apiVersion: "v1"'

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#11106]
### Bug description

The `apiVersion: "v1"` in a customization YAML gets rendered the Installer config correctly, but this is not picked up in the internals - it's omitted entirely when it's pushed through to the config map

`apiVersion: "*"` still works though

### Steps to reproduce

When applying the customization file:

```yaml
customization:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "proxy"
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
```

When looking at the config file (`kubectl get configmaps -n gitpod gitpod -o jsonpath='{.data.config\.yaml}'`), this is rendered as (note the missing `apiVersion`):

```yaml
customization:
- kind: Service
  metadata:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    creationTimestamp: null
    name: proxy
  spec:
    env: null
```

### Expected behavior

The `apiVersion` should be implemented as `v1`

### Anything else?

[Internal discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1656924888317209)
