### ISSUE TITLE
Move default `workspaceImage` setting out of experimental

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#11408]
## Is your feature request related to a problem? Please describe
Currently, to set a global default workspace image, you need to add it to a config patch file in the following manner:
```
experimental:
  webapp:
    server:
      workspaceDefaults:
        # update with the docker image you want for workspaces. If the workspace default
        # base image is stored in a private repo, this registry should be the same as the
        # registry specified in config page in KOTS dashboard. This is the only supported authentication method atm.
        workspaceImage: registry.server.io/repository/workspace-image:latest
```

## Describe the behaviour you'd like
- Default workspace image can be set in the config - happy to chat about where and how exactly. 
- We have a guide in our docs that explains how & why to do this and clarifies the limitations

## Describe alternatives you've considered
- Expect every user to have a image set in the gitpod.yml - this is a hassle for some users, and something they would have to remember for every project / repo. 

## Related ticket
- https://github.com/gitpod-io/gitpod/issues/10791 --> it is likely best to tackle this issue and [10791](https://github.com/gitpod-io/gitpod/issues/10791) together

## Additional context
- Internal [discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1657874824256409?thread_ts=1657874046.907129&cid=C01KLC56NP7)
