### ISSUE TITLE
Refactor ws-daemon postStart hook

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11514]
## Is your feature request related to a problem? Please describe

After ws-daemon starts and pass the readinessProbe, we update the node labels that enable the scheduling of workspaces. In some edge cases, the `store` in `ws-daemon` is not ready and can introduce an issue creating the socket inside workspaces that are being created. The issue creates pods that timeout because cannot reach ws-daemon.

## Describe the behaviour you'd like

Use a different container that waits for the readinessProbe and then updates the labels.

```
- command:
- /bin/bash
- -c
- wait4x http http://localhost:9501/ready -t30s --expect-status-code 200 && sleep 30 && kubectl label --overwrite nodes ${NODENAME} gitpod.io/ws-daemon_ready_ns_${KUBE_NAMESPACE}=true && sleep infinity
env:
- name: NODENAME
  valueFrom:
	fieldRef:
	  apiVersion: v1
	  fieldPath: spec.nodeName
- name: KUBE_NAMESPACE
  valueFrom:
	fieldRef:
	  apiVersion: v1
	  fieldPath: metadata.namespace
image: eu.gcr.io/gitpod-core-dev/build/ws-daemon:commit-<XXXXXXXXXXXXXXXXXXXX>
imagePullPolicy: IfNotPresent
name: ws-daemon-labels
```
