### ISSUE TITLE
ws-manager: the pod keeps in Terminating if the pod can't be scheduled on the node more than 30 minutes

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11673]
### Bug description

We saw in us56 production cluster, the prebuild pod keeps Terminating and can't be finished.
The root cause is that the pod can't be scheduled onto the node for more than 30 minutes.

Some outstanding workspace pod yaml
```yaml
apiVersion: v1
kind: Pod 
metadata:
  annotations:
    gitpod.io/attemptingToCreate: "true"
    gitpod.io/stoppedByRequest: 30s
    gitpod/never-ready: "true"
    gitpod/timedout: workspace timed out after initialization (00h30m) took longer
      than 00h30m
```

The jaeger tracing
<img width="561" alt="image" src="https://user-images.githubusercontent.com/49380831/181182143-eacfbc7b-ccd9-41f4-b0ad-ec9a95aecc9c.png">

### Steps to reproduce

1. Create workspace preview
2. Remove the label `kubectl label node <node-name> gitpod.io/workload_workspace_headless-`
3. Launch the workspace

<img width="942" alt="image" src="https://user-images.githubusercontent.com/49380831/181205103-2e1e2c84-f018-47e7-a122-4a4952005f2c.png">

Code flows:
- The annotation `attemptingToCreatePodAnnotation` added
https://github.com/gitpod-io/gitpod/blob/093e8c6586183660a4bdb9f218e4afd12ca1ad9e/components/ws-manager/pkg/manager/status.go#L342-L346

- No adding the annotation `workspaceFailedBeforeStoppingAnnotation` since the `status.Conditions.Failed == ""`
https://github.com/gitpod-io/gitpod/blob/51375056a4e160e43a71ed7b1cc68e8ef6aab496/components/ws-manager/pkg/manager/monitor.go#L333-L341

- Call StopWorkspace. However, since the pod is Terminating, return it directly
https://github.com/gitpod-io/gitpod/blob/51375056a4e160e43a71ed7b1cc68e8ef6aab496/components/ws-manager/pkg/manager/monitor.go#L354
https://github.com/gitpod-io/gitpod/blob/51375056a4e160e43a71ed7b1cc68e8ef6aab496/components/ws-manager/pkg/manager/manager.go#L691-L698

Note: once the pod is Running, the ws-manager removes the `attemptingToCreatePodAnnotation` annotation
https://github.com/gitpod-io/gitpod/blob/51375056a4e160e43a71ed7b1cc68e8ef6aab496/components/ws-manager/pkg/manager/manager.go#L366-L367
