### ISSUE TITLE
Regular and Prebuild workspaces sometimes get stuck in Stopped on start-up

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11729]
### Bug description

This happens intermittently:
![image](https://user-images.githubusercontent.com/1272076/181518897-d2407b0f-4609-489f-806b-d68c4376d176.png)

And when it does, upon further examination, it's actually a sign that the workspace failed starting. For example:
1. You'll see `Error from server (BadRequest): container "workspace" in pod "" is waiting to start: ContainerCreating` in the workspace pod's logs
2. The status will be Stopped or Failed in the Database
3. The finalizer is never added to the pod
4. the `never-ready` annotation is on the pod 
5. The pod is stuck in `Terminating`
6. `gitpod.io/disposalStatus: {"backupComplete":true,"backupFailure":"cannot find workspace during DisposeWorkspace"}`, could be related to #11715 
7. `gitpod/timedout: workspace timed out after pulling images (01h00m) took longer than 01h00m`

```
kubectl get pod ws-c9e37024-7378-493c-a46f-126811998f98
NAME                                      READY   STATUS        RESTARTS   AGE
ws-c9e37024-7378-493c-a46f-126811998f98   0/1     Terminating   0          115m
kubectl logs ws-c9e37024-7378-493c-a46f-126811998f98
Error from server (BadRequest): container "workspace" in pod "ws-c9e37024-7378-493c-a46f-126811998f98" is waiting to start: ContainerCreating
gpctl workspaces list | grep c9e37024-7378-493c-a46f-126811998f98
e6b9ccf3-fb0c-414c-818e-31966d5e1a96        foo-bar-vq5tlqjiz9p         c9e37024-7378-493c-a46f-126811998f98        STOPPED
```

### Steps to reproduce

n/a

### Workspace affected

n/a

### Expected behavior

The workspace and pod should be terminated gracefully, and not linger.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p5qi)

**Comment by jenting** [comment]
> The finalizer is never added to the pod
> The pod is stuck in Terminating

How's it possible? 🤔  The pod is stuck in Terminating generally means the finalizer is still present.

**Comment by svenefftinge** [comment]
Not sure if related, but I just wanted to start a workspace on gitpod-io/gitpod main. It didn't come up but went to stopped immediately. [The logs](https://cloudlogging.app.goo.gl/mWYAt9k6P6Cq1oH38) complain about image pull issues.

**Comment by jenting** [comment]
> Not sure if related, but I just wanted to start a workspace on gitpod-io/gitpod main. It didn't come up but went to "stopped" immediately. [The logs](https://cloudlogging.app.goo.gl/mWYAt9k6P6Cq1oH38) complain about image pull issues.

I did saw it in preview env before, and I think the behavior is correct because the workspace can't start due to ErrImagePull, so the state changes to stopped.

**Comment by svenefftinge** [comment]
I had that on gitpod.io. The question is why out of the sudden the image cannot be pulled.

**Comment by svenefftinge** [comment]
I remembered that I had another one yesterday and looked it up. It's the same error. 
[It happens a few times a day](https://cloudlogging.app.goo.gl/safJXAt1cSnPsv869). In both cases the image wasn't special (one was plain workspace-full, the other one was our dev image).

**Comment by kylos101** [comment]
@svenefftinge I see `gitpod/timedout: workspace timed out after pulling images (01h00m) took longer than 01h00m` consistently on pods that encounter this behavior. I added as a 7th clue - thank you!

@jenting it seems like terminating pods are not deleted for some reason. Given `kubectl get pod <pod-name> -o yaml`, I see the following for a regular workspace `status` field:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-29T12:16:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-07-29T12:16:04Z"
    message: 'containers with unready status: [workspace]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-07-29T12:16:04Z"
    message: 'containers with unready status: [workspace]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-07-29T12:16:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: reg.ws-eu54.gitpod.io:20000/remote/5f9d2b25-15ee-47d2-97da-819d82db1bb9
    imageID: ""
    lastState: {}
    name: workspace
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
```

It seems like if `ContainersReady` is false, the pod will not be deleted, like it must be allowed to complete it's life cycle first. Still investigating.
