### ISSUE TITLE
Support multiple start tasks for different start kinds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#119]
We should 
 - allow multiple tasks in the `.gitpod`
 - allow specifying `on` what kind of start a task should be executed.

Atm I see two different scenarios: `clone` and `restart`.
Example:
```yml
ports:
  - port: 3000
    protocol: "http"
tasks:
  - command: "yarn install && yarn build"
    on: clone
  - command: "yarn build"
    on: restart
```
For each task a terminal shall be opened.
