### ISSUE TITLE
Failing to start Kubernetes Cluster

### ISSUE THREAD

**Issue by jim-junior** [gitpod-io/gitpod#11940]
### Bug description

I have been trying to spin up kubernetes clusters using [minikube](https://minikube.sigs.k8s.io/docs/) and [kind](https://kind.sigs.k8s.io/) but they keep on failing.
When i try creating a cluster using kind i get this error:
```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: command "docker run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false --volume /dev/mapper:/dev/mapper --publish=127.0.0.1:38777:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e" failed with error: exit status 126
Command Output: 3a7302b609e2f16085868b83017b49c45658df4c854bcb85e4924995233de988
docker: Error response from daemon: error while creating mount source path '/dev/mapper': mkdir /dev/mapper: permission denied.
```
When i try minikube it never starts it just stops at this:
```
😄  minikube v1.26.1 on Ubuntu 20.04 (amd64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
```
I tried in codespaces and it works well but i just prefer gitpod and I would like to know if there is a walk around this error.

### When using minikube
I first install minikube
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
```
then run
```bash
minikube start
```
### When using kind
Installing kind
```sh
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
```
Then i run
```
kind create cluster --config kind-config.yaml
```
The contents of `kind-config.yaml`
```yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 31001
    hostPort: 80
    protocol: TCP
  - containerPort: 32002
    hostPort: 443
    protocol: TCP
```
