### ISSUE TITLE
Vala syntax highlighting

### ISSUE THREAD

**Issue by aggsol** [gitpod-io/gitpod#1242]
Having syntax highlighting for `*.vala` files would be great. As a first work around using the C# highlighter for files with `*.vala` extension would be very helpful. Those two language are very similar.

**Comment by JesterOrNot** [comment]
I will look into this!

**Comment by JesterOrNot** [comment]
Would something like this work?
![image](https://user-images.githubusercontent.com/50386709/74936044-08308080-53af-11ea-99ae-a92a922f6ea8.png)

**Comment by JesterOrNot** [comment]
If so add the following to your [.gitpod.yml](https://www.gitpod.io/docs/config-gitpod-file/)
```yaml
vscode:
  extensions:
    - thiagoabreu.vala@0.3.5:wpqKL9G/pGRsFlLDBLF2hA==
```
