### ISSUE TITLE
Ability to support ENVs for monorepos

### ISSUE THREAD

**Issue by ctrlaltdylan** [gitpod-io/gitpod#12627]
## Is your feature request related to a problem? Please describe
Monorepos host multiple apps in one repository.

If one or more of the apps use the same ENV variable, there's a conflict.

Currently Workspace ENV vars are only specific to the repository, not to a sub-app.

## Describe the behaviour you'd like

Would be great if the ENV definition in the task was able to support dynamic ENVs.

Then we could create "aliases":

```
  - name: Backend
    env:
      PORT: ${BACKEND_PORT}
    init: |
      yarn dev --scope=@backend
  - name: Fronend
    env:
      PORT: ${FRONTEND_PORT}
    init: |
      yarn dev --scope=@frontend
```

## Describe alternatives you've considered

Trying to make a bash script to reproduce this.

## Additional context

https://discord.com/channels/816244985187008514/839379835662368768/1015296414286360587
