### ISSUE TITLE
The BlockNewUsers param is no longer being respected by server

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#12738]
### Bug description

The Installer has a `BlockNewUsers` block which is passed into the Server's config map. The purpose of this is to offer measure of security to self-hosted owners who do not wish for their instance to be used by people not authorised.

### 1. In KOTS, enable the user management option and enter your domain (eg, `simonemms.com`)

![image](https://user-images.githubusercontent.com/275848/188908106-58852396-6063-4e3a-aaed-30b2bc4cfd78.png)

### 2. Check that this is set

- `kubectl get configmaps -n gitpod gitpod -o jsonpath='{.data.config\.yaml}'` to check the Installer's configmap ([example](https://github.com/gitpod-io/gitpod/issues/12738#issuecomment-1244967575))
- `kubectl get configmaps -n gitpod server-config -o jsonpath='{.data.config\.json}'` to check the server config map ([example](https://github.com/gitpod-io/gitpod/issues/12738#issuecomment-1244973722))

### 3. Login with your GitHub account, where the primary email is on the domain

This works

### 4. Get a friend (or a second GitHub account) not on the domain and get them to register

I got @adrienthebo to register who does not have a `simonemms.com` email address. He was able to login

### Workspace affected

All. Using latest `2022.8.0` release in the `stable` channel

### Expected behavior

@adrienthebo should not have been able to register

**Comment by gtsiolis** [comment]
Ideally, we could also move this configuration to the admin dashboard instead of relying on KOTS. 💡

**Comment by MrSimonEmms** [comment]
@gtsiolis yes, that's the long-term plan - still need to get the bug fixed though

**Comment by corneliusludmann** [comment]
Just to be sure: The config value in the installer is set correctly, the value is set in the server's config map correctly, and still, the server does not pick this config up, right?

That means that can be easily reproduced in an ordinary preview env by adding the config to the installer config or server config map without the need for the KOTS installation flow, right? (I mean, that could be easier for Team WebApp to reproduce. :thinking:)

**Comment by geropl** [comment]
thx @corneliusludmann and @MrSimonEmms for highlighting. Scheduled for next week. :calendar:

**Comment by MrSimonEmms** [comment]
@corneliusludmann yes, you're correct - the config is set correctly so it can be deployed anywhere and the bug should still exist

**Comment by AlexTugarev** [comment]
@MrSimonEmms, for completeness, could you please paste an example of the `blockNewUsers` config json. I couldn't find any related changes made in this area in the past 5 months.

**Comment by MrSimonEmms** [comment]
@AlexTugarev the configmap is:

```yaml
apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: true
  passlist:
  - simonemms.com
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: true
  privateBaseImageAllowList: []
database:
  inCluster: true
disableDefinitelyGp: true
domain: k3s.gitpod.simonemms.com
kind: Full
license:
  kind: secret
  name: gitpod-license
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
  resources:
    requests:
      memory: 2Gi
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  maxLifetime: 36h0m0s
  pvc:
    size: 30Gi
    snapshotClass: ""
    storageClass: ""
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/k3s/containerd/containerd.sock
    fsShiftMethod: fuse
```
