### ISSUE TITLE
Gitpod 2022.08.0 doesn't support cpu burst/min values

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12848]
### Bug description

Gitpod SaaS supports the ability to specify min and burst limit values; this value does not appear to work in Gitpod self-hosted

### Steps to reproduce

Apply the following config patch during installation:

```yaml
workspace:
  pvc:
     size: 20Gi
     snapshotClass: "csi-aws-vsc"
     storageClass: "ebs-sc"
   resources:
     requests:
       cpu: "1"
       memory: 2Gi
     limits:
       cpu:
         min: "4"
         burst: "8"
      memory: 32Gi
```

The installer will fail with the following:

```
Error: error loading config: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
