### ISSUE TITLE
FeaReg: Add 'packages:' property in `.gitpod.yml`

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1294]
Proposing to add property `packages:` in `.gitpod.yml` that would expand in dockerfile instructions to add packages on target dockerfile.

### Example use

in `.gitpod.yml`

```yml
distro: debian

package:
  - shellcheck
```

Expands in

```
FROM debian:latest

USER root

RUN apt-get update && apt-get install -y shellcheck
```
