### ISSUE TITLE
typo in automated project initialization

### ISSUE THREAD

**Issue by tianhaoz95** [gitpod-io/gitpod#1300]
### Describe the bug

The automated project initialization initializes my `.gitpod.yml` to have the following:

```yml
tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with omething that should run on every start, or just
      remove me entirely."
```

where "s" is missing from "something".

### Steps to reproduce

open an empty project and click on init project button

### Expected behavior

should be "something"

### Additional information

n/a
