### ISSUE TITLE
Port view is empty

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#13377]
### Bug description

The new default ports view appears empty.

### Steps to reproduce

Start a workspace with the following ports defined in `.gitpod.yml`:

```yaml
ports:
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3005
    onOpen: ignore
  - port: 3080
    onOpen: ignore
    visibility: public
  - port: 5001
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 8020
    onOpen: ignore
  - port: 8030
    onOpen: ignore
  - port: 8040
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 9090
    onOpen: ignore
  - port: 9323
    onOpen: ignore
```

### Expected behavior

The ports view lists all ports.

### Example repository

It happens for a private repo. If additional info is required beyond the ports configuration in `.gitpod.yml` as shared above, please let me know.
