### ISSUE TITLE
Last backup failed: final backup failed Error on Self-Hosted 2022.09rc4 when manually stopping workspace

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#13491]
### Bug description

<img width="1678" alt="Screenshot 2022-09-30 at 14 18 34" src="https://user-images.githubusercontent.com/22516873/193271011-2d5c8af3-e7b2-48a6-aa80-30dfe472e726.png">
When manually stopping a workspace, I recieved an error that the "last backup failed: final backup failed." This happened after I had the workspace running for some time (about one hour), and then extended the timeout to 3h and then stopped the workspace 

Environment: 
- Gitpod Self-Hosted version 2022.09rc4 (I believe, could be rc3)
- Internally launched preview environment on GCP using our scripts ([this](https://www.notion.so/gitpod/0534b6ba181b476cb1826e358a7149f9#819867816e5f4c39b89a8831eb26d59c) one, although the link might be oudated if the environment is recreated)

### Steps to reproduce

Open a workspace in an environment launched by our internal pipeline on the same version as above. Wait for a while, then extend the timeout to 3h (not sure if this is relevant, but this is what I did), then stop the workspace manually from within the VS Code Desktop UI

**Comment by atduarte** [comment]
@lucasvaltl I know it will take a while, but could you check whether it's reproducible? Also, the logs you mentioned in Slack would help for sure 🙏

**Comment by lucasvaltl** [comment]
Working on getting the logs. Fwiw, the workspace id in question was: `gitpodio-website-qots97tlz3s`

**Comment by MrSimonEmms** [comment]
The support bundle (with all the logs etc) is uploaded to our [Vendor portal](https://vendor.replicated.com/troubleshoot/analyze/2022-09-30@12:59)

The config.yaml is:

```yaml
apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  external:
    certificate:
      kind: secret
      name: container-registry
    url: gcr.io/sh-automated-tests
  inCluster: false
  privateBaseImageAllowList: []
database:
  inCluster: true
disableDefinitelyGp: true
domain: release-gcp.tests.gitpod-self-hosted.com
httpProxy:
  kind: secret
  name: http-proxy-settings
kind: Full
license:
  kind: secret
  name: gitpod-license
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
  resources:
    requests:
      memory: 2Gi
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
sshGatewayHostKey:
  kind: secret
  name: ssh-gateway-host-key
workspace:
  maxLifetime: 36h0m0s
  pvc:
    size: 30Gi
    snapshotClass: ""
    storageClass: ""
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /run/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: shiftfs
```

**Comment by MrSimonEmms** [comment]
The support bundle (with all the logs etc) is uploaded to our [Vendor portal](https://vendor.replicated.com/troubleshoot/analyze/2022-09-30@12:59)

The config.yaml is:

```yaml
apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  external:
    certificate:
      kind: secret
      name: container-registry
    url: gcr.io/sh-automated-tests
  inCluster: false
  privateBaseImageAllowList: []
database:
  inCluster: true
disableDefinitelyGp: true
domain: xxxx
httpProxy:
  kind: secret
  name: http-proxy-settings
kind: Full
license:
  kind: secret
  name: gitpod-license
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
  resources:
    requests:
      memory: 2Gi
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
sshGatewayHostKey:
  kind: secret
  name: ssh-gateway-host-key
workspace:
  maxLifetime: 36h0m0s
  pvc:
    size: 30Gi
    snapshotClass: ""
    storageClass: ""
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /run/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: shiftfs
```
