### ISSUE TITLE
init task doesn't stop on failure

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/gitpod#13520]
### Bug description

Gitpod doesn't stop with an error when init task command fails.

### Steps to reproduce

 In the `.gitpod.yml` below (for Ruby project) `gitpod/workspace-ruby-2` image comes without `yarn`, but init script continues to run after `yarn install` failed.

```yaml
image: gitpod/workspace-ruby-2

tasks:
  - init: |
      bundle install
      yarn install --frozen-lockfile
      bundle exec rake
      bundle exec nanoc compile
    command: bundle exec nanoc live --port=3004
```

### Workspace affected

abitrolly-gitlabdocs-1ymjgt70jro

### Expected behavior

Failure and stopping after `yarn install` would make it much easier to spot and debug errors.

### Example repository

https://gitlab.com/gitlab-org/gitlab-docs/ (it might be fixed soon)
