### ISSUE TITLE
ImageBuild can't pull workspace-full

### ISSUE THREAD

**Issue by Nefelim4ag** [gitpod-io/gitpod#13551]
### Bug description

```
{"level":"info","message":"building workspace image","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-10-03T22:59:04Z"}
{"level":"info","message":"waiting for build context","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-10-03T22:59:04Z"}
{"level":"info","message":"serving request","req":"/v2/gitpod/workspace-full/manifests/sha256:de0088de2524ec085b619d34d48c69189d289dc6898879a6e49255219e19406a","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-10-03T22:59:04Z"}
2022/10/03 22:59:04 [DEBUG] HEAD https://registry-1.docker.io/v2/gitpod/workspace-full/manifests/sha256:de0088de2524ec085b619d34d48c69189d289dc6898879a6e49255219e19406a
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 133B done
#2 DONE 0.1s

#3 [internal] load metadata for localhost:8080/base@sha256:de0088de2524ec085b619d34d48c69189d289dc6898879a6e49255219e19406a
{"host":"registry-1.docker.io","level":"info","message":"authorizing registry access","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-10-03T22:59:04Z","user":""}
2022/10/03 22:59:04 [DEBUG] HEAD https://registry-1.docker.io/v2/gitpod/workspace-full/manifests/sha256:de0088de2524ec085b619d34d48c69189d289dc6898879a6e49255219e19406a (status: 401): retrying in 1s (3 left)
```

### Steps to reproduce

I use a local installer on EKS, external/internal, version (2022.06.01 ... 2022.09.0-rc5) of the installer doesn't affect anything.
Even changing the image repo to the local proxy cache doesn't affect log output and behavior.
("docker.io/gitpod/workspace-full:latest" to "proxy-cache/gitpod/workspace-full:latest")

**Comment by Nefelim4ag** [comment]
https://github.com/gitpod-io/gitpod/issues/7114#issuecomment-988647983 same as here

**Comment by adrienthebo** [comment]
Hi @Nefelim4ag, thanks for submitting this issue! To confirm my understanding, you're running Gitpod on EKS; can you indicate which container registry you're using to store the images that Gitpod is building? Do you have any custom container registry credentials configured in the KOTS UI?

**Comment by Nefelim4ag** [comment]
I use gitpod installer, not KOTS (kots is just stuck at license upload and useless IMHO )
I've tried to use harbor registry, but even with a built-in container registry (inCluster: true) (which uses the same underline docker registry container) that doesn't work, because it can't pull workspace-full image from docker.io registry.

```
apiVersion: v1
authProviders:
  - kind: secret
    name: gitlab-auth
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: false
  external:
    url: harbor.dev.example.net/gitpod
    certificate:
      kind: secret
      name: gitpod-harbor
database:
  inCluster: false
  external:
    certificate:
      kind: secret
      name: gitpod-db-access
disableDefinitelyGp: true
domain: "gitpod.example.net"
kind: Full
metadata:
  region: eu-west-1
  shortname: fabros
objectStorage:
  inCluster: false
  s3:
    endpoint: s3.amazonaws.com
    credentials:
      kind: secret
      name: gitpod-s3-access
observability:
  logLevel: debug
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  maxLifetime: 24h0m0s
  pvc:
    size: 30Gi
    snapshotClass: ""
    storageClass: "efs"
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
```

with built-in registry:

```
apiVersion: v1
authProviders:
  - kind: secret
    name: gitlab-auth
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: tru
database:
  inCluster: false
  external:
    certificate:
      kind: secret
      name: gitpod-db-access
disableDefinitelyGp: true
domain: "gitpod.example.net"
kind: Full
metadata:
  region: eu-west-1
  shortname: fabros
objectStorage:
  inCluster: false
  s3:
    endpoint: s3.amazonaws.com
    credentials:
      kind: secret
      name: gitpod-s3-access
observability:
  logLevel: debug
openVSX:
  url: https://open-vsx.org
repository: eu.gcr.io/gitpod-core-dev/build
workspace:
  maxLifetime: 24h0m0s
  pvc:
    size: 30Gi
    snapshotClass: ""
    storageClass: "efs"
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
```
