### ISSUE TITLE
Jetbrains: Installing extensions does not work with prebuild enabled

### ISSUE THREAD

**Issue by shyim** [gitpod-io/gitpod#13770]
### Bug description

When you add Jetbrains extensions to your gitpod.yml and later enable prebuild. The extensions will not be installed anymore.

### Steps to reproduce

Have a gitpod with

```yml
jetbrains:
  phpstorm:
    plugins:
      - de.espend.idea.php.annotation
      - fr.adrienbrault.idea.symfony2plugin
```

It works

Enable prebuild in gitpod

The extensions are missing now

### Expected behavior

The extensions are always installed
