### ISSUE TITLE
Update current Start Workspace SLO to use semantic metric

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14075]

**Comment by jankeromnes** [comment]
**Question**: What does this issue title mean? Also, is it a duplicate of https://github.com/gitpod-io/gitpod/issues/14074 ?

**Comment by easyCZ** [comment]
In https://github.com/gitpod-io/gitpod/issues/14074 we want to create a second SLO which does not include the ws-manager side of the call (we stop measuring just before we issue the ws-manager call).

Here, it refers to not using 2 different metrics (which are semantically different) but use only one.
```
success:
        metric: gitpod_server_api_calls_duration_seconds_bucket{method="startWorkspace",le="10"}
      total:
        metric: gitpod_server_api_calls_total{method="startWorkspace",statusCode!~"4.."}
```
Here we use `gitpod_server_api_calls_total` for the total metric, but we use `gitpod_server_api_calls_duration_seconds_bucket` for the successes.

We want to use `gitpod_server_api_calls_duration_seconds_bucket` for the total also. Additionally, it's not semantic as the total excludes 4xx errors, while the success includes them.
