### ISSUE TITLE
Ignoring port ranges fails

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1442]
### Describe the bug

when doing `onOpen: ignore` on a port range not all of the ports are ignored

### Steps to reproduce

create a ports config like the following:

```yaml
ports:
  - port: 50-60
    onOpen: ignore
```

### Expected behavior

All ports to be ignored

### Example repository

https://github.com/eclipse/openvsx
