### ISSUE TITLE
VSCode extension latest version

### ISSUE THREAD

**Issue by PatMyron** [gitpod-io/gitpod#1455]
Pinning VSCode extension versions is really cool:
```yaml
tasks:
- init: pip3 install cfn-lint
vscode:
  extensions:
    - kddejong.vscode-cfn-lint@0.10.20:3jS39ZZBIttaSEQP0R5BKg==
```
Would it also be possible to install the latest version of a VSCode extension? 
```yaml
tasks:
- init: pip3 install cfn-lint
vscode:
  extensions:
    - kddejong.vscode-cfn-lint
```

https://www.gitpod.io/docs/vscode-extensions/
