### ISSUE TITLE
[self-hosted] Baremetal install can't pass from validate-config

### ISSUE THREAD

**Issue by dnegrisolli** [gitpod-io/gitpod#14666]
### Bug description

I'm facing a problem in a K8s instance baremetal.
I'm using ingress-nginx, metallb and trying to install the gitpod from Helm in the gitpod namespace.
The validate-config Pod can't go further (and I can't move to the control panel), and shows the problem:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-14T02:11:08Z"
    message: '0/2 nodes are available: 2 node(s) didn''t match Pod''s node affinity/selector.
      preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.'
```
2- The ingress for the main URL (gitpod.artyou.net) is done but I also don't know the service I should point it. I'm pointing to "kotsadm"

3- When it starts the validate-config pod gives this label error and I see only this labels in the cluster:

```
$ kubectl label --list nodes srvsa1
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
kubernetes.io/arch=amd64
kubernetes.io/hostname=srvsa1
kubernetes.io/os=linux
node-role.kubernetes.io/control-plane=
node.kubernetes.io/exclude-from-external-load-balancers=

$ kubectl label --list nodes srvsa2
kubernetes.io/hostname=srvsa2
kubernetes.io/os=linux
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
kubernetes.io/arch=amd64
```
and never finishes the install. I did 4 times erasing all the cluster (and installing Ubuntu again) and it seems is not a localizated problem.

[validate-config-pod-level.txt](https://github.com/gitpod-io/gitpod/files/10004019/validate-config-pod-level.txt)

### Steps to reproduce

In a baremetal instance, try intall the latest version of Gitpod using helm. 

### Workspace affected

gitpod

### Expected behavior

The install should finish
