### ISSUE TITLE
Workspace timeout 30m on self-hosted

### ISSUE THREAD

**Issue by msiegenthaler** [gitpod-io/gitpod#14840]
### Bug description

Since I updated from 2022.8.0 to 2022.10.2 on our self-hosted instance we experience very short workspace timeouts of just 30 minutes. Previously we had the following config
```
    workspace:
      timeoutDefault: 36h
      timeoutExtended: 96h
      maxLifetime: 168h
      timeoutAfterClose: 36h
```

that gave us longer timeouts. 
Also we cannot extend the timeout anymore from VS Code (Cannot extend workspace timeout: Error: enterprise license required).

We run the free community version with 3 users. Is this an expected behaviour? I didn't see anything mentioned in the documentation that the free version with less that 10 users was having this restriction.

Let me finishing by thanking you so much for the great development environment experience gitpod provides, it's really a great piece of software!

### Steps to reproduce

- Deploy self-hosted instance
- apply above workspace configuration
- check workspace timeout in VS Code
