### ISSUE TITLE
Make gitpod's build output bigger

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1502]
I usually test gitpod this way:
![image](https://user-images.githubusercontent.com/11302521/81794805-a09c5400-950b-11ea-9903-51151d012ff3.png)

Where the build output is too small which makes me to make customCSS all the time that is annoying..

### Expected

Add a toggle switch that would make the build output on whole page

**Comment by jankeromnes** [comment]
@Kreyren Excellent idea, thanks! We could add a sort of Maximize/Fullscreen button.

Do you happen to have the custom CSS at hand? 😇

**Comment by Kreyren** [comment]
> Do you happen to have the custom CSS at hand? :innocent: @jankeromnes

I doubt that it works outside of my environment though..

```css
.start .log .log-container {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    height: 100%;
}
```
