### ISSUE TITLE
workspaceLocation does not work on VSCode desktop

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#15043]
### Bug description

One of our projects if using `workspaceLocation` configuration in `.gitpod.yml` file.

It opens the required structure as defined if we open in browser but that doesn't work in VSCode Desktop.

### Steps to reproduce

Here's the `gitpod.yml` file
```yml
image:
  file: .gitpod.Dockerfile

workspaceLocation: /workspace/flat/.code-workspace
```

and `.code-workspace` file is:

```json
{
  "folders": [
    {
      "name": "webapp",
      "path": "."
    },
    {
      "name": "api",
      "path": "/workspace/api"
    }
  ],
  "settings": {
    "explorer.expandSingleFolderWorkspaces": false,
    "typescript.tsdk": "node_modules/typescript/lib"
  }
}
```

### Anything else?

Link to Discord [conversation](https://discord.com/channels/816244985187008514/1042775691927752754).
