### ISSUE TITLE
Unable to open workspace - x509 error on ide-proxy pod with private registry

### ISSUE THREAD

**Issue by quadeare** [gitpod-io/gitpod#15195]
## Context : 

- RKE2 cluster
- Gitpod-installer binary
- Private image registry

ide-proxy pod return x509 error with a private image registry.
So i'm unable to open workspace and get IDE working.

![image](https://user-images.githubusercontent.com/3419613/205994541-28c9c027-f057-4603-a232-67a93c5cd979.png)

### Steps to reproduce

- Install Gitpod with gitpod-installer
- Use private container registry
- Try open a workspace

## Config : 

```
apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: gitpod-tls
customCACert:
  kind: secret
  name: gitpod-ca-certificate
containerRegistry:
  inCluster: true
  privateBaseImageAllowList:
    - harbor.xx.xx.xx
    - artifactory.xx.xx
    - reg.gitpod.xx.xx
database:
  inCluster: true
disableDefinitelyGp: true
domain: "gitpod.xx.xx"
kind: Full
metadata:
  region: local
  shortname: default
objectStorage:
  inCluster: true
observability:
  logLevel: info
openVSX:
  url: https://open-vsx.org
repository: harbor.xx.xx.xx/gitpod/
workspace:
  maxLifetime: 36h0m0s
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/k3s/containerd/containerd.sock
    fsShiftMethod: fuse
```

### Workspace affected

ide-proxy
