### ISSUE TITLE
Gitpod does not output a helpful message on syntax error in .gitpod.yml

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1527]
Running following `.gitpod.yml`:

```yaml
image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install && npm install -g firebase firebase-tools
 ports:
    # Set for `firebase login:ci` which opens authentification on google.com website that doesn't work in iframe (iframe used by theia's preview)
  - port: 9005
    onOpen: open-browser
```

(notice additional space before `ports`)

Results in gitpod building on a default image.
