### ISSUE TITLE
could not translate host name "host.docker.internal" to address: Name does not resolve

### ISSUE THREAD

**Issue by doublefx** [gitpod-io/gitpod#15272]
### Bug description

When using docker-compose, could not translate host name "host.docker.internal" to address: Name does not resolve.

gitpod /workspace/demo (gitpod) $ `docker-compose up`
[+] Running 3/0
 ⠿ Network demo_default  Created 0.0s
 ⠿ Container pg-db                        Created 0.0s
 ⠿ Container pg_client                    Created 0.0s
Attaching to pg-db, pg_client
pg-db      | 
pg-db      | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg-db      | 
pg-db      | 2022-12-09 11:33:40.866 UTC [1] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
pg-db      | 2022-12-09 11:33:40.866 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg-db      | 2022-12-09 11:33:40.867 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg-db      | 2022-12-09 11:33:40.868 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg-db      | 2022-12-09 11:33:40.871 UTC [41] LOG:  database system was shut down at 2022-12-09 11:33:32 UTC
pg-db      | 2022-12-09 11:33:40.874 UTC [1] LOG:  database system is ready to accept connections
**_pg_client  | psql: error: could not translate host name "host.docker.internal" to address: Name does not resolve_**
pg_client exited with code 2

gitpod /workspace/demo (gitpod) $ `docker network inspect demo_default`
``` json
[
    {
        "Name": "demo_default",
        "Id": "5dbfcb2b4fe55f5cdf92018f9ff8aa3cf8bacb65b110778409563b974f3d963a",
        "Created": "2022-12-09T11:41:04.000687561Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.21.0.0/16",
                    "Gateway": "172.21.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "ee0c4bb9a72ac746d0701fe9bdc6f5ba35c09805d66d9c0b045c72df6d409339": {
                "Name": "pg-db",
                "EndpointID": "0a3ea7f0b1ea8e01dd50b7dcb02b94bcde0d7b70b7b5ec43b5b5518b6edbc173",
                "MacAddress": "02:42:ac:15:00:02",
                "IPv4Address": "172.21.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.mtu": "1440"
        },
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "demo",
            "com.docker.compose.version": "2.10.0"
        }
    }
]
```

### Steps to reproduce

1. Create/Open a gitpod project
2. Create pg-client.Dockerfile:
``` dockerfile
FROM alpine:latest
RUN apk --no-cache add postgresql15-client
ENTRYPOINT psql
```
3. Create a docker-compose.yml:
``` yaml
version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    container_name: pg-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pg_client:
    environment:
      PGDATABASE: postgres
      PGHOST: ${POSTGRES_HOST:-host.docker.internal}
      PGPORT: ${POSTGRES_PORT:-5432}
      PGUSER: ${POSTGRES_USER:-admin}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-admin}
    build:
      context: .
      dockerfile: pg-client.Dockerfile
    container_name: pg_client
    depends_on:
      - db

volumes:
  db:
    driver: local
```
4. Run `docker-compose up`

### Expected behavior

The client can connect the db via `host.docker.internal`
