### ISSUE TITLE
.gitpod.yml window(tab?) management system for multiple monitor setups.

### ISSUE THREAD

**Issue by JesseRigon** [gitpod-io/gitpod#15279]
I love gitpod (online I don't use locally much) but I loved having multiple monitor setups.

Gitpod can currently create terminals and place them. It also can create new browser tabs programatically. So it seems the base ingredients are there.
I would like it if I could setup the yml to have two (or more) tabs(windows) with different interface components declared.

I understand that vs-codes interface components, meaning the top bar, footer bar, and extension panel, would have to be there across all tabs related to a particular container. Though with the side panel closed it wouldnt

```
Display: 
     tab1:
         - name: Main
           vspanel: open
           terminals: none
    tab2:
        - name: Terminals 
          vspanel: closed
          terminals:
              taskgroups: |
                  group1
                  group2
 ```

I'm not sure how this would play with the current tasks structure in regards to terminal management but I think you get it.
