### ISSUE TITLE
Gitpod's preview does not show google.com pages.

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1528]
Gitpod's preview shows a blank page if `gp preview google.com` is invoked

This prevents some google-depending services like firebase to not work since they require a token from a google-hosted domain.

### Steps to reproduce
Use this `.gitpod.yml` on any repository

```yaml
image: gitpod/workspace-full-vnc:latest
tasks:
  - init: npm install --global npm firebase firebase-tools
    command: firebase login
```

### Additional informations
Google blocks `iframe` which is used in gitpod's preview according to @jankeromnes
