### ISSUE TITLE
"PVC" extra config issue: missing the required PVC snapshotClass attribute

### ISSUE THREAD

**Issue by tdensmore** [gitpod-io/gitpod#15334]
### Bug description

When enabling the ALPHA snapshot PVC feature, the correct volume snapshot class is not specified. This results in errors:

> I1208 20:31:20.343117    1 snapshot_controller_base.go:221] Failed to sync snapshot "gitpod/f14b6b78-18c8-45ae-a759-87cc61099876", will retry again: volumesnapshotclass.snapshot.storage.k8s.io "" not found

This is the current spec (broken):

```
workspace:
  maxLifetime: 36h0m0s
  pvc:
    size: 30Gi
    snapshotClass: "csi-aws-vsc"
    storageClass: "ebs-sc"
```

This is the correct spec:

```
workspace:
  maxLifetime: 36h0m0s
  pvc:
    size: 30Gi
    snapshotClass: "csi-aws-vsc"
    storageClass: "ebs-sc"
  prebuildPVC:
    size: 30Gi
    snapshotClass: "csi-aws-vsc"
    storageClass: "ebs-sc"
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "8"
      memory: 32Gi
```

These errors are correlated to this change: https://github.com/gitpod-io/gitpod/commit/140022e851f592c9b46e67c5d302bb5635dd7cbb

### Steps to reproduce

Enable the PVC support on both the project and enable the PVC feature flag on users:

1. Go to Gitpod Settings -> General -> Workspaces -> Enable Persistent Volume Claim

### Expected behavior

Workspaces should start up correctly.

### Anything else?

Reported by a customer
