### ISSUE TITLE
[ws-manager] `gitpod_ws_manager_workspace_starts_failure_total` does not increment on failure

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15335]
### Bug description

`gitpod_ws_manager_workspace_starts_failure_total` doesn't appear to increment with some limited tests I ran. [Context.](https://github.com/gitpod-io/gitpod/pull/15138#issuecomment-1349627352)

### Steps to reproduce

From a harvester preview vm, start a workspace, write some data, stop the workspace, scale minio to zero after it finishes, try restarting the workspace with minio at zero.

### Workspace affected

n/a

### Expected behavior

When `ws-manager` fails starting a workspace then `gitpod_ws_manager_workspace_starts_failure_total` should increment

### Anything else?

`gitpod_ws_manager_workspace_starts_failure_total` was introduced in https://github.com/gitpod-io/gitpod/pull/15138

**Comment by jenting** [comment]
The current `gitpod_ws_workspace_starts_failure_total` increases when the workspace pod can’t in running state. For examples: fails to create a workspace pod, the workspace pod not in running state.

Given the reproduce steps mentioned in this issue, the workspace pod is running but fails at initial the workspace content.

We could add one more metric to track the workspace pod content is not ready.

**Comment by kylos101** [comment]
👋 Hi @jenting , I hope you continue to have a nice vacation! 🌴 

> The current gitpod_ws_workspace_starts_failure_total increases when the workspace pod can’t in running state.

I see, thank you for sharing, I did not know. So, it'd increment if, say for example, we cannot pull the workspace image?

> Given the reproduce steps mentioned in this issue, the workspace pod is running but fails at initial the workspace content.

The steps I added were just one example for content init failure. You can also break ws-daemon [like so](https://github.com/gitpod-io/gitpod/pull/15431), so that content init fails. 

> We could add one more metric to track the workspace pod content is not ready.

Why add a metric? In other words, why not reuse this existing metric, which is part of our SLOs in [Pyrra](https://pyrra.gitpod.io/objectives?expr=%7B__name__=%22workspace-start-workspace-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22%7D&grouping=%7B%7D)? In both cases or steps to recreate (failed minio, or [ws-daemon](https://github.com/gitpod-io/gitpod/pull/15431)), startWorkspace is failing for ws-manager.

In Pyrra, SLO is defined as follows:
```
spec:
  alerting:
    name: WorkspaceStartWorkspaceRatio
  description: Success ratio of regular workspace starts
  indicator:
    ratio:
      errors:
        metric: gitpod_ws_manager_workspace_starts_failure_total{type="REGULAR", cluster!~"ephemeral.*"}
      grouping: null
      total:
        metric: gitpod_ws_manager_workspace_starts_total{type="REGULAR", cluster!~"ephemeral.*"}
```
