### ISSUE TITLE
[Config] Separated 'init' command

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#154]
I'd like to change the lately introduced 'on' property, because how it is used is leading to duplication.
Here is an example for a simple gatsby project:
```yaml
tasks:
- on: init
  command: npm install && npx gatsby develop --host 0.0.0.0
- on: restart
  command: npx gatsby develop --host 0.0.0.0
```
As you can see it has two commands, one for 'init' one for 'restart'. Both share the stuff that should always happen and only the bits needed in 'init' are preprended in the first one. Besides the duplication, this has the consequence that we are not able to execute only the 'init' part. But we will need that for prebuilt workspaces #146. So my proposal is to write it like this instead:
```yaml
tasks:
- init: npm install
  command:  npx gatsby develop --host 0.0.0.0
```
That is a task has an `init` and the existing `command` property. Both would be optional.
On initial workspace starts we use the '&&'  operator and run both in a terminal.
On restarted workspaces we only run the command.
To prebuild workspaces we only run the 'init' part.

The contract for `init` also needs to be that the command terminates eventually.

**Comment by svenefftinge** [comment]
An offline discussion revealed that there are cases where you would want to run some sort of prerequisite scripts in any case. An example would be to configure the system with something that is needed by the build, as well. To keep it declaratively we will add a third property `before`.

To make it more flexible and solve unconsidered situations, we could pass in an environment variable containing the execution mode (e.g. 'prebuild', 'cloned', 'restart'). But I'd like to wait for a real use case to not make it unnecessarily complicated.

**Comment by svenefftinge** [comment]
Also we will remove the `args` and the `cwd` property as they are not used and it would further complicate things to maintain them.

**Comment by meysholdt** [comment]
I very much like the [approach of package.json scripts](https://docs.npmjs.com/misc/scripts). We could use the same pattern:
* A code snippet is called a task
* A task has a name
* there is a naming convention for standard events, such as `restart` or `init`, but users can introduce their own names.
* this allows to extract shared code.

This issue's example could look as follows:

```yaml
tasks:
- name: init
  command: npm install && gp launch-preview
- name: restart
  command: gp launch-preview
- name: launch-preview
  command: npx gatsby develop --host 0.0.0.0
```

Additional perks:
* make the tasks runnable via `gp <taskanem>`
* Have a menu item in the Theia main menu for each tasks. That would make it much easier for projects to on-board new users.
