### ISSUE TITLE
[ws-manager] maintenance mode

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15409]
## Is your feature request related to a problem? Please describe

We sometimes want to upgrade workspace component images in existing workspace clusters, such as `registry-facade`, `ws-daemon`, and `ws-manager`, but cannot because they are starting workspaces (pulling images, initializing content), stopping (backing content up to object storage) or taking a snapshot (backing up too).

## Describe the behaviour you'd like

1. Persist that maintenance mode is enabled in the `ws-manager` configmap
   * `maintenanceMode` should be persisted as a new object that for now only has an `enabled` field
   * Maintenance mode should only be considered active when enabled is true
2. `ws-manager` must reload the config when maintenanceMode is altered in the configmap
~3. Add two new gRPC endpoints to ws-manager: startMaintenance, stopMaintenance~
   ~* Start sets enabled to true in the configmap~
   ~* Stop sets enabled to false in the configmap~
4. While in maintenance mode, the following gRPC endpoints must fail in a state that is predictable
   * StartWorkspace
   * StopWorkspace
   * TakeSnapshot
5. While in maintenance mode workspace timeouts (which trigger backup) must be delayed until maintenanceMode is disabled

## Describe alternatives you've considered

All other [wsmanager gRPC](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/core.proto) do not require changes and should fail gracefully w/o alternation to be considered for maintenance mode.

## Additional context

Maintenance mode will not be used with gitpod.io. It will be used with Gitpod Dedicated, as a short term solution to do in-place upgrades, as we do not yet have workspace mk2.

## Questions
How will this impact related metrics for workspace start and stop, with and without failures?

**Comment by jenting** [comment]
The gRPC client might need to implement the [circuit breaker pattern](https://martinfowler.com/bliki/CircuitBreaker.html).

**Comment by csweichel** [comment]
@jenting what stops us from implementing this in ws-manager's logic for `startWorkspace`, `stopWorkspace` and `TakeSnapshot` (notice the case)?

**Comment by kylos101** [comment]
@jenting added a related Questions section to the issue. Presently just contains on question about metrics.

**Comment by jenting** [comment]
> @jenting what stops us from implementing this in ws-manager's logic for `startWorkspace`, `stopWorkspace` and `TakeSnapshot` (notice the case), rather than do this on a gRPC level? Also note that we have to not stop workspaces ourselves in that time (e.g. workspace timeout).

@csweichel 
My current idea is implementing the maintenance mode on the gRPC level by leveraging the rate limit setting.
Once the `maintenanceMode.Enabled=true` in the ws-manager ConfigMap, updates/overwrites the rate limit for these three gRPC calls as
```yaml
    "rpcServer": {
        ...
        "ratelimits": {
          "/wsman.WorkspaceManager/StartWorkspace": {
            "block": true,
            "bucketSize": 0,
            "refillInterval": "1ms"
          },
          "/wsman.WorkspaceManager/StopWorkspace": {
            "block": true,
            "bucketSize": 0,
            "refillInterval": "1ms"
          },
          "/wsman.WorkspaceManager/TakeSnapshot": {
            "block": true,
            "bucketSize": 0,
            "refillInterval": "1ms"
          }
        }
      }
```

The client received the error code _ResourceExhausted_ when the maintenance mode enables.

Any comments or suggestions for the ☝️ design?
