### ISSUE TITLE
Worskpace doen't pull container 

### ISSUE THREAD

**Issue by Ludea** [gitpod-io/gitpod#16121]
### Bug description

Hi, 

I try to use vnc container from `gitpod/workspace-full-vnc`

But when restarting workspace, it does not pull image, and start defaut workspace

### Steps to reproduce

create .gitpot.yml:
```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install && cd src-tauri && cargo build --no-default-features
    command: "yarn tauri dev"

ports:
  - name: VNC UI
    port: 6080
    onOpen: open-browser

github:
  prebuilds:
    addCheck: true
```

Create .gitpod.Dockerfile
```
FROM gitpod/workspace-full-vnc
USER root
RUN apt update && \
    apt install -yq build-essential \
        libwebkit2gtk-4.0-dev  \
        build-essential \
        wget \
        libssl-dev \
        libgtk-3-dev \
        libsoup2.4-dev \
        libjavascriptcoregtk-4.0-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev \
        at-spi2-core && \
    npm i -g yarn && \
#    cd /workspace/gitpod-test/crates/test-app && yarn && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ /tmp/* /var/tmp/*
USER gitpod
```

restart workspace

### Workspace affected

ludea-sparus-phz7v1b9pvy

### Expected behavior

pull docker container and connect to webui with VNC

### Example repository

https://github.com/Ludea/Sparus
