### ISSUE TITLE
Support for JupyterLab

### ISSUE THREAD

**Issue by jtpio** [gitpod-io/gitpod#16306]
## Is your feature request related to a problem? Please describe

Currently Gitpod supports a couple of editors and IDEs by default:

![image](https://user-images.githubusercontent.com/591645/217573482-6102c573-32cf-4809-a2a1-c33c397292c0.png)

However these editors are mostly meant for software developers writing code and could be intimidating for other categories of developers.

## Describe the behaviour you'd like

Some Data Scientists might also be interested in using Gitpod for their work.

But they might be more familiar with user interfaces like JupyterLab or Jupyter Notebook.

So it would be great if Gitpod could provide support launching JupyterLab as well.

## Describe alternatives you've considered

With GitHub Codespaces it's possible to set JupyterLab as the default interface:

![image](https://user-images.githubusercontent.com/591645/217575270-bf1b909e-c792-4ea1-b96f-a60cfc709770.png)

Currently on Gitpod it's also possible to install JupyterLab with `pip install jupyterlab` and launch it via a `command` with something like:

```
jupyter lab --no-browser --LabApp.token='' --LabApp.allow_origin=* --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'
```

But this still requires launching VS code and then opening the service (running on port 8888 by default) in another browser tab to access the JupyterLab interface.

**Comment by loujaybee** [comment]
Thanks @jtpio ! This is definitely something that have / are considering. We're also looking into ways to make our IDE interfaces more configurable, so they could be community owned, maintained and suggested more freely.

**Comment by astrojuanlu** [comment]
+1. I'm an instructor that usually works with data scientists and I am looking into ways to use JupyterLab as the default, and later on switch back to VSCode.

Inspired by that JupyterLab itself does (see [their `.gitpod.yml`](https://github.com/jupyterlab/jupyterlab/blob/a920f33/.gitpod.yml)), this is what I'm testing on my projects:

```yaml
tasks:
  ...
  - name: Launch JupyterLab
    init: |
      gp sync-await dependencies
      python -m pip install -r dev-requirements.txt
    # Inspiration: https://github.com/jupyterlab/jupyterlab/blob/a920f33/.gitpod.yml
    # and https://github.com/gitpod-io/gitpod/issues/16306
    command: |
      python -m jupyter lab --port 8888 \
        --LabApp.token='' \
        --LabApp.allow_origin='*' \
        --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}' \
        --no-browser

ports:
  - port: 8888
```

But still usually requires me to explain participants that

- they have to ignore VSCode for a moment,
- they must locate the button "open browser", the ports section, or the active services tab
- they must allow pop-ups from their browser

Not the end of the world, but a bit cumbersome.
