### ISSUE TITLE
cannot set environment variables: invalid request: 500

### ISSUE THREAD

**Issue by ryanpcmcquen** [gitpod-io/gitpod#1663]
`.gitpod.yml`:
```
tasks:
    - init: gp env -e PATH="/usr/local/cargo/bin:$PATH" && eval $(gp env -e) && /workspace/rustlings/install.sh
    - command: eval $(gp env -e) && /workspace/.cargo/bin/rustlings watch
image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
```

`.gitpod.Dockerfile`:
```
FROM rust

ENV export PATH="/usr/local/cargo/bin:$PATH"
```

Repo:
https://github.com/ryanpcmcquen/rustlings/tree/add-gitpod-support
