### ISSUE TITLE
[installer] Allow WorkspaceGarabageCollection to be configured

### ISSUE THREAD

**Issue by charleswhchan** [gitpod-io/gitpod#16980]
## Problem to solve
As a developer,
I want to be able to specify WorkspaceGarbageCollection during installation,
So that I can override optional the default settings to be used for installation

## Proposal
Expose the WorkspaceGarbageCollection from [server/configmap.go](https://github.com/gitpod-io/gitpod/blob/e01ca57b69b8b7d20a9660eb5fc6c03b004e15f1/install/installer/pkg/components/server/configmap.go#L229-L239) in [pkg/config/v1/config.go](https://github.com/gitpod-io/gitpod/blob/e01ca57b69b8b7d20a9660eb5fc6c03b004e15f1/install/installer/pkg/config/v1/config.go#L351-L375) and update [config.md](https://github.com/gitpod-io/gitpod/blob/e01ca57b69b8b7d20a9660eb5fc6c03b004e15f1/install/installer/pkg/config/v1/config.md?plain=1#L64-L74).

This would allow a user to specific the following in gitpod.config.yaml and use the installer to generate the K8s manifest with the appropriate settings.
```
    workspace:
      contentRetentionPeriodDays: 21
      minAgeDays: 14
      minAgePrebuildDays: 7
      prebuildPVC:
      purgeRetentionPeriodDays: 365
```

Note: I am happy to contribute a PR for this
