### ISSUE TITLE
Using MySQL base image produces errors in task terminals

### ISSUE THREAD

**Issue by JuJup** [gitpod-io/gitpod#18491]
### Bug description

When using the `gitpod/workspace-mysql` image, the MySQL Setup produces a couple of errors in each terminal (tested on `latest` and `gitpod/workspace-mysql:2023-02-27-14-39-56`)

```
HISTFILE=/workspace/.gitpod/cmd-1 history -r; {
echo "init test 2"
} && {
echo "command test 2"
}
mysqld: Error on delete of '/workspace/mysql/mysqld_tmp_file_case_insensitive_test.lower-test' (OS errno 2 - No such file or directory)
mysqld: Error on delete of '/workspace/mysql/mysqld_tmp_file_case_insensitive_test.lower-test' (OS errno 2 - No such file or directory)
mysqld will log errors to /var/log/mysql/error.log
2023-08-11T08:35:57.482500Z 0 [ERROR] [MY-011065] [Server] Unable to determine if daemon is running: Invalid argument (rc=0).
2023-08-11T08:35:57.482548Z 0 [ERROR] [MY-010946] [Server] Failed to start mysqld daemon. Check mysqld error log.
```

The errors are not always the same, depending on how fast the terminal starts it might be more or even no error. However, the database is working fine so far, it's just the error outputs.

I suppose this is somehow caused by the [mysql-bashrc-launch.sh](https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-mysql/mysql-bashrc-launch.sh) script, which is executed via .bashrc.

### Steps to reproduce

Creating simple `.gitpod.yml` and do `gp validate` or push and create a new workspace.
Then check the already opened terminals in VS Code.

```
image: gitpod/workspace-mysql

tasks:
  - name: Test 1
    init: echo "init test 1"
    command: echo "command test 1"
  - name: Test 2
    init: echo "init test 2"
    command: echo "command test 2"
  - name: Test 3
    init: echo "init test 3"
    command: echo "command test 3"
  - name: Test 4
    init: echo "init test 4"
    command: echo "command test 4"
  - name: Test 5
    init: echo "init test 5"
    command: echo "command test 5"
```

### Expected behavior

No Error Messages, if there are no Errors.

### Anything else?

After all - is there any reason why I should use this image and not simply start a MySQL Dockercontainer? That way I could even control the Version to be equivalent to my prod Database.
