### ISSUE TITLE
Document generic OAuth integration

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#1866]
Gitpod supports OAuth providers beyond GitHub, GitLab, and bitbucket.org. 

This is an example of the generic mechanism for Azure. It would also work for other OAuth providers. 
This code goes into the Helm's `value.yaml` of your Gitpod installation.

```yaml
gitpod:
  authProviders:
    - id: "OAuth-Service" # must be unique
      type: "OAuth" # type of the generic auth provider
      host: "service.some-provider.com"
      description: "Login with Azure"

      oauth:
        # configuration of the OAuth Provider
        callBackUrl: "https://my-gitpod-domain.com/auth/service.some-provider.com/callback"
        clientId: "<redacted>"
        clientSecret: "<redacted>"
        authorizationUrl: "https://service.some-provider.com/authorize"
        tokenUrl: "https://service.some-provider.com/token "
        scope: "openid offline_access profile email"
        scopeSeparator: " "

        # authorization params that aren't spec'ed goes here:
        authorizationParams:
          # e.g. https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code


        # this profile setup function will be executed in isolated context on each authorization request and should
        # provide current profile information, current scopes, and allows to update
        configFn: |-
          async function(accessToken, tokenResponse) {

              // only the `fetch` function is available to provide the means of reading a user's profile, e.g.
              const userinfo = await (fetch('https://service.some-provider.com/userinfo', { headers: { 'Authorization': 'Bearer ' + accessToken }}).then(res => res.json()));


              const currentScopes = (tokenResponse.scope || "").split(" ");
              const id_token = tokenResponse.id_token;


              return {
                  authUser: {
                    authId: "TODO",
                    authName: "TODO",
                    primaryEmail: userinfo.email,
                    name: "TODO"
                  },
                  envVars: [{
                    name: "SOME_ENV_VAR",
                    repositoryPattern: "*/*",
                    value: "TODO"
                  }],
                  currentScopes
              }
          }
```
