### ISSUE TITLE
Allow port visibility to be configured in .gitpod.yml

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#1867]
I would be convenient to have the `PortVisibility` configurable in `.gitpod.yml` as outlined in the following example:

```yaml
ports:
  - port: 8080-8082
    onOpen: ignore
    visibility: public
```

In web application development, JavaScript code in the browser often needs to call a backend API. If that backend API runs on Gitpod, it needs to be exposed publicly. To achieve that currently, it requires manual clicks to mark each backend API's port as public and to close the dialog.
