### ISSUE TITLE
Self hosted gitpod and gitlab Auth issues

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#1887]
Hi

i've installed gitpod (non-ssl) onto a local box,     and tried to integrate into our local gitlab instance (non-ssl)
when I hit the login button it redirects to gitlab,  accessing for authorisation and then the callback to gitpod occurs,   however gitpod just says 

"Sorry, something went wrong 😓
Please allow Cookies in your browser and try to log in again."

disabled all extension and allowed cookies,  

Server logs show

User started the login process
(GitLab Auth) No session found during auth callback

**Comment by corneliusludmann** [comment]
How does the `values.yaml` file of your helm installation look like? Do you have an `authProviders` section?

**Comment by hm2075** [comment]
Yes,    

attached below

secret key,  id and callback all work fine,   its just on the redirect back that it doesnt seem to be picking up the session
`
 # Gitpod needs at least one auth provider to allow users to log in.
  # The auth providers below are examples only. Please change/remove them to fit your installation.
  authProviders:
  - id: "Local Gitlab"
    host: "aaa.xxx.xxx.xxx"
    protocol: "http"
    type: "GitLab"
    oauth:
      clientId: "id"
      clientSecret: "secretkey"
      callBackUrl: "http://bbb.xxx.xxx.xxx/auth/gitlab/callback"
      settingsUrl: "http://aaa.xxx.xxx.xxx/profile/applications"

`

**Comment by hm2075** [comment]
Attached below

id, secret key works fine as well as the callback,
just looks like its not picking up the session after that

```
# Gitpod needs at least one auth provider to allow users to log in.
  # The auth providers below are examples only. Please change/remove them to fit your installation.
  authProviders:
  - id: "LocalGitlab"
    host: "aaa.xxx.xxx.xxx"
    protocol: "http"
    type: "GitLab"
    oauth:
      clientId: "id"
      clientSecret: "secretkey"
      callBackUrl: "http://bbb.xxx.xxx.xxx/auth/gitlab/callback"
      settingsUrl: "http://aaa.xxx.xxx.xxx/profile/applications"

````
