### ISSUE TITLE
Adding (self-hosted) Gitlab Provider - Sorry, something went wrong 😓 Login not permitted

### ISSUE THREAD

**Issue by philjak** [gitpod-io/gitpod#1906]
### Describe the bug
I spawned gitpod by using the provided [docker-image](https://github.com/gitpod-io/gitpod/tree/master/install/docker/examples/gitpod). When trying to connect to my Gitlab (CE & EE 13.3.5), I get an error.

![image](https://user-images.githubusercontent.com/5772650/94259822-5b634680-ff2f-11ea-9d66-79d1ae071f85.png)

### Steps to reproduce
- Run docker image (with HTTPS)
- Add Git Provider
- Choose "GitLab" and enter hostname of Gitlab Server
- Create Application in Gitlab and use provided callback url (https://`gitpod-host-url`/auth/`gitlab-host-url`/callback) and scopes **api** and **read_user**.
- Enter Gitlab's Application ID as Client ID and Secret as Client Secret.
- Click "Connect" (twice) and get the error message above.

### Expected behavior
I should be able to use my Gitlab's OAuth.

Thanks for your help,
philjak

//Edit: I'm experiencing the same even for Gitlab.com

**Comment by philjak** [comment]
Ok, I have an update.

Two different docs[1](https://www.gitpod.io/docs/self-hosted/latest/install/oauth/)[2](https://www.gitpod.io/docs/gitlab-integration/) say different scopes. If I add "read_repository" as well, I get to my Gitlab installation asking for authorization. Yay!  But after clicking on "Authorize", I get back to my Gitpod installation saying:

"Sorry, something went wrong 😓
Login with "gitlab.com" is not permitted."

![image](https://user-images.githubusercontent.com/5772650/94303215-c16ebe80-ff6d-11ea-8278-239c35420201.png)

Can anyone help with that?

Thanks!

**Comment by wulfthimm** [comment]
Hi,
it seems that the auth-provider credentials are not set properly. Please check your Gitlab authentification. Gitpod needs the permissions for `api` and `read_repository`. The callback url should be `https://<GITPOD_URL>/auth/<GITLAB_URL>/callback`.

**Comment by philjak** [comment]
Dear @wulfthimm 

Thanks for your reply. That's what I set when was entering the details on the `/first-steps` page.

![image](https://user-images.githubusercontent.com/5772650/94427258-10e00500-018f-11eb-8f20-a6ddf6cf778a.png)

Scope as well as callback url are set that way as you mentioned.

**Comment by philjak** [comment]
Quick update: Same issue for github.com. But both, Gitlab.com and Github.com show 1 connected client

![image](https://user-images.githubusercontent.com/5772650/94455251-2404cc00-01b3-11eb-88c2-23f9489120e4.png)

**Comment by corneliusludmann** [comment]
FYI: That happens when you add the provider via the web wizard only. When you add

```
authProviders:
- id: "Public-GitHub"
  host: "github.com"
  type: "GitHub"
  oauth:
    clientId: "CLIENTID"
    clientSecret: "CLIENTSECRET"
    callBackUrl: "https://YOURDOMAIN.COM/auth/github.com/callback"
    settingsUrl: "https://github.com/settings/connections/applications/CLIENTID"
  description: ""
  icon: ""
```

to your `values.yaml` login works as expected.
