### ISSUE TITLE
Is there any way to turn off extension sync when starting a new workspace

### ISSUE THREAD

**Issue by 170210** [gitpod-io/gitpod#19338]
## Is your feature request related to a problem? Please describe

I want to ask whether there is a way to turn off the sync when starting a new workspace.
The official documentation says it can turn off extension sync in ```.gitpod.yml```, but I couldn't find more information about it.
 https://www.gitpod.io/docs/references/ides-and-editors/settings-sync#how-to-disable-extension-sync
I have only found the GUI method after the workspace is created in the official documentation. 

But when I try the following command, it seems to work. However, I cannot find any information about it.
```
vscode:
  extensions:
    - ...
tasks:
  - name: Setup

    init: |

      gp sync-done settings-sync-off
      gp sync-await settings-sync-off
```
Are these codes correct, and will they have any additional effects?
