### ISSUE TITLE
[image-builder] Can't connect to docker daemon (digitalocean)

### ISSUE THREAD

**Issue by wolfymaster** [gitpod-io/gitpod#1942]
# Issue

The image-builder pod seems to not be able to resolve DNS for localhost when trying to connect to docker host in: 
`image-builder run -v --config /config/image-builder.json`

![image](https://user-images.githubusercontent.com/6290908/95036188-22e10c80-0695-11eb-93ce-12733e332e94.png)

# Testing

Exec'ing in the container and running `nslookup localhost` results in `no servers could be reached`

![image](https://user-images.githubusercontent.com/6290908/95036260-5c197c80-0695-11eb-94d9-91f3f542e3d2.png)

Removing the egress portion of the network policy fixed the issue. 

![image-builder-network-policy](https://user-images.githubusercontent.com/6290908/95036969-7d7b6800-0697-11eb-8616-6becbe7c2a7c.gif)

I have no idea why this would fix the issue. I reproduced this test multiple times on digitalocean k8s.

Moreso, I have also installed on Amazon EKS and did not have this issue. image-builder was able to connect just fine. 

This seems to be an issue w/ digitalocean - maybe ? Trying to discover why?! 

# specs
Tested w/ Digital Ocean Managed Kubernetes & Amazon EKS
kubernetes version: DO - 1.18.8 / EKS - 1.17
kubectl version: 1.18.0
nodes: DO - s-4vcpu-8gb  (2) / EKS - m5.large (2)

**Comment by wolfymaster** [comment]
I think I figured this out, after a couple more hours of digging, I found that DigitalOcean ships their Managed Kubernetes with [Cilium](https://cilium.io/). By applying the following, the image-builder pod was able to connect to kube-dns and spin up as expected. 

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-to-kubedns"
spec:
  endpointSelector:
    {}
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: '53'
        protocol: UDP
```
source: https://github.com/cilium/cilium/blob/master/examples/policies/kubernetes/namespace/kubedns-policy.yaml

I have no familiarity with cilium to explain why I was seeing this issue to begin with - I would love to know tho. However, this seems to have resolved the issue. It could be paired down to maybe only select the pod(s) needed. 

Hopefully anyone else who may encounter a similar experience can find this and be saved a dozen hours.
