### ISSUE TITLE
Gitpod app no longer creates Badges or comments

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#19519]
### Bug description

We loved the Gitpod badges on PRs because they helped people to go test things.

But they disappeared at some point. 

Maybe prebuilds are completely gone and aren't run any more? I can't find badges happening on any gitpod-enabled repository. 

### Steps to reproduce

I created 
* https://github.com/ddev/ddev/pull/5945

to demonstrate this.

You can see DDEV's .gitpod.yml at https://github.com/ddev/ddev/blob/master/.gitpod.yml

### Expected behavior

Love those badges!

### Example repository

https://github.com/ddev/ddev

### Anything else?

I see
* https://github.com/gitpod-io/gitpod/issues/3812
* https://github.com/gitpod-io/gitpod/issues/7488

**Comment by TechQuery** [comment]
A third-party GitHub app can help us: https://pullrequestbadge.com/

## `.github/pr-badge.yml` example

```yml
- icon: github
  label: "GitHub codespaces"
  message: "PR-$prNumber"
  color: "black"
  url: "https://codespaces.new/$owner/$repo/pull/$prNumber"

- icon: git
  label: "GitPod.io"
  message: "PR-$prNumber"
  color: "orange"
  url: "https://gitpod.io/?autostart=true#https://github.com/$owner/$repo/pull/$prNumber"
```

## Real world PR example

kaiyuanshe/open-source-articles#367
