### ISSUE TITLE
Changes in $HOME lost after restarting workspace

### ISSUE THREAD

**Issue by Adamtaranto** [gitpod-io/gitpod#19529]
### Bug description

I have been using the Dockerfile below for the last year without issue to create workspaces with miniconda. 

Miniconda is installed into the $HOME (/home/gitpod) dir. Recently changes in this dir such as installed packages or new envs have been failing to persist after restarting the workspace.

Has something changed on your end? 
Should I install miniconda somewhere else now?

### Steps to reproduce

Create new Gitpod workspace using these config files. Create a test env (i.e. conda env create -n testenv). Stop and restart the workspace.

Startup will give error on "jupyter nbextension" commands from .gitpod.yml as packages previously install by ` init: pip3 install -r requirements.txt` are gone. Also `conda env list` will show that testenv is gone.

.gitpod.Dockerfile
```
# Use the Gitpod base image for Python 3.11
FROM gitpod/workspace-python-3.11

# Set user
USER gitpod

# Install Miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p $HOME/miniconda && \
    rm ~/miniconda.sh

# Add Miniconda to PATH
ENV PATH="$HOME/miniconda/bin:$PATH"

# Initialize conda in bash config fiiles:
RUN conda init bash

# Set up Conda channels
RUN conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda config --set channel_priority strict

# Set libmamba as solver
RUN conda config --set solver libmamba

# Remove the undesired default Python location from PATH
RUN export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/home/gitpod/.pyenv/shims' | tr '\n' ':')
```

.gitpod.yml
```
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python packages from requirements.txt
    init: pip3 install -r requirements.txt
    command: |
      jupyter nbextension install --sys-prefix --py nbgrader
      jupyter nbextension enable --sys-prefix --py nbgrader
      jupyter labextension enable nbgrader

vscode:
  extensions:
    - eamodio.gitlens
    - janisdd.vscode-edit-csv
    - mechatroner.rainbow-csv
    - ms-python.python

```

requirements.txt
```
nbgrader==0.8.5
numpy
pandas
seaborn
matplotlib
pysam
biopython
regex
scipy
```

### Workspace affected

melbournebi-comp9001620-96dowtuzt7i

### Expected behavior

New envs and installed packages in $HOME should persist after restarting a stopped workspace.

### Anything else?

This seems to have become an issue some time after November last year.
