### ISSUE TITLE
Cannot do anything as superuser in custom image

### ISSUE THREAD

**Issue by nothingneko** [gitpod-io/gitpod#20046]
### Bug description

I cannot use superuser in my Ultramarine 40 docker image, there is no option in the gitpod.yml to define a user

Error output in terminal
![Screenshot 2024-07-17 at 11 34 25 PM](https://github.com/user-attachments/assets/1a9b9965-99c0-4a27-9fba-e8d59957d939)

gitpod.yml
```yaml
image: ghcr.io/ultramarine-linux/ultramarine:40

tasks:
  - name: Setup Environment
    before: useradd -G wheel gitpod
    init: sudo dnf install katsu submarine vboot-utils
```

### Steps to reproduce

Attempt to validate my gitpod.yaml

### Expected behavior

Already a superuser, or the ability to elevate

### Example repository

https://github.com/nothingneko/gitpod-bug

### Anything else?

This could potentially be an issue with our docker images, our sources are here https://github.com/ultramarine-linux/images
