### ISSUE TITLE
cannot initialize workspace: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#2014]
### Describe the bug

Workspace cannot initialize due to Custom CA certifiate used by Gitlab. It fails to launch with this error
```
cannot initialize workspace: cannot initialize workspace: cannot initialize workspace: git initializer: git clone https://gitlab.devlnk.net/john.gallucci/bisf-cli.git . failed (exit status 128): Cloning into '.'... fatal: unable to access 'https://gitlab.devlnk.net/john.gallucci/bisf-cli.git/': SSL certificate problem: unable to get local issuer certificate
```

### Steps to reproduce

1. Deploy Gitpod into Kubernetes
2. Integrate with Gitlab which uses an HTTPS with a Custom CA certificate
3. Launch Workspace

### Expected behavior

Workspace launches

### Additional information

Red Hat 7.8 (Docker CE 19.03)
Kubernetes 17.5.1
Gitpod Self-hosted v0.4.0

![image](https://user-images.githubusercontent.com/9018897/96323672-06b56780-0fd3-11eb-9602-4b9ff78c28e9.png)

### Example repository

n/a

**Comment by jgallucci32** [comment]
I was successfully able to workaround this issue by doing the following:

1. Create Kubernetes secret `gitpod-ca-root` with trusted root CA certificates:
```
cd /path/to/custom/ca/bundle
kubectl -n gitpod-selfhosted create secret generic gitpod-ca-root --from-file=ca-bundle.crt
```
2. Manually add the `volume:` and `volumeMounts:` parameters to the `ws-sync.yaml` deployment file to overwrite the trusted certificate authorities:
```
#   spec:
#     containers:
#       volumeMounts:
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: gitpod-ca-root
          subPath: ca-bundle.crt
#     volumes:
      - name: gitpod-ca-root
        secret:
          defaultMode: 420
          secretName: gitpod-ca-root
```
4. Redeploy `ws-sync` pod
