### ISSUE TITLE
Extensions keep reinstalling every time I load VS Code Desktop

### ISSUE THREAD

**Issue by alessandro-newzoo** [gitpod-io/gitpod#20262]
### Bug description

There are several extensions that, for some reason, get reinstalled every single time I create/open a Gitpod workspace.
The extensions are not in my VS Code profile. I think they are extensions I have installed (and removed) a long time ago, probably when I was trialling Gitpod (and then decided to ditch it for this exact problem, which I forgot about until I tried it again today).

This is incredibly annoying and it's making it impossible for my team to use Gitpod.

### Steps to reproduce

- Open VS Code
- Notice how the extension `vscode-twigcs` is **not** installed:
![CleanShotX - Code  02 10 2024 at 13-51-36 @2x](https://github.com/user-attachments/assets/99d9facd-75da-4b6d-b4e5-6ad6d7f1080a)
- Command pallette → `Settings Sync: Sync now`
- Create a Gitpod workspace that opens in VS Code Desktop
- Notice how `vscode-twigcs` is now installed in the new workspace (why??):
![CleanShotX - Code  02 10 2024 at 13-53-37 @2x](https://github.com/user-attachments/assets/e522f6a9-7c0a-4b7e-bf37-a9a338b477fb)
- Uninstall the extension while the workspace is open
- Reload the VS Code window
- The extension has been reinstalled again 😩

The same thing happens if I close the workspace, uninstall the extension, and create a new workspace.
The same thing happens with many other extensions, and it's driving me insane.
The extensions in question are **not** in my .gitpod.yml

```yaml
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mrmlnc.vscode-apache
    - ihatetomatoes.gsap3-snippets
    - donjayamanne.jquerysnippets
    - usernamehw.commands
    - vunguyentuan.vscode-css-variables
    - mrmlnc.vscode-less
    - bmewburn.vscode-intelephense-client
    - vunguyentuan.vscode-postcss
    - aswinkumar863.smarty-template-support
    - bradlc.vscode-tailwindcss
    - jdcreations.timber-snippets
    - mrmlnc.vscode-duplicate
    - gruntfuggly.todo-tree
    - xdebug.php-debug
``` 

How do I prevent this? Where is Gitpod getting this list of extensions from?

Thank you.

### Anything else?

VS Code `1.93.1` on macOS
