### ISSUE TITLE
Error: build failed: cannot check base image exists

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#2049]
### Describe the bug

When using a Dockerfile in your .gitpod.yml configuration while Gitpod is configured for an external Docker registry the following error appears:
```
Error: build failed: rpc error: code = Internal desc = cannot check base image exists: Error response from daemon: errors: denied: requested access to the resource is denied unauthorized: authentication required
```
This issue occurs if the custom Docker registry does not have the repositories `workspace-images` and `base-images` created prior. This was tested against Docker Trusted Registry specifically.

### Steps to reproduce

1. Deploy Gitpod self-hosted and configure for external Docker registry as follows:
```yaml
  components:
    imageBuilder:
      registryCerts: []
      registry:
        name: registry.domain.local/gitpod
        secretName: external-registry-auth
```
2. Launch Gitpod workspace

### Expected behavior

Workspace is expected to build the image and launch the workspace.

### Additional information

Red Hat Enterprise Linux 7.8
Docker CE 19.03.13
Gitpod 0.5.0

### Fix
Create the `workspace-images` and `base-images` repositories in Docker Trusted Registry

### Recommendation
Add this to the documentation as a dependency for external registries.
