### ISSUE TITLE
Unable to create workspace : https://github.com/DevFactory/mf-trilogy-group-avolin-tradebeam-gtm

### ISSUE THREAD

**Issue by ganapathy-df** [gitpod-io/gitpod#2055]
While trying to create a workspace getting the following error

Sorry, something went wrong 😓
Error: Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Head https://060260394319.dkr.ecr.us-east-1.amazonaws.com/v2/workspace-images/manifests/835c95423ec4d3254bb7fa41910686e75630a97a4b74f8cc9accb9d01a8d4841: no basic auth credentials
Please file an issue if you think this is a bug.

Repo : https://github.com/DevFactory/mf-trilogy-group-avolin-tradebeam-gtm

**Comment by corneliusludmann** [comment]
Hi @ganapathy-df,

I get a 404 for the repo URL. Is it a private repo?

**Comment by corneliusludmann** [comment]
Closing this due to inactivity. Please reopen if you have additional information to share.

**Comment by enriquecaballero** [comment]
@corneliusludmann Any chance we can reopen this ticket? I'm running into this same situation. I'm using an external registry, and set up a registry secret to which I think I added successfully to my values.yaml as all my pods are running. However when I try to create a workspace, I get:

**Error: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Head https://r.gitpod.caballero.dev/v2/workspace-images/manifests/e16311ce7fb6ebb309b0fa988b6bc08e1ca3923aa8205fac86d3a3be138fda7c: no basic auth credentials**

Registry is whitelisted to my internal network (it was the easiest way to get https to work).

**Comment by enriquecaballero** [comment]
My `values.yaml` file looks like this:

```yaml
components:
  wsDaemon:
    containerRuntime:
      containerd:
        socket: /run/k3s/containerd/containerd.sock
      enabled: true
      nodeRoots:
        - /var/lib
        - /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
    registry:
      baseImageName: ''
      bypassProxy: false
      name: r.gitpod.caballero.dev
      path: ''
      secretName: image-builder-registry-secret
      workspaceImageName: ''
  server:
    pullSecret:
      secretName: image-builder-registry-secret
    spec:
        imagePullSecrets:
          - name: image-builder-registry-secret
```

`image-builder-registry-secret` is a docker-registry secret containing both username and password
