### ISSUE TITLE
Intellij Plugins Not Working

### ISSUE THREAD

**Issue by lwoerdeman** [gitpod-io/gitpod#20807]
### Bug description

Plugins configured for Gitpod are no longer being installed in my IDE after migration from Classic to Flex.

Plugins specified according to format found in IntelliJ documentation
https://www.jetbrains.com/help/idea/customizing-devcontainer-json-file.html#add_plugins

### Steps to reproduce

Here's the relevant section of my gitpod.yaml file on classic
```yml
jetbrains:
  intellij:
    plugins:
      - org.intellij.plugins.hcl
      - com.gitlab.plugin
      - com.intellij.mermaid
      - Pythonid
      - PythonCore
      - com.thoughtworks.gauge
```

Here's my configuration in the `devcontainer.json` for flex
```json
{
    "customizations": {
        "jetbrains": {
            "plugins": [
                 "org.intellij.plugins.hcl",
                 "com.gitlab.plugin",
                 "com.intellij.mermaid",
                 "Pythonid",
                 "PythonCore",
                 "com.thoughtworks.gauge"
             ]
        }
    }
}
```

### Expected behavior

Would expect to see plugins listed in customizations section installed.
