### ISSUE TITLE
Self Hosted Kubernetes Nodes go "Not Ready" – Port conflict with kubespray / wsDaemon 8081

### ISSUE THREAD

**Issue by stefanstoeckigt** [gitpod-io/gitpod#2180]
### Describe the bug
When using gitpod with certificates enabled in a selfhosted kubernetes cluster, the kubernetes node fluctuate between Ready and Not Ready. All Gitpod deployment succeed, however after about 1 minute of pod uptime the nodes in the cluster start to fluctuated between Ready and Not Ready. 
Note: This bug only occurs when certificates are enabled ("certificatesSecret"). 

This could indicated that there is a networking conflict between the gitpod docker deployments (Docker in Docker) and the kubernetes management networking. 
My kubernetes api server port is 6443 over https, which is setup via kubespray. 

### Steps to reproduce
- Kubernetes Cluster deployed with [Kubespray ](https://github.com/kubernetes-sigs/kubespray) (calico networking).
- Gitpod Helm Values:
```yaml
# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

version: 0.5.0
imagePrefix: eu.gcr.io/gitpod-io/self-hosted/

# This field must be set to your domain name. Leaving it set to its default value will result in
# a non-functional installation.
hostname: {{ gitpod_hostname }}

# If you have a static IP that your domain resolves to, set it here.
# Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
# during deployment.

components:
  proxy:
    loadBalancerIP: {{ gitpod_proxy_loadbalancer_ip }}

# Gitpod needs at least one auth provider to allow users to log in.
# The auth providers below are examples only. Please change/remove them to fit your installation.
authProviders:
- id: "{{ gitpod_authProviders_gitlab_id }}"
  host: "{{ gitpod_authProviders_gitlab_host }}"
  type: "GitLab"
  oauth:
    clientId: "{{ gitpod_authProviders_gitlab_oauth_client_id }}"
    clientSecret: "{{ gitpod_authProviders_gitlab_oauth_client_secret }}"
    callBackUrl: "https://{{ gitpod_hostname }}/auth/gitlab/callback"
    settingsUrl: "https://{{ gitpod_authProviders_gitlab_host }}/profile/applications"

# RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
# we do not attempt to install PodSecurityPolicies and the likes.
installPodSecurityPolicies: true

certificatesSecret:
  secretName: proxy-config-certificates
```

### Expected behavior
The kubernetes nodes shouldn't go "Not Ready" due to a cluster deployment.

**Comment by stefanstoeckigt** [comment]
Any help would be appreciated.

**Comment by meysholdt** [comment]
hi @stefanstoeckigt! 

From reading your report I can't quite tell what went wrong. 

Do you find find something in the logs that indicated what caused the status changes of your nodes?
What's the output of `kubectl describe node <nodename>` for a non-ready node?
Can you post the logs of gitpod's pod `image-builder`?

**Comment by stefanstoeckigt** [comment]
This issue doesn't occur with helm chart version 0.6.0-beta1.

**Comment by stefanstoeckigt** [comment]
![image](https://user-images.githubusercontent.com/1832236/103917627-b9deba00-5105-11eb-9d23-0746c8fc5fee.png)

No useful information on the nodes to why they went down. This issues only occurs when the ws-deamon are deployed on all the nodes. 
This issues still persists with gitpod 0.6.0-beta.

**Comment by DomHoney** [comment]
I've got a little more information, not sure how useful.

Lots and lots of errors in the kubelet logs saying connection refused, all seem to be complaining about connecting to the API server:
`Error updating node status, will retry: error getting node "garblak8swkr01": Get https://localhost:6443/api/v1/nodes/garblak8swkr01?timeout=10s: dial tcp 127.0.0.1:6443: connect: connection refused`

I'm guessing kube-proxy makes the requests to the API server for the kubelets.

Also at the same time this was happening, our nginx-proxy health probes failed due to 'connection refused' errors. The container logs showed nginx being killed with sigterm, I'm guessing thats the liveness probe?
The nginx-proxy pod ended up being killed and restarted after the gitpod deployment had torn down.

Will hopefully be able to post some more useful info tomorrow.

**Comment by stefanstoeckigt** [comment]
@meysholdt, i have found the causes of this issues. 

So in the [kubespray ](https://github.com/kubernetes-sigs/kubespray) deployment of kuberentes, the following config is applied by default:
```yaml
loadbalancer_apiserver_healthcheck_port: 8081
```

This is causing a conflict with:
```yaml
components:
  wsDaemon:
    registryProxyPort: 8081
```

If you look at the kubelets logs on the node, you can see the affect of the wsDaemon deployment. 

```
21:05:38 garblak8swkr01 kubelet[1900]: I0109 21:05:38.075988    1900 prober.go:116] Readiness probe for "nginx-proxy-garblak8swkr01_kube-system(4c9318535ee7020d4f4ca0f12c36049a):nginx-proxy" failed (failure): Get http://10.26.105.12:8081/healthz: dial tcp 10.26.105.12:8081: connect: connection refused
21:06:01 garblak8swkr01 kubelet[1900]: I0109 21:06:01.140806    1900 kuberuntime_manager.go:612] Container "nginx-proxy" ({"docker" "8491d921877a8e308472a4acf2cfb1b7132c37f76b8010cfc47d1db59d602411"}) of pod nginx-proxy-garblak8swkr01_kube-system(4c9318535ee7020d4f4ca0f12c36049a): Container nginx-proxy failed liveness probe, will be restarted
21:06:01 garblak8swkr01 kubelet[1900]: I0109 21:06:01.140869    1900 kuberuntime_container.go:586] Killing container "docker://8491d921877a8e308472a4acf2cfb1b7132c37f76b8010cfc47d1db59d602411" with 30 second grace period
```

Changing the ``` registryProxyPort``` to 8082 fixes the issue. 
However its alarming that there is a port conflict like this!
