### ISSUE TITLE
presist signals fired via gp sync{await, done} so they survive workspace restarts

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2186]
I was recently Gitpodifying https://github.com/niklasvh/html2canvas and below is how my config looked like:

```yml
tasks:
  - name: Build
    init: npm install && npm run build && gp sync-done boot

  - name: Website
    before: cd www/
    init: npm install
    command: gp sync-await boot && npm start
    openMode: split-right

ports:
  - port: 8000
    onOpen: open-preview

```

The same config worked without the pre-builds while with the pre-builds it seemed to be stuck as if the `npm start` thing did not work. The behaviour was kind of odd and I had no idea What I was doing wrong.

### Without Pre-build

![image](https://user-images.githubusercontent.com/46004116/99147968-c9fa9000-26a6-11eb-9efa-d6ab26245c03.png)

### With Pre-build

![image](https://user-images.githubusercontent.com/46004116/99147976-d979d900-26a6-11eb-8112-cb6e5fc32ad3.png)

Thanks to @svenefftinge who pointed out:

> the init tasks are not executed during startup of a prebuilt workspace. Therefore the `gp sync-done boot` command is never executed and as a consequence the other terminal is waiting forever.

moving the `gp sync-done boot` to the `command` section instead of `init` made it work as expected.

As a user looking at https://www.gitpod.io/docs/config-start-tasks/ I was expecting `gp sync-done boot` to work in the `init` phase. Sven proposed:

> Maybe we should persist signals fired on disk so they survive workspace restarts.

I agree with him as the current behaviour unless we clearly document it is alienating.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3tgju)
