### ISSUE TITLE
Github and Gitlab OAuth flows resulting in session/cookie error

### ISSUE THREAD

**Issue by boledzp** [gitpod-io/gitpod#2228]
Hi,  

I've been trying to install self-hosted on GCP via the automated installer.  Helm package installation appears to be completed successfully, but I'm a receiving an error one being returned from both oAuth providers: 

"Sorry, something went wrong 😓
Please allow Cookies in your browser and try to log in again."

Also seeing 'no session' errors in the GCP error reporting:
`(GitHub Auth) No session found during auth callback.`
`(GitLab Auth) No session found during auth callback.`

OAuth return URL as follows within GCP error logging as follows:
`url: /auth/github/callback?code=0353d4bc6ea321852a2a`

I believe I've checked for issues in the values.yaml, but have included a version here in case.

```
gitpod:
  # This field must be set to your domain name. Leaving it set to its default value will result in
  # a non-functional installation.
  hostname: gitpod.<TLD>

  branding:
    homepage: https://gitpod.<TLD>
    redirectUrlIfNotAuthenticated: /workspaces/ # value of `homepage` is default
    redirectUrlAfterLogout: https://gitpod.<TLD>

  # If you have a static IP that your domain resolves to, set it here.
  # Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
  # during deployment.
  components:
    proxy:
      loadBalancerIP: <IP>

  # Gitpod needs at least one auth provider to allow users to log in.
  # The auth providers below are examples only. Please change/remove them to fit your installation.
  authProviders:
  - id: "Example Github"
    host: "github.com"
    protocol: "https"
    type: "GitHub"
    oauth:
      clientId: "<CID>"
      clientSecret: "<CS>"
      callBackUrl: "https://gitpod.<TLD>/auth/github/callback"
      settingsUrl: "https://github.com/settings/connections/applications/<CID>"
  - id: "Example Gitlab"
    host: "gitlab.com"
    protocol: "https"
    type: "GitLab"
    oauth:
      clientId: "<CID>"
      clientSecret: "<CS>"
      callBackUrl: "https://gitpod.<TLD>/auth/gitlab/callback"
      settingsUrl: "gitlab.com/profile/applications"


  # RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
  # we do not attempt to install PodSecurityPolicies and the likes.
  installPodSecurityPolicies: true
```
