### ISSUE TITLE
Gitpod API missing

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#2241]
While working on [Gitpod-AWS](https://github.com/JesterOrNot/Gitpod-AWS) I almost made a functioning automated install however on trying to login I get the following error

![image](https://user-images.githubusercontent.com/50386709/80729928-89527500-8ace-11ea-943d-c4cdc7e9ac40.png)

Note the following things have been missing from the install

* A real domain with wildcards (although I have tried to get the DNS with gcp to work I have been unable and have had to do some hacky things to make it work)
* The image builder service seems broken
![image](https://user-images.githubusercontent.com/50386709/80730286-01b93600-8acf-11ea-994b-44f212b5a163.png)

Current configuration
```yaml
gitpod:
  hostname: adb8cda76790e47cb99317fabdfe3661-43330277.us-east-2.elb.amazonaws.com
  components:
    proxy:
      loadBalancerIP: null
  authProviders:
  - id: "Github"
    host: "github.com"
    protocol: "http"
    type: "GitHub"
    oauth:
      clientId: "a0d9f23f71a890a581e8"
      clientSecret: "SECRET"
      callBackUrl: "http://adb8cda76790e47cb99317fabdfe3661-43330277.us-east-2.elb.amazonaws.com/auth/github/callback"
      settingsUrl: "https://github.com/settings/connections/applications/a0d9f23f71a890a581e8"
  installPodSecurityPolicies: true

docker-registry:
  enabled: true

gitpod_selfhosted:
  variants:
    customRegistry: false
```
