### ISSUE TITLE
onOpen: open-browser doesn't work

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2432]
### Describe the bug
I have a service that listens on a port. I added the port to gitpod.yml, with `onOpen: open-browser` set. No browser tab is opened, and the popup now doesn't show either.

My config:

```yaml
# 1234 is my service.
ports:
  - port: 1234
    onOpen: open-browser
  - port: 2345
    onOpen: ignore
  - port: 3456
    onOpen: ignore
  - port: 4567
    onOpen: ignore
```

I see the port listed as `open (public)` in the "Open Ports" console. Clicking "Open Browser" from the Open Ports console works.

### Steps to reproduce
Add something similar to your .gitpod.yml file. Start a service on it. A new browser window should open.

### Expected behavior
A browser tab should open.
