### ISSUE TITLE
suppress exposing some ports

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#245]
During Node.js debugging I see notifications to expose ports, it gets annoying. It would be nice if it is possible to mark some ports like not exposable and suppress new notifications.

**Comment by HorizonShadow** [comment]
Is it possible to do that globally?

using meteor, you end up with this:

![image](https://user-images.githubusercontent.com/1729810/55794543-e2063880-5a9b-11e9-8e97-426d0280c236.png)

Uses a new port every time the hot-reloader runs.

**Comment by jankeromnes** [comment]
@HorizonShadow Oof, that's a lot of ports!

If you know these ports in advance, you can silence the pop-ups with something like this in your `.gitpod.yml`:

```yaml
ports:
  - port: 3001
    onOpen: ignore
  - port: 29851
    onOpen: ignore
  - port: 28593
    onOpen: ignore
  - port: 21581
    onOpen: ignore
```

**Comment by meysholdt** [comment]
I was also made aware of a project where programs open many ports, leading to several popup messages in Gitpod:

![image](https://user-images.githubusercontent.com/239422/56113587-97366600-5f5e-11e9-93b8-298e0b615969.png)

I thought we could have something like.
```yaml
ports:
  - port: 20000
    onOpen: open-preview
  - ignoreAllOtherPorts: true
```

or even better, define the semantics of @jankeromnes suggestion to be like this:

```yaml
ports:
  - port: 20000
    onOpen: open-preview
  - port: 1000-30000
    onOpen: ignore
```

This would ignore ports `1000-30000`, except the ones that have been explicitly opened (`20000`).

**Comment by jankeromnes** [comment]
Another idea could be to throttle the Gitpod port pop-ups, only opening the first 2 or 3, and then say something like "There are 12 other ports with activity [View active ports] [Ignore all unspecified ports]"?

**Comment by AlexTugarev** [comment]
In addition to that, I propose to introduce a user setting for ignoring port notifications.

**Comment by meysholdt** [comment]
Some people want to use Gitpod to demo their code:
* the person that prepares the demo has deep knowledge about `.gitpod.yaml`
* the person that views the demo should *not have a single false-positive popup*.

**Comment by akosyakov** [comment]
I have same issues with node debugging on random ports. I cannot specify which port can be ignored, one notification is not so annoying, but still distracting.

**Comment by meysholdt** [comment]
Yesterday in a call I was asked: "How can I open a new Terminal in Gitpod"? It turned out the menu item for it was hidden all the time behind "expose port" popups.

**Comment by svenefftinge** [comment]
Lot's of good suggestions! 
I like the simplicty of `ignoreAllOtherPorts` but would like to make it fit better with the existing concepts by allowing ranges and a wildcard `*` in addition to the port numbers.

Example:
```yaml
ports:
 - port: 3000
   onOpen: open-preview
 - port: *
   onOpen: ignore
```

One could argue that the current default is.
```yaml
ports:
 - port: *
   onOpen: notify
```

I also think https://github.com/gitpod-io/gitpod/issues/493 would improve the UX a lot.

Improving notifications generally makes a lot of sense, too. We should generalize that in Theia.

**Comment by pattacini** [comment]
I would really love to have the possibility to mask notifications for port ranges or even better for all those ports in `.gitpod.yml` that I don't specifically mark as to-be-notified.

When I start my application in Gitpod, the IDE is literally flooded with tons of notifications.

**Comment by svenefftinge** [comment]
We should maybe add `onOpen: ignore-no-expose` to allow non auto-exposing for ranges.

**Comment by jankeromnes** [comment]
I'd like to implement port ranges like so (implicit priority: "single port" > "specific port ranges" > "*"):

```yaml
ports:
- port: 3000
  onOpen: open-preview
- port: 3001-4000
  onOpen: notify
- port: *
  onOpen: ignore
```

However, my concern is that until now, _every_ port listed in `ports:` gets exposed in the workspace (whether `onOpen:` is `open-browser`, `open-preview`, `notify` or `ignore`).

But when you do:

```yaml
- port: *
  onOpen: ignore
```

I guess your intent is _not_ to suddenly expose all the ports of your workspace, but just to silence the notifications.

Thus, I would like to:
- rename `ignore` to `expose` (same behavior: expose the port silently and do nothing else)
- add a new action that is both silent _and_ doesn't expose the port, called something like `block` or `ignore-no-expose` as suggested above

We could keep backwards compatibility by continuing to allow `ignore` as a synonym for `expose`.

**Comment by jankeromnes** [comment]
Actually (after many design iterations) I think that the following behavior would be best to silence noisy port notifications, without unintended side-effects, nor over-complicated configurations:

- Port ranges in `.gitpod.yml` don't pre-expose ports
- When a port from a range becomes active **and** the IDE opens it, it gets automatically exposed first
- (no change to the existing `onOpen` actions)

Current behavior (to illustrate):

```yaml
ports:
- port: 3000 # exposed
- port: 3001
  onOpen: open-preview # exposed
- port: 3002
  onOpen: notify # exposed
- port: 3003
  onOpen: ignore # exposed
```

New with port ranges:

```yaml
ports:
- port: 4000-4999 # (same as notify)
- port: 5000-5999
  onOpen: open-preview # not exposed (but a port that triggers a preview will get exposed first)
- port: 6000-6999
  onOpen: notify # not exposed (but clicking on "Open Preview" or "Open Browser" will expose that port)
- port: *
  onOpen: ignore # not exposed (if you really want to expose a port here, either configure it specifically, or manually expose from the Ports view)
```

**Comment by svenefftinge** [comment]
I often use `ignore` and need that port being exposed. This is always the case for any API endpoints.

Would be good to auto-expose on `ignore`, `open-browser`, `open-preview`. 
But not on `notify` (default) and a new `ignore-no-expose`.

The notify will open up a notification allowing to `open in browser` or `open in preview` which will auto-expose.

**Comment by meysholdt** [comment]
Hi @jankeromnes, thank you for your proposal! 

I also think (like @svenefftinge) that we should support the use-case of exposing ports without raising notifications for them.

Besides this, I think I understand how @svenefftinge and you arrive at different approaches. @svenefftinge's design has two assumptions:
1) listing a port in `.gitpod.yml` means it is exposed.
2) `onOpen` is only about the action that's triggered when an app starts listening on that port, not exposure. 

If a user is not aware of these two assumptions he/she is very like to misunderstand the semantic's of `ignore`: He/she may think the port is ignored by Gitpod: not exposed, no notification.

**Comment by jankeromnes** [comment]
Thank you for the quick feedback on my proposal!

I agree with:
- making `Open Browser` and `Open Preview` actions expose the port on-the-fly if necessary
- changing `onOpen: notify` to **not** pre-expose the port

> I often use `ignore` and need that port being exposed. This is always the case for any API endpoints.

My gut feeling here is that you'll _never_ want to use public Gitpod URLs like `https://31457-abcd.ws-eu.gitpod.io` when using port ranges.

I think that you'll either have:
1. A single API port (or just a few), that you can list individually in `.gitpod.yml`
2. Too many API ports, that you'll be able to list as a port range like `- port: 30000-40000`, but that you won't ever use public Gitpod URLs for (e.g. unexposed `localhost:31457` access server-side will be enough)

Because of 1. and 2., I'm suggesting to continue pre-exposing single ports (e.g. `- port: 8081`, regardless of `onOpen`) but to **not** pre-expose port ranges (e.g. `- port: 30000-40000`). Do you think that's reasonable?

Another way to put my question is, what do you think should happen when users do:

```yaml
- port: *
  onOpen: ignore
```

?

**Comment by jankeromnes** [comment]
(Side-note, we can't use the syntax `- port: *`, as our parser thinks `*` is an empty [YAML alias](https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)). Instead, it should be `- port: "*"`, or just `- default:`.)

**Comment by jankeromnes** [comment]
Update: I'm currently implementing something like this:

```yaml
ports:
  - port: 3000-3999
    onOpen: ignore
```

**The Good:** By default, this will have the desired effect of silencing the notifications of all ports in the specified range (because of `onOpen: ignore`).

**The Bad:** This will also have the unfortunate side-effect of automatically exposing all active ports in that range (i.e. just like automatically clicking "Expose" on all these notifications, regardless of `onOpen`).

In the interest of time, I'll ship this version first, and follow up with improvements later. (Also, I don't like the name `ignore-no-expose`, but if that's the preferred way to silence notifications _without_ exposing all ports, I'll implement it.)

**Comment by pattacini** [comment]
Thank you @jankeromnes for being on this.
Having `ignore-no-expose` (or any equivalent tag) available would be great in my setting.

**Comment by jankeromnes** [comment]
Update: Port ranges are now implemented and should be deployed very soon (today). 🎉 

Additionally, contrary to the previous update, port ranges with `onOpen: ignore` will _not_ be automatically exposed for now (i.e. for port ranges, `ignore` currently behaves like a `ignore-no-expose` would):

```yaml
ports:
  - port: 2000-2999
    onOpen: open-preview # auto-exposed
  - port: 3000-3999
    onOpen: ignore # NOT auto-exposed
```

This is slightly inconsistent with individual ports, in order to preserve backward-compatibility:

```yaml
ports:
  - port: 4000
    onOpen: open-preview # auto-exposed
  - port: 5000
    onOpen: ignore # also auto-exposed
```

I also think that it makes sense that way:
- If you have a single ignored port, it might be a backend that you'd like to access via a Gitpod preview URL like `https://5000-abcd.ws-eu.gitpod.io`
- But if it's an entire port range that's ignored, you're probably not going to bother with preview URLs (i.e. you just want to silence them, or you just want to use `localhost:<dynamic port>` server-side). And even if you _really_ want a preview URL, you can always manually expose ports from the `Open Ports` view, or set the range's `onOpen` to something different than `ignore`.

Note that this is very easy to tweak further in the future. Please let me know if you'd like the auto-exposing behavior to be changed.
