### ISSUE TITLE
Add ESLint support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#251]
We should add the plug-in for TS 
https://github.com/typescript-eslint/typescript-eslint

cc @akosyakov

**Comment by svenefftinge** [comment]
Users can install the ESLint extension for VS Code.

**Comment by brunogcpinheiro** [comment]
@svenefftinge Did you find a solution?

**Comment by jankeromnes** [comment]
Hi @brunogcpinheiro, simply install `eslint` or `typescript-eslint` as usual (e.g. `npm install -g eslint`), and then add this to your `.gitpod.yml` file in order to automatically install the VS Code extension:

```yml
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.0.15:/v3eRFwBI38JLZJv5ExY5g==
```
