### ISSUE TITLE
Configurable URL for `open-browser` action

### ISSUE THREAD

**Issue by AdrianoKF** [gitpod-io/gitpod#252]
As described on [Spectrum](https://spectrum.chat/gitpod/general/further-configuration-for-open-browser-for-ports~139e2ead-7359-41ca-bb3b-0b82b58e20c4), it would be nice to be able to specify a URI to be used as part of the ports configuration, so the `open-browser` action automatically accesses the correct location. This is useful if the application listening on the port does not allow configuring the root URI / to redirect.

I could imagine adding a `previewURI` option or similar to the `ports` section in .gitpod.yml:
```
ports:
- port: 8080
  onOpen: open-browser
  previewURI: /web/helloworld.html
```

**Comment by svenefftinge** [comment]
A workaround until this is directly support is to `ignore` the port event and run the `gp preview` command on start.
Example:
```yml
ports:
- port: 8080
  onOpen: ignore
tasks:
- command: gp preview $(gp url 8080)web/helloworld.html
```
