### ISSUE TITLE
VSCode Feature Preview doesn't install extensions in .gitpod.yml

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2530]
### Describe the bug

I just enabled the vscode editor feature preview, and my extensions don't get installed.

Here's the extensions portion of my .gitpod.yml file

```yaml
vscode:
  extensions:
    - zxh404.vscode-proto3@0.4.2:ZnPmyF/Pb8AIWeCqc83gPw==
    - mhutchie.git-graph@1.26.0:m8EvA1owa1dL2R6+Swieyg==
```

Then I go to the extensions tab, and search mhutchie.git-graph, and I can still install it. No extensions are installed by default.

### Steps to reproduce

Enable Feature Preview, switch editor from theia to vscode, open a workspace from a repo with vscode extensions set in .gitpod.yml, and look at the extensions tab.

### Expected behavior

Extensions should be installed.
