### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in gitpod/workspace-mysql

### ISSUE THREAD

**Issue by christiansiewert** [gitpod-io/gitpod#2533]
Hi,

unfortunately we can't connect to our MySQL server when initializing our workspace and using `gitpod/workspace-mysql` docker image.

We have this in our `.gitpod.Dockerfile`:

```bash
FROM gitpod/workspace-mysql

USER gitpod

# Install php-dev
RUN sudo apt-get update -q \
    && sudo apt-get install -y php-dev

# Build and install Xdebug
RUN wget http://xdebug.org/files/xdebug-2.9.1.tgz \
    && tar -xvzf xdebug-2.9.1.tgz \
    && cd xdebug-2.9.1 \
    && phpize \
    && ./configure \
    && make \
    && sudo mkdir -p /usr/lib/php/20190902 \
    && sudo cp modules/xdebug.so /usr/lib/php/20190902 \
    && sudo bash -c "echo -e '\nzend_extension = /usr/lib/php/20190902/xdebug.so\n[XDebug]\nxdebug.remote_enable = 1\nxdebug.remote_autostart = 1\n' >> /etc/php/7.4/cli/php.ini"

# Export environment variables
ENV DATABASE_USER=root
ENV DATABASE_HOST=127.0.0.1
ENV DATABASE_PASSWORD=
```

Our `gitpod.yml`

```yaml
image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - init: ./setup.sh
    - before: wget https://get.symfony.com/cli/installer -O - | bash  
      command: export PATH="$HOME/.symfony/bin:$PATH" && symfony server:start
```

In `setup.sh` we are trying to install our databases:

```bash
#!/bin/bash

# Install databases
mysql -e 'CREATE DATABASE app;'
mysql -e 'CREATE DATABASE app_test;'

# Install Composer dependencies
composer install
```

When the node is trying to install our databases we get an error in the terminal output:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

If we are running the above commands after initialization is finished, everything works as it should:

```bash
gitpod /workspace/aaas-api $ mysql -e "show databases;"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```

Was there anything changed on GitPod or is there smething we did wrong? We're pretty sure it worked not too long ago.

Many thanks for your awesome application by the way. :+1:
