### ISSUE TITLE
Plugins are not preinstalled by default

### ISSUE THREAD

**Issue by titivermeesch** [gitpod-io/gitpod#2580]
### Describe the bug
When using Code, plugins not preinstalled by default

### Steps to reproduce
Switch  IDE to Code

### Expected behavior
Plugins should get installed

### Additional information
.gitpod.yml
```
image:
  file: .gitpod.Dockerfile

tasks:
  - before: export ROOT_URL=$(gp url 3000)
    init: cd src && npm install
    command: npm run platform_beta
# Populate mongo db?
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001 # Mongo
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8
    - esbenp.prettier-vscode@5.8.0
    - formulahendry.auto-close-tag@0.5.9
    - kamikillerto.vscode-colorize@0.8.17
    - dsznajder.es7-react-js-snippets@3.0.0
    - eamodio.gitlens@10.2.1
    - yzhang.markdown-all-in-one@3.4.0
    - eg2.vscode-npm-script@0.3.11
    - christian-kohler.npm-intellisense@1.2.2
    - christian-kohler.path-intellisense@2.3.0
    - mrmlnc.vscode-scss@0.9.1
    - wayou.vscode-todo-highlight@1.0.4
    - vscode-icons-team.vscode-icons@11.0.0
    - jpoissonnier.vscode-styled-components@1.4.1
    - github.github-vscode-theme@1.1.5
    - vscode-icons-team.vscode-icons@11.0.0
```
