### ISSUE TITLE
Unable to start workspace in case of broken gitpod config 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2627]
### Describe the bug

I've added manually gitpod config that assume that `.gitpod.Dockefile` is exist in repository. 

### Steps to reproduce

1. Open repo in Gitpod by using the following url https://gitpod.io/#https://github.com/lazyorangejs/validate-vscode-extension-pack
2. Add .gitpod.yml file with content 
```yaml
image:
  file: .gitpod.Dockerfile
``
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn && yarn build
    command: yarn start
```
3. Commit and push changes to origin. 
4. Open repo in Gitpod by using the following url https://gitpod.io/#https://github.com/lazyorangejs/validate-vscode-extension-pack again with new changes.
5. Gitpod can't open due to the error `Error: File .gitpod.Dockerfile does not exist in repository lazyorangejs/validate-vscode-extension-pack`

![image](https://user-images.githubusercontent.com/1110697/103206843-7ca84a00-4905-11eb-9ae6-d42a7e733df5.png)

### Expected behavior

I expect that I will be still able to open a repo to fix issue, commit changes then recreate workspace.

### Additional information

![image](https://user-images.githubusercontent.com/1110697/103206843-7ca84a00-4905-11eb-9ae6-d42a7e733df5.png)

### Example repository

https://github.com/lazyorangejs/validate-vscode-extension-pack/commit/cf1dc4d2914c3813d377afb42caf0c333be42cd7
