### ISSUE TITLE
Sync task phases

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#267]
Through `.gitpod.yml` one can provide multiple shell commands for different phases on start (before, init, command, etc.). 
When using multiple tasks, we should sync execution of the commands per phase. E.g.
```yaml
tasks:
 - init: npm install
   command: npm run watch
 - command: npm start
```
Should first run the init command from task 1, before it runs the `command` part of both tasks in parallel (two terminals). This also has the nice effect that multiple commands would not need to be chained to one, i.e. `{ npm install } && { npm run watch }`, but would be individual commands instead. So we get a cleaner bash history.

Unfortunately, this is not so easy to do. There is a proposal for Xterm.js to inject escape sequences but it is not done. See also https://github.com/Microsoft/node-pty/issues/56

**Comment by jankeromnes** [comment]
Random notes:

- As a potential workaround, one can duplicate the `init` command (seems to work with `npm install` at least):

```yaml
tasks:
- init: npm install
  command: npm run watch
- init: npm install
  command: npm start
```

- The Shields project uses `concurrently` to pack two commands in its `npm start` script:

https://github.com/badges/shields/blob/9cb399a8dcdad6181748f43307957a00428b8e81/package.json#L109
