### ISSUE TITLE
Is docker engine supported by gitpod ?

### ISSUE THREAD

**Issue by yyexplore** [gitpod-io/gitpod#2691]
Hello 

The container of  our k8s vendor provided is docker .  The architecture  seems like this

![docker](https://user-images.githubusercontent.com/3124074/103880945-c1598f80-5114-11eb-8dbf-cb777e3c4498.png)

I met a problem when installing ws-daemon , file of ` /run/containerd/io.containerd.runtime.v1.linux/k8s.io`  is missing , seems that gitpod will invoke CRI plugin interface of Containerd, but the CRI plugin is disabled by docker by default.

Is there any  workaround to solve this problem ?

**Comment by csweichel** [comment]
I'm afraid not. At the moment Gitpod requires `containerd-cri`. There's a good chance we'll need CRI only in the future, at which point `dockershim` would work as well. Unfortunately there's no timeline for this change yet.

**Comment by jgallucci32** [comment]
I wanted to add a note here that `dockershim` does in fact work with Gitpod v0.6.0 using both Docker CE 19.03 and 20.10 on both RHEL 7 & 8 distributions. I'm actively trying to track down the breaking change in later Gitpod releases to determine if there is a plausible workaround.

**Comment by jgallucci32** [comment]
I was able to get `containerd-cri` enabled using an installation of Docker CE. To enable it you must do the following:
1. Enable CRI plugin by modifying `/etc/containerd/config.toml` as follows
```
disabled_plugins = []
```
2. Run `systemctl restart containerd`
3. Verify `cri` plugin is enabled by running `ctr plugins ls | grep cri`
3. Modify `kubelet` to use containerd instead of dockershim (this example is for RKE cluster.yaml)
```yaml
    kubelet:
      extra_args:
        container-runtime: remote
        container-runtime-endpoint: 'unix:///run/containerd/containerd.sock'
      extra_binds:
        - '/var/gitpod:/var/gitpod'
        - '/var/lib/containerd:/var/lib/containerd'
```
I used these two sources as reference coming up with the configuration
https://gianarb.it/blog/kubernetes-1-20-dockershim-in-practice
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/
