### ISSUE TITLE
Workspace Dockerfile Build Hang

### ISSUE THREAD

**Issue by sabrehagen** [gitpod-io/gitpod#284]
I'm stuck at Step 13/14 building workspace image. What occurs in this step?

I have tried the following two `.gitpod.yml` files:

Build on workspace start:

```yml
image:
  file: infrastructure/containers/development-environment-gitpod/Dockerfile
  context: infrastructure/containers/development-environment-gitpod
```

Use pre-built dockerhub image:

```yml
image: stemn/development-environment-gitpod:latest
```

The `stemn/development-environment-gitpod` Dockerfile is as follows:

```Dockerfile
FROM stemn/development-environment:latest
USER root
```

![image](https://user-images.githubusercontent.com/1094600/52314693-f2505780-2a07-11e9-808e-e4189d9028b5.png)
