### ISSUE TITLE
error: OCI runtime exec - when running a docker command with healthcheck

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#2845]
### Describe the bug

Running a docker command with healthcheck (while `sudo docker-up` is running), cause an error.

### Steps to reproduce

1. In https://gitpod.io/settings/ enable "Feature Preview" (but first read the description carefully)
1. In your workspace, start the Docker daemon with `sudo docker-up`
1. In a new Terminal, run `docker run -it --rm debian:buster-slim bash`
Check the terminal that is running docker-up, there should be **no errors**.

1. In a new Terminal, run `docker run -it --rm --health-cmd=ls --health-interval=1s debian:buster-slim bash`
Check the terminal that is running docker-up, you will see an error similar to this:
```
WARN[2021-01-12T04:51:03.049636537Z] Health check for container 75eb20919c86a3b05eb789d04602fc9df9dfc73eca2d6e5ca36b97c9dbebab15 error: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown
```

### Expected behavior

The command should run with healthcheck with no errors.

### Example repository

This branch is set to run the command that generates errors.
https://gitpod.io/#https://github.com/shaal/ddevenv/tree/docker-error
The content of its gitpod.yml is 
```
tasks:
  - name: docker_up
    command: sudo docker-up
  - name: run_command
    command: docker run -it --rm --health-cmd=ls --health-interval=1s debian:buster-slim bash
```
