### ISSUE TITLE
[self-hosted] Wait helm template failed; error in minio chart

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#2911]
### Describe the bug

When deploying the latest 0.6.0 helm chart, the following error is given with helm:
```
Wait helm template failed. Error: render error in "gitpod/charts/minio/templates/deployment.yaml": template: gitpod/charts/minio/templates/_helpers.tpl:49:43: executing "minio.deployment.apiVersion" at <.Capabilities.KubeVersion.Version>: can't evaluate field Version in type *version.Info : exit status 1
```

### Steps to reproduce

Deploy gitpod-0.6.0 helm chart (clean install)

### Expected behavior

Chart deploys

### Additional information

Did not have this issue with 0.6.0-beta5. Same `answers.yaml` file was used. Here are the relevant minio configuratoins:
```yaml
  components:
    wsDaemon:
      remoteStorage:
        minio:
          accessKey: "<accesskey>"
          secretKey: "<secretkey>"
  minio:
    accessKey: "<accesskey>"
    secretKey: "<secretkey>"
    s3gateway:
      enabled: true
      serviceEndpoint: "https://s3.domain.local"
```

### Example repository

n/a
