### ISSUE TITLE
Support Elixir language

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#30]
Add support for https://elixir-lang.org/

source for request: [here](
https://twitter.com/Betree83/status/1034759172099846144)

**Comment by svenefftinge** [comment]
https://github.com/JakeBecker/elixir-ls

**Comment by jehrhardt** [comment]
Would love to use for my open source Elixir / Phoenix project: https://github.com/technology-ebay-de/werkstatt

If you need anyone for testing it, just ping me.

**Comment by svenefftinge** [comment]
You can subscribe to this https://github.com/gitpod-io/gitpod/issues/433
It will allow to install the elixir VS Code extension.

**Comment by lemol** [comment]
@svenefftinge , following #433 now I was able to install the elixir extension, but cannot figure out how to run `elixir` (or `mix`) command.
Is it be possible to build elixir app on gitpod?

**Comment by lemol** [comment]
Following the docs in https://www.gitpod.io/docs/42_config_docker/ I figured out how to make install elixir on my workspace, I just add the installation step on the Dockerfile `.gitpod.Dockerfile`:

```Dockerfile
FROM gitpod/workspace-full

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb \
    && dpkg -i erlang-solutions_1.0_all.deb \
    && apt-get update \
    && apt-get install esl-erlang -y \
    && apt-get install elixir -y
```

**Comment by svenefftinge** [comment]
@lemol awesome! Thanks for looking into it. Do you have a public repository that can be used as an example?

**Comment by lemol** [comment]
Sure!
I also included the elixir vs extension and it works nicely: https://github.com/lemol/guess_elixir

**Comment by sntran** [comment]
For Phoenix, there are a few additions:

```Dockerfile
FROM gitpod/workspace-postgres

USER root

ENV DEBIAN_FRONTEND noninteractive

# Install Erlang, Elixir, Hex and Rebar
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb \
    && dpkg -i erlang-solutions_1.0_all.deb \
    && apt-get update \
    && apt-get install esl-erlang -y \
    && apt-get install elixir -y \
    && apt-get install inotify-tools -y \
    && mix local.hex --force \
    && mix local.rebar --force \
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
```

.gitpod.yml
```Yaml
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 4000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
# Install front-end assets
- init: cd apps/mkfifo/assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
# Install dependencies
- init: psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && mix deps.get && mix ecto.create
  command: iex -S mix phx.server

vscode:
  extensions:
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==
```

There are still some confusions for me with `.gitpod.yml`, as I am trying to create the `postgres` user for Phoenix, and somehow one terminal does not see the `postgres` user being created. Would love to see some improvement.

**Comment by jankeromnes** [comment]
Hi @sntran, thanks a lot for sharing this configuration!

> There are still some confusions for me with `.gitpod.yml`, as I am trying to create the `postgres` user for Phoenix, and somehow one terminal does not see the `postgres` user being created.

I can help you debug this.

Firstly, I tried to import your config into https://github.com/jankeromnes/test-phoenix, but I'm obviously missing some files, because I get error like `cd: apps/mkfifo/assets: No such file or directory` and `please ensure you are running Mix in a directory with a mix.exs file`. If your repository is public, could you please share its URL here?

But I can make a few guesses:

> somehow one terminal does not see the `postgres` user being created

maybe this terminal checks for the `postgres` user too early? (Both `init` tasks will run in parallel, and thus race each other.)

If that's the case, the fix is to use synchronization, e.g. with `gp sync-await` and `gp sync-done`:

```yml
tasks:
  - init: gp sync-await pguser && # ... (user 'postgres' should exist here)
  - init: >
      psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && \
      gp sync-done pguser # (notify we're done creating the user)
```
