### ISSUE TITLE
registry facade fails on cluster agent nodes

### ISSUE THREAD

**Issue by z3ky** [gitpod-io/gitpod#3037]
### Describe the bug

The registry facade fails on k3s cluster agent nodes and turns to CrashLoopBackOff. Its logs are

```
{
    "fn": "/mnt/pull-secret.json",
    "level": "info",
    "message": "using authentication for backing registries",
    "serviceContext": {
        "service": "registry-facade",
        "version": ""
    },
    "severity": "INFO",
    "time": "2021-01-27T14:22:14Z"
}
{
    "level": "info",
    "message": "preparing static layer",
    "serviceContext": {
        "service": "registry-facade",
        "version": ""
    },
    "severity": "INFO",
    "time": "2021-01-27T14:22:14Z"
}
{
    "host": "gcr.io",
    "level": "debug",
    "message": "resolving",
    "severity": "DEBUG",
    "time": "2021-01-27T14:22:14Z"
}
{
    "host": "gcr.io",
    "level": "debug",
    "message": "do request",
    "request.header.accept": "application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*",
    "request.header.user-agent": "containerd/1.4.1+unknown",
    "request.method": "HEAD",
    "severity": "DEBUG",
    "time": "2021-01-27T14:22:14Z",
    "url": "https://gcr.io/v2/gitpod-io/self-hosted/supervisor/manifests/0.6.0"
}
{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "error": "cannot source layer from gcr.io/gitpod-io/self-hosted/supervisor:0.6.0: failed to do request: Head \"https://gcr.io/v2/gitpod-io/self-hosted/supervisor/manifests/0.6.0\": dial tcp: i/o timeout",
    "level": "fatal",
    "message": "cannot create registry",
    "serviceContext": {
        "service": "registry-facade",
        "version": ""
    },
    "severity": "CRITICAL",
    "time": "2021-01-27T14:22:44Z"
}
```

The pods on the master work.

### Steps to reproduce

Connecting an agent node to a k3s master that runs Gitpod 0.6.0

### Expected behavior

The registry facade should not fail.

### Additional information

Self-hosted Gitpod 0.6.0, k3s v17
Same behavior with internal and private registry.

Edit: formatted JSON

**Comment by AlexTugarev** [comment]
> failed to do request: Head \"https://gcr.io/v2/gitpod-io/self-hosted/supervisor/manifests/0.6.0\": dial tcp: i/o timeout"

@z3ky this sounds like a network issue. can you verify, that gcr.io can be reached from the cluster, please?

**Comment by z3ky** [comment]
It can be reached
`wget https://gcr.io/v2/gitpod-io/self-hosted/supervisor/manifests/0.6.0`
from the agent downloads the manifest file.

**Comment by corneliusludmann** [comment]
Same as this? https://github.com/gitpod-io/gitpod/issues/3016#issuecomment-768671081

You probably need to set `dindMtu`:

https://github.com/gitpod-io/gitpod/blob/6b10ec9eb0f44f27f50a07ff49bbfe1ab797834f/install/docker/gitpod-image/values.yaml#L22-L23

**Comment by z3ky** [comment]
Setting MTU has no effect

**Comment by corneliusludmann** [comment]
Could you probably post your `values.yaml` file here?

**Comment by z3ky** [comment]
sure. the only non-standard setting is the registryProxyPort due to a conflict with another application on the server.

```
# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

# This field must be set to your domain name. Leaving it set to its default value will result in
# a non-functional installation.
hostname: mydomain.com
ingressMode: hosts

# If you have a static IP that your domain resolves to, set it here.
# Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
# during deployment.
proxy:
  loadBalancerIP: x.x.x.x
    
# Gitpod needs at least one auth provider to allow users to log in.
# The auth providers below are examples only. Please change/remove them to fit your installation.
authProviders:
- id: "Example GitHub"
  host: "github.com"
  type: "GitHub"
  oauth:
    clientId: "xxx"
    clientSecret: "xxx"
    callBackUrl: "https://mydomain.com/auth/github/callback"
    settingsUrl: "https://github.com/settings/connections/applications/xxx"

workspaceSizing:
  requests:
    cpu: "1m"
    memory: "2.25Gi"
    storage: "5Gi"
  limits:
    cpu: "5"
    memory: "12Gi"

docker-registry:
  enabled: true

components:
  nodeDaemon:
    # Gitpod copies Theia to each node. This setting configures where Theia is copied to.
    # We'll copy Theia to $theiaHostBasePath/theia/theia-$version
    # The faster this location is (in terms of IO) the faster nodes will become available and the faster workspaces will start.
    theiaHostBasePath: /opt/data/gitpod

  imageBuilder:
    # The image builder deploys a Docker-in-Docker-daemon. By default that Docker daemon works in an empty-dir on the node.
    # Depending on the types of node you operate that may cause image builds to fail or not perform well. We recommend you give the Docker daemon
    # fast storage on the node, e.g. an SSD.
    hostDindData: /opt/data/gitpod/docker
    dindMtu: 1450
  
  wsDaemon:
    # Workspace data is stored on the nodes. This setting configures where on the ndoe the workspace data lives.
    # The faster this location is (in terms of IO) the faster workspaces will initialize.
    hostWorkspaceArea: /opt/data/gitpod/workspaces
    registryProxyPort: 18081
    containerRuntime:
      nodeRoots:
      - /run/containerd/io.containerd.runtime.v1.linux/moby
```
