### ISSUE TITLE
Install extension to code editor by using an url to extension 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#3045]
It would be useful to be able to add an extension that are not published to OpenVSX registry by using a public url to extension.

There is an example. 

```yaml
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm i # runs during prebuild
    command: 'NODE_ENV=development npm run dev'

vscode:
  extensions:
  - pflannery.vscode-versionlens
  - mikestead.dotenv
  - https://github.com/mongodb-js/vscode/releases/download/v0.4.0/mongodb-vscode-0.4.0.vsix
```
