### ISSUE TITLE
[Helm chart] Configuring sensitive values via secrets

### ISSUE THREAD

**Issue by cyrilcros** [gitpod-io/gitpod#3094]
Hi,
Would it be possible to set the sensitive values in the Helm chart (like `components.server.sessionSecret` for ex., but also db password and oauth info) via either an `existingSecret` secret reference or setting an environment variable? 
Right now the `values.yaml` has sensitive information in it which is an issue for “gitops-style” management of Kubernetes.
Thanks!

**Comment by csweichel** [comment]
That makes perfect sense. We could adopt a pattern akin to how we handle the HTTPS certificates, except that one could still provide the value directly if necessary, e.g.:
```YAML
server:
  sessionSecret:
    secretName: some-preexisting-secret
    key: data-in-the-secret
```

but also:
```YAML
server:
  sessionSecret:
    value: "enter value here directly"
```

We would do that for:
- `db.password`
- `messagebus.password`
- `minio.accessKey`
- `minio.secretKey`
- `server.sessionSecret`
