### ISSUE TITLE
Workspace terminates immediately

### ISSUE THREAD

**Issue by enriquecaballero** [gitpod-io/gitpod#3185]
### Describe the bug
Using the gitpod-k3s image, version 0.7.0, behind a Traefik reverse proxy and an external registry. I also have a separate GitLab instance that I intend to integrate with Gitpod and all of seems to work fine (oauth's all good). Everything works fine until I attempt to create a workspace. It pulls the image and does its thing but then terminates the workspace pod. Unfortunately every time I try to describe pod, information isn't very helpful. However, the annotations have the following information:

```
Annotations:               gitpod.io/requiredNodeServices: ws-daemon
                           gitpod/admission: admit_owner_only
                           gitpod/contentInitializer:
                             ErgBCkNodHRwczovL2dpdGxhYi5jYWJhbGxlcm8uZGV2L2JvaWxlcnBsYXRlcy9yZWFjdC1hcHAtYm9pbGVycGxhdGUuZ2l0GAIiBm1hc3RlcioVcmVhY3QtYXBwLWJvaWxlcnBsYX...
                           gitpod/customTimeout: 30m
                           gitpod/explicitFail: cannot initialize workspace: cannot use configured storage: cannot create bucket: The specified bucket does not exist.
                           gitpod/failedBeforeStopping: true
                           gitpod/id: b453c77c-1b3c-4e57-8328-1182fc83ef1c
                           gitpod/imageSpec:
                             CmhyLmdpdHBvZC5jYWJhbGxlcm8uZGV2L3dvcmtzcGFjZS1pbWFnZXM6NTQ4MTNhYjEyYWU0YTQ3NmNkNjRmMDEwMDYyZTc5NTFkODJhNjQ3ZjhkM2ZkYTcyZDVmODNlNWY4Y2I5Nj...
                           gitpod/never-ready: true
                           gitpod/ownerToken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                           gitpod/servicePrefix: fuchsia-cat-x9238vzo
                           gitpod/traceid: AAAAAAAAAABYrl6mlfkUKS4aOfKdfIKmYtP6wtC9utMAAAAAAA==
                           gitpod/url: http://fuchsia-cat-x9238vzo.ws.gitpod.caballero.dev
                           prometheus.io/path: /metrics
                           prometheus.io/port: 23000
                           prometheus.io/scrape: true
                           seccomp.security.alpha.kubernetes.io/pod: runtime/default
```

### Steps to reproduce
Create a workspace or start a workspace.

### Expected behavior
Workspace should open fine.

### Additional information
docker-compose.yml
```yaml
version: '3'
services:
  gitpod:
    image: eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:0.7.0
    privileged: true 
    environment:
      - DOMAIN=gitpod.caballero.dev
    expose:
      - 80
    volumes:
      - "$PWD/values:/values"
      - "$PWD/docker:/var/gitpod/docker"
      - "$PWD/docker-registry:/var/gitpod/docker-registry"
      - "$PWD/minio:/var/gitpod/minio"
      - "$PWD/mysql:/var/gitpod/mysql"
      - "$PWD/workspaces:/var/gitpod/workspaces"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitpod.rule=Host(`gitpod.caballero.dev`, `*.gitpod.caballero.dev`, `*.ws.gitpod.caballero.dev`)"
      - "traefik.http.services.gitpod.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
```

values.yaml
```yaml
hostname: gitpod.caballero.dev

authProviders:
  - description: ''
    host: gitlab.caballero.dev
    icon: ''
    id: Internal-GitLab
    oauth:
      callBackUrl: 'https://gitpod.caballero.dev/auth/gitlab.caballero.dev/callback'
      clientId: XXXXXXXXX
      clientSecret: XXXXXXXXX
      settingsUrl: 'https://gitlab.caballero.dev/profile/applications'
    type: GitLab

certificatesSecret:
  secretName: null

components:
  imageBuilder:
    registryCerts: []
    registry:
      name: r.gitpod.caballero.dev
      path: '' 
      secretName: image-builder-registry-secret
  workspace:
    pullSecret:
      secretName: image-builder-registry-secret

minio:
  accessKey: XXXXXXXXX
  secretKey: XXXXXXXXX

docker-registry:
  enabled: false
```

I'm stumped. Been trying for almost two weeks to get the self-hosted version of Gitpod to run. Tried everything. I even attempted to install via Rancher but that had other issues... This Docker version is the closest I've been. Any help would be awesome.
