### ISSUE TITLE
[self-hosted] cannot initialize workspace: exit status 42. CreateContainerConfigError: cannot find volume "vol-this-workspace" to mount into container "workspace"

### ISSUE THREAD

**Issue by alexlhoffman** [gitpod-io/gitpod#3187]
### Describe the bug

I have a self-hosted instance of Gitpod running in vanilla k8s 1.20, Debian 10. When starting any workspace, it immediately fails with the error `cannot initialize workspace: cannot initialize workspace: exit status 42` as seen in the following screenshot:

<img width="537" alt="Screen Shot 2021-02-14 at 12 27 33 PM" src="https://user-images.githubusercontent.com/5889769/107888279-22b51100-6ec0-11eb-8491-ad01606a8dbf.png">

When I check the workspace pod (it is terminated immediately, so there's only a brief moment to do this), I found the following status:

```
containerStatuses:
    - name: workspace
      state:
        waiting:
          reason: CreateContainerConfigError
          message: >-
            cannot find volume "vol-this-workspace" to mount into container
            "workspace"
      lastState: {}
      ready: false
      restartCount: 0
      image: >-
        registry.my-gitpod-domain.com/workspace-images:54813ab12ae4a476cd64f010062e7951d82a647f8d3fda72d5f83e5f8cb9685f
      imageID: ''
      started: false
```

I watched the directory `/var/gitpod/workspaces` on the node this workspace was started on, and I see briefly that the workspace folder is created correctly, but I think by the time this happens the pod is already terminating. Does this seem like a possible cause? If so, is there a way to add a startup delay to allow the directory to be created before immediately terminating?

### Steps to reproduce

Install Gitpod 0.1.5 on vanilla k8s 1.20 on Debian 10. Workspaces will fail to start.

### Expected behavior

A Gitpod workspace would be started successfully.

### Additional information

Setup:

- OS: Debian 10
- Kubernetes: 1.20 deployed with kubeadm.
```
% kubectl version
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Gitpod: deployed with helm using chart version `gitpod-0.6.0` and gitpod version 0.1.5.

### Example repository

I created an empty repo in an private internal GitLab instance.
