### ISSUE TITLE
[Self-Hosted] Minio Backup Max Size not working

### ISSUE THREAD

**Issue by stefanstoeckigt** [gitpod-io/gitpod#3204]
### Describe the bug
Gitpod 0.7.0b1, Kubernetes 1.16
When increasing the max backup size, backup for workspaces larger than 30Gb still fail. . 
```last backup failed: workspace content was never ready. Please contact support if you need the workspace data.```

### Steps to reproduce

1. Update the helm values to increase the minio ```maxBackupSize```. 
2. Download large file in workspace and close. 

```yaml
components:
  contentService:
    remoteStorage:
      kind: "minio"
      blobQuota: 0
      backupTrail:
        enabled: true
        maxLength: 3
      minio:
        maxBackupSize: 64424509440
        parallelUpload: 6
```

### Expected behavior
Workspace should backup 64Gb.
