### ISSUE TITLE
Custom domain for the IDE

### ISSUE THREAD

**Issue by JeremyJaydan** [gitpod-io/gitpod#329]
Ability to add a CNAME which is somehow directed to your current active workspace's open ports would be cool.

**Comment by svenefftinge** [comment]
We'd rather integrate well with services that do these things better, such as now.sh, netlify, platform.sh etc. Would that be good enough in your case?

**Comment by JeremyJaydan** [comment]
Yeah those make sense for deployment although I'm thinking in terms of sharing a custom URL with friends which shows the live development version (which would stop working when I close a workspace). 

Something like https://dev.example.com would show the live development version of https://example.com

**Comment by JeremyJaydan** [comment]
I'm not 100% on the idea though, I understand how complex this can be for the actual returned benefit. More of a "nice to have".

**Comment by meysholdt** [comment]
I'd also prefer to integrate with other platform such as now.sh, netlify, platform.sh... they're optimised to have services running continuously at high density. 

But to discuss your request, I think there are two possibilities:
a) allow custom subdomains, e.g. `jeremys-app.apps-eu.gitpod.io`, with you having it named `jeremys-app`.
b) allow custom top-level domains, e.g. `jeremys-app.com`

While (a) could be doable, (b) brings more challenges:
* request ssl certs on-demand
* you, as the owner of your domain, would need to configure one of Gitpod's IPs in your DNS

**Comment by JeremyJaydan** [comment]
(a) sounds like a great idea, maybe it could be part of the configuration:
```yaml
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: "<your-workspace-image>"
# Command to start on workspace startup (optional)
tasks:
  - command: "yarn install && yarn build"
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
# Sub domain
domain: "jeremys-app"
```
