### ISSUE TITLE
'- print' configuration key/value for "readme" purposes

### ISSUE THREAD

**Issue by JeremyJaydan** [gitpod-io/gitpod#330]
(context):
Over at [the configuration docs](https://docs.gitpod.io/41_Config_Gitpod_File.html) there is the following codeblock..
```yaml
# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: "<your-workspace-image>"
# Command to start on workspace startup (optional)
tasks:
  - command: "yarn install && yarn build"
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
```

(feature request):
It'd be cool to have a `- print: "what you want to print"` option within the tasks which would print out to a specific "terminal" or the current active one. 

(example):
```yaml
tasks:
  - command: "npm i firebase-tools -g"
  - print: "Firebase tools has been installed, make sure to add '--no-localhost' to the login cmd"
```

**Comment by meysholdt** [comment]
would this be better than using `echo` as part of the command?
e.g. 
```yaml
tasks:
  - command: > 
      npm i firebase-tools -g
      echo "Firebase tools has been installed, make sure to add '--no-localhost' to the login cmd"
```
