### ISSUE TITLE
[code] support custom extension upload like Theia did

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#3441]
Currently code doesn't persistent user upload extensions.

**Comment by akosyakov** [comment]
We want to rely on Open VSX in long rung and replaced own persistence with ability to use external storages to install extensions. In your .gitpod.yml you can add:
```yaml
- vscode:
  - extensions:
    - http://url-to-my-extension.vsix
```

Could you elaborate on your use case if it does not work?
