### ISSUE TITLE
Self-hosted GCP - installation error

### ISSUE THREAD

**Issue by statictype** [gitpod-io/gitpod#3647]
### Bug description

Can't install on GCP. Was very excited to try the self hosted Gitpod magic install, because i'm not very experienced with dev ops. Unfortunately, both AWS and GCP have some issues at the moment.

### Steps to reproduce

Following the instructions for the easy GCP install i get to a Terraform error and the installation fails

<img width="934" alt="Screenshot 2021-03-29 at 17 20 42" src="https://user-images.githubusercontent.com/42985153/112860363-09ed6d00-90b4-11eb-9737-7ab5f28370c5.png">

**Comment by statictype** [comment]
i think it happened because i left the domain blank, as instructed by the installer, but no temporary domain was added

**Comment by ryo-egch** [comment]
I got same issue before.
As error said, we should not use `load_config_file` . remove it from providers.tf.

Not only this part, you may get other errors as I had also;

See the issue I posted. Not sure your situation is same as me, because mine is a little bit old.
https://github.com/gitpod-io/gitpod/issues/2985

**Comment by plank-tools** [comment]
I deleted the `load_config_file` line from providers.tf and it works. It fails with `min_master_version` in `install/gcp-terraform/modules/kubernetes/main.tf` file having an invalid value of `1.16`. I changed this to `1.18`. It creates the gitpod cluster but fails with the following error

```
gitpod/charts/rabbitmq/templates/statefulset.yaml:36:28: executing "gitpod/charts/rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: gitpod/charts/rabbitmq/templates/secrets.yaml:42:16: executing "gitpod/charts/rabbitmq/templates/secrets.yaml" at <include "common.tplvalues.render" (dict "value" $value "context" $)>: error calling include: template: gitpod/charts/mysql/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "load_definition.json: |\n  {\n    \"users\": [{\n      \"name\": {{ required \"rabbitmq username is required, please add a value to your values.yaml or with the helm flag --set rabbitmq.auth.username=xxxxx\" .Values.auth.username | quote }},\n      \"password\": {{ required \"rabbitmq password is required, please add a value to your values.yaml or with the helm flag --set rabbitmq.auth.password=xxxxx\" .Values.auth.password | quote }},\n      \"tags\": \"administrator\"\n    }],\n    \"vhosts\": [{\n      \"name\": \"/\"\n    }],\n    \"parameters\": {{ tpl (.Values.shovelsTemplate) . | fromYamlArray | toJson }},\n    \"permissions\": [{\n      \"user\": {{ .Values.auth.username | quote }},\n      \"vhost\": \"/\",\n      \"configure\": \".*\",\n      \"write\": \".*\",\n      \"read\": \".*\"\n    }],\n    \"exchanges\": [{\n      \"name\": \"gitpod.ws\",\n      \"vhost\": \"/\",\n      \"type\": \"topic\",\n      \"durable\": true,\n      \"auto_delete\": false\n    }, {\n      \"name\": \"gitpod.ws.local\",\n      \"vhost\": \"/\",\n      \"type\": \"topic\",\n      \"durable\": true,\n      \"auto_delete\": false\n    }, {\n      \"name\": \"wsman\",\n      \"vhost\": \"/\",\n      \"type\": \"topic\",\n      \"durable\": false,\n      \"auto_delete\": false\n    }, {\n      \"name\": \"consensus-leader\",\n      \"vhost\": \"/\",\n      \"type\": \"fanout\",\n      \"durable\": false,\n      \"auto_delete\": false\n    }],\n    \"bindings\": [{\n      \"source\": \"gitpod.ws.local\",\n      \"vhost\": \"/\",\n      \"destination\": \"gitpod.ws\",\n      \"destination_type\": \"exchange\",\n      \"routing_key\": \"#\",\n      \"arguments\": {}\n    }],\n    \"queues\": [{\n      \"name\": \"consensus-peers\",\n      \"vhost\": \"/\",\n      \"durable\": false,\n      \"auto_delete\": false,\n      \"arguments\": {}\n    }, {\n      \"name\": \"pwsupdatable\",\n      \"vhost\": \"/\",\n      \"durable\": true,\n      \"auto_delete\": false,\n      \"arguments\": {}\n    }],\n    \"policies\": [{\n      \"name\": \"ha-all\",\n      \"vhost\": \"/\",\n      \"pattern\": \".*\",\n      \"definition\": {\n        \"ha-mode\": \"all\",\n        \"ha-sync-mode\": \"automatic\",\n        \"ha-sync-batch-size\": 5\n      }\n    }]\n  }": execution error at (gitpod/charts/rabbitmq/templates/statefulset.yaml:4:17): rabbitmq username is required, please add a value to your values.yaml or with the helm flag --set rabbitmq.auth.username=xxxxx

  on ../../modules/gitpod/main.tf line 27, in resource "helm_release" "gitpod":
  27: resource "helm_release" "gitpod" {
```

I have updated the rabbitmq settings in the file values.yaml in `install/gcp-terraform/environment/full/values.yaml` but it doesn't pick up these values.

**Comment by plank-tools** [comment]
I got past the `load_config_file` errors. But I'm running into more problems. These are my settings

`main.autovars.yml`

```yml
name="my gcp account name"
project="my project name"
region="us-east4"
zone_name="us-east4-a"
dns_name = "valid dns name that I own"
container_registry = {
  location = "US"
}
```

```
# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.
certificatesSecret: {}
hostname: "valid dns name owned by me"
rabbitmq:
  auth:
    username: jgrabbitmq
    password: "valid password"
minio:
  accessKey: "generated access key"
  secretKey: "generated secret key"
authProviders:
  - id: "GitLab"
    host: "my gitlab installation"
    protocol: "https"
    type: "GitLab"
    oauth:
      clientId: "verified client id"
      clientSecret: "verified client secret"
      callBackUrl: "verified callback url"
      settingsUrl: "verified settings url" 
components:
  wsProxy:
    ingress:
      portRange:
        start: 10000
        end: 11000
  proxy:      
    loadBalancerIP: "valid ip address pointing to the hostname in my domain provider dns"
```

I get the following errors when I run `terraform plan`

```
Warning: Value for undeclared variable

The root module does not declare a variable named "dns_name" but a value was
found in file "main.auto.tfvars". To use this value, add a "variable" block to
the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Warning: Value for undeclared variable

The root module does not declare a variable named "name" but a value was found
in file "main.auto.tfvars". To use this value, add a "variable" block to the
configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Warning: Deprecated Attribute

  on ../../modules/kubernetes/main.tf line 59, in resource "google_container_cluster" "gitpod":
  59: resource "google_container_cluster" "gitpod" {

This attribute is currently in beta and will be removed from the google
provider. Please use the google-beta provider to continue using this
attribute.


Error: "account_id" ("db") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"

  on ../../modules/database/main.tf line 50, in resource "google_service_account" "gitpod_database":
  50:   account_id   = var.name



Error: googleapi: Error 404: The 'parameters.managedZone' resource named 'us-east4-a' does not exist., notFound

  on ../../modules/dns/main.tf line 25, in data "google_dns_managed_zone" "gitpod":
  25: data "google_dns_managed_zone" "gitpod" {
```
