### ISSUE TITLE
[Self-Hosted] Support Google Artifact Registry to save workspace-images

### ISSUE THREAD

**Issue by ryo-egch** [gitpod-io/gitpod#3695]
I set up Gitpod on GKE, Gitpod version 0.7.0-beta
Currently, downloaded `workspace-images` is saved in Google Container Registry. 

https://github.com/gitpod-io/gitpod/blob/62207521b22d47676fa168a772a2e0a90e51ab32/install/gcp-terraform/modules/registry/templates/values.tpl#L8
```
components:
  imageBuilder:
    registryCerts: []
    registry:
      name: "eu.gcr.io/${project}"
      secretName: ${secretName}
#      path: secrets/registry-auth.json
```

I want to use Google Artifact Registry instead, but just changing registry name from "eu.gcr.io" to "asia-northeast1-docker.pkg.dev" didn't work, got error when starting workspace
>   build failed: cannot push workspace image: name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE.
                  Error: build failed: cannot push workspace image: name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE

On current version, by the way  I cannot figure out which image [stored in GCP](https://console.cloud.google.com/gcr/images/gitpod-io/GLOBAL/self-hosted/installer?gcrImageListsize=30) is available, can we use artifact registry ? Or late it would be supported ?
