### ISSUE TITLE
terminal command history does not look nice

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#376]
I would expect to see `cd examples/browser && yarn start --hostname 0.0.0.0 ../..` as the last command but:
<img width="1444" alt="Screen Shot 2019-03-13 at 08 09 36" src="https://user-images.githubusercontent.com/3082655/54259852-5f0ac480-4567-11e9-9d46-519473c81596.png">

**Comment by 32leaves** [comment]
can you post `/workspace/.cmd-0`? If the history rewriting didn't work that's usually a sign of a broken `HISTFILE`. Breaklines towards the end of the file are important.

**Comment by geropl** [comment]
I think @akosyakov means the `{ <some cmd>} && { <the cmd he expected> }; <some hist file restoration>`.

**Comment by akosyakov** [comment]
Ideally, in this case the last item should be `yarn start --hostname 0.0.0.0 ../..`, otherwise i had to edit it.

**Comment by svenefftinge** [comment]
splitting on shell operators sounds very brittle. If we want to support this, we should allow lists of commands per life cycle and concatenate them with `&&`.

**Comment by cilthepen** [comment]
```
 HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
pnpm run start
}
gitpod /workspace/web-app (main) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> pnpm run start
> }

> web-app@1.0.0 start /workspace/web-app
> next start

- ready started server on [::]:3000, url: http://localhost:3000
HELLOOOOOOOOOOOOOOO
[Error: ENOENT: no such file or directory, open '/workspace/web-app/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/workspace/web-app/.next/BUILD_ID'
}
```

i get this command on init. i don't why even though my .gitpod.yml is this.
```yml
# .gitpod.yml
tasks:
    - name: Start development environment
      init: pnpm install
      command: pnpm run dev

ports:
    - name: Web App
      description: The main application web server
      port: 3000
      onOpen: open-browser

vscode:
    extensions:
        - EditorConfig.EditorConfig
        - usernamehw.errorlens
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - yoavbls.pretty-ts-errors
        - shardulm94.trailing-spaces
```
