### ISSUE TITLE
Registry mirror is not configured for Image builder

### ISSUE THREAD

**Issue by ranzbak** [gitpod-io/gitpod#4109]
### Bug description

Expected:
I followed the description here: https://www.gitpod.io/docs/self-hosted/latest/install/docker-registry/
Understanding that configuring the mirrors, will result in all images being pulled from the Docker mirror, not docker.io.

Observed:
When I tested the setup, I still received a docker rate limiting message, the image builder dind was still pulling from docker.io.

### Steps to reproduce

Configure gitlab self-hosted using the instructions : https://www.gitpod.io/docs/self-hosted/latest/install/docker-registry/

And verify if Docker images get pulled from docker.io, the settings do work for the Pod containers, but the dind containers are still pulled from docker.io.

### Expected behavior

The Docker registry is propageted into the docker image pod, so dind pulls the images from the correct mirror.

Use a config map to mount a daemon.json in the image builder pod:
```
          - mountPath: /etc/docker/daemon.json
            name: docker-daemon-confmap
            subPath: daemon.json

        - configMap:
            defaultMode: 420  
            name: docker-daemon
          name: docker-daemon-confmap  
```

daemon.json:
```
 {
    "registry-mirrors": [
      "https://<mirror name>"
    ]
  }
```

### Anything else?

I've thought about building a custom container, but since this is not really workable with updates i would like a solution in the Helm chart much more.
