### ISSUE TITLE
Prebuilds don't seem to be working

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#4148]
### Bug description

No prebuilds seem to be built or used from Gitpod hosted repos. 

From our gitpod.yml:
```yaml
github:
  prebuilds:
    addCheck: true
    addBadge: true
    addLabel: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
```

Nonetheless, opening Gitpod on the main branch, other branches, or PRs results in a workspace where the rebuild has not run and we must wait for it to run. Slowing down the development cycle significantly. 

Also, newly created PRs are missing the usual prebuild check.

### Steps to reproduce

Open any repo

### Expected behavior

Should prebuild

### Anything else?

Using VSCode
