### ISSUE TITLE
Access to multiple repositories? 

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#418]
I have a special situation that in of my project that I work on I need to access several other repositories which are not managed as submodules. Is possible to have a token that have read/write access to multiple repositories? Or is submodule the way to go?

**Comment by svenefftinge** [comment]
I think you need to use submodules. You can clone additional repositories, but not on startup, as the workspace doesn't container your token. You need to have the IDE open as it is requested through your session for security reasons.

**Comment by jankeromnes** [comment]
> Is possible to have a token that have read/write access to multiple repositories?

Actually yes, you can already manage all your repositories from any single Gitpod workspace.

If you don't want to use submodules, you can simply `cd /workspace && git clone https://github.com/dclong/other-project`.

You can even automate this by adding a `.gitpod.yml` like this to your project:

```yaml
tasks:
- init: >
    git clone https://github.com/dclong/other-project-1 /workspace &&
    git clone https://github.com/dclong/other-project-2 /workspace
```
