### ISSUE TITLE
trying to get hot loader working

### ISSUE THREAD

**Issue by catmando** [gitpod-io/gitpod#435]
https://hyperstack.org has a built in hotloader that sets up a push notification from a task running on server, to the client.

I cant get this to work on gitpod.

after a minute or so the client throws this error:

WebSocket connection to 'wss://5000-d229dba3-3441-4622-a288-3a4990c9cc1b.ws-us0.gitpod.io:25222/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

Here is my .gitpod.yml file:

```
tasks:
  - init:
      bundle install
  - command:
      bundle exec rake db:create &&
      bundle exec rake db:migrate
ports:
- port: 5000
- port: 3000
- port: 9514
- port: 9515
- port: 25222
```

Any help is appreciated.  The repo is here:

`https://github.com/hyperstack-org/todo-compare` use the ``gitpod`branch

for simplicity I am running in two terminal windows instead of using foreman

terminal 1: `bundle exec rails s -b 0.0.0.0 -p 5000
terminal 2: `bundle exec hyperstack-hotloader -p 25222 -d app/hyperstack/`

if you change a file in the app/hyperstack directoy you will see it is noticed but no message goes to the client.

The funny thing this safe app uses Rails action-cable, and that works fine!
