### ISSUE TITLE
can't get initialization to work

### ISSUE THREAD

**Issue by catmando** [gitpod-io/gitpod#456]
I have the following .gitpod.yml file.

It doesn't seem to do anything:

```yaml
tasks:
  - init:
      bundle install && 
      yarn &&
      bundle exec rake db:reset
  - command:
      bundle exec foreman start
ports:
  - port: 5000
  - port: 3000
  - port: 9514
  - port: 9515
  - port: 25222
```

the repo is here: https://github.com/hyperstack-org/todo-compare/tree/gitpod

thanks in advance

**Comment by svenefftinge** [comment]
You are creating two terminals here, I guess what you want is the following:

```yaml
tasks:
  - init:
      bundle install && 
      yarn &&
      bundle exec rake db:reset
    command:
      bundle exec foreman start
ports:
  - port: 5000
  - port: 3000
  - port: 9514
  - port: 9515
  - port: 25222
```

Please note, that for the ports you can specify what action to take when they open. 
See https://www.gitpod.io/docs/43_Config_Ports/#configure-the-opening-behavior
