### ISSUE TITLE
Self hosted fails on trying to create workspace

### ISSUE THREAD

**Issue by tarioch** [gitpod-io/gitpod#4582]
### Bug description

When trying to create a workspace it fails with

```
Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Get https://registry.gitpod.MYDOMAIN.COM/v2/: x509: certificate is valid for ingress.local, not registry.gitpod.MYDOMAIN.COM

Unknown Error: { "code": -32603 }
```

### Steps to reproduce

Try to create any workspace (e.g. example workspaces)

### Anything else?

My values file

```yaml

hostname: gitpod.MYDOMAIN.COM

certificatesSecret:
  certName: tls.crt
  chainName: tls.crt
  fullChainName: tls.crt
  keyName: tls.key

installNetworkPolicies: true

components:
  wsDaemon:
    containerRuntime:
      containerd:
        socket: /run/k3s/containerd/containerd.sock
      nodeRoots: 
      - /var/lib
      - /run/k3s/containerd/io.containerd.runtime.v1.linux
      - /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
  workspace:
    template:
      spec:
        dnsConfig: null
        dnsPolicy: ClusterFirst
  imageBuilder:
    dindMtu: 1450
  proxy:
    ports:
      http:
        expose: false

minio:
  accessKey: SECRET
  secretKey: SECRET
  resources:
    requests:
      memory: 2G

rabbitmq:
  auth:
    username: SECRET
    password: SECRET

docker-registry:
  enabled: true
```

the certificate was created with certmanager and the secret looks like this

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: https-certificates
  namespace: gitpod
  annotations:
    cert-manager.io/alt-names: '*.gitpod.MYDOMAIN.COM,*.ws.gitpod.MYDOMAIN.COM,gitpod.MYDOMAIN.COM'
    cert-manager.io/certificate-name: gitpod-cert
    cert-manager.io/common-name: gitpod.MYDOMAIN.COM
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod-dns
    cert-manager.io/uri-sans: ""
data:
  ca.crt: ""
  tls.crt: SECRET
  tls.key: SECRET
```

I'm running on a single node k3s cluster and trying version 0.9.0
