### ISSUE TITLE
Certificate error in ws-proxy in official k3s docker image

### ISSUE THREAD

**Issue by krejcar25** [gitpod-io/gitpod#4628]
### Bug description

When using the k3s docker image `` the `ws-proxy` pod will not start. Pod log attached below. Certificate dir mounted into `/certs` as specified in [README.md](https://github.com/gitpod-io/gitpod/blob/main/install/docker/README.md). `docker-compose.yml` snippet attached below.

```
{"ca":"/ws-manager-client-tls-certs/ca.crt","cert":"/ws-manager-client-tls-certs/tls.crt","key":"/ws-manager-client-tls-certs/tls.key","level":"debug","message":"using TLS config to connect ws-manager","serviceContext":{"service":"ws-proxy","version":""},"severity":"DEBUG","time":"2021-06-27T19:26:39Z"}
{"level":"info","message":"workspace info provider started","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-06-27T19:26:39Z"}
{"level":"info","message":"started proxying on :8080","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-06-27T19:26:39Z"}
{"addr":":60060","level":"info","message":"serving pprof service","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-06-27T19:26:39Z"}
{"addr":":60095","level":"info","message":"started Prometheus metrics server","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-06-27T19:26:39Z"}
{"level":"info","message":"🚪 ws-proxy is up and running","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-06-27T19:26:39Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"open /mnt/certificates/cert.pem: no such file or directory","level":"fatal","message":"cannot start proxy","serviceContext":{"service":"ws-proxy","version":""},"severity":"CRITICAL","time":"2021-06-27T19:26:39Z"}
```

### Steps to reproduce

Follow steps in README.md. Create container, copy certificates, configure `values.yml` and run.

### Expected behavior

`ws-proxy` pod should try to read the certificate from `/mnt/certificates/fullchain.pem` as configured in secret.

#### Compose snippet

```yaml
  gitpod:
    image: 'gcr.io/gitpod-io/self-hosted/gitpod-k3s:0.9.0'
    restart: unless-stopped
    environment:
      - DOMAIN=code.gitlab.example.com
    volumes:
      - '/var/docker/gitlab/gitpod/data/mysql:/var/gitpod/mysql:rw'
      - '/var/docker/gitlab/gitpod/data/minio:/var/gitpod/minio:rw'
      - '/var/docker/gitlab/gitpod/certs:/certs:rw'
      - '/var/docker/gitlab/gitpod/values:/values:rw'
      - '/var/docker/gitlab/gitpod/data/workspaces:/var/gitpod/workspaces:rw'
      - '/var/docker/gitlab/gitpod/data/docker-registry:/var/gitpod/docker-registry:rw'
      - '/var/docker/gitlab/gitpod/data/docker:/var/gitpod/docker:rw'
    dns:
      - 1.1.1.1
    networks:
      - proxy
    privileged: true
```

Edit: No ports are specified in compose, as traefik is used as SSL termination proxy, via the `proxy` network. This worked flawlessly in previous versions.
