### ISSUE TITLE
[self-hosted] Release 0.10.0

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#4710]
After we released [0.9.0](https://github.com/gitpod-io/gitpod/releases/tag/v0.9.0) with quite a delay, we plan to have a regular cadence to not let down our Self-Hosted users.

In that vein - and after the release to gitpod.io last week - we plan to quickly release 0.10.0, which should be a straight-forward "test-and-release" because there have been no bigger changes that should impact Self-Hosted.

### Test
- [x] test on k3s
- [ ] test on GCP

### Tasks
- [x] fix access to self-hosted registry: either #4711 or #4592
- [x] fix UI to show the setup page for Self-Hosted: #4764
- [x] updates docs: https://github.com/gitpod-io/website/issues/745
- [x] fix DB migration are not executed
- [x] docker credentials
  - [x] docs: add to new `values.custom.yaml` (next to minio etc.)
  - [x] docs: migration guide

/cc @corneliusludmann @solomonope

**Comment by geropl** [comment]
Dumping my personal notes here, in hope this might help whoever works on this:
 - [ ] docs:
   - [ ] "Configure Ingress": cerbot: copy'n'paste is broken
   - [ ] replace "find -exec copy broken: "find $WORKDIR/config/live -name "*.pem" -exec cp {} secrets/https-certificates \;" with
     - cp $WORKDIR/config/live/fullchain.pem secrets/https-certificates/tls.crt
     - cp $WORKDIR/config/live/privkey.pem secrets/https-certificates/tls.key
   - [ ] troubleshooting:
     - [ ] container runtime config for k3s:
        ```
        containerRuntime:
        containerd:
            socket: /var/run/k3s/containerd/containerd.sock
        nodeRoots:
            - /var/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
        ```
     - [ ] make visible in the navigation
   - [ ] migration guide:
     - [ ] make visible in navigation
     - [ ] 0.9.0 -> 0.10.0
       - mv secrets/https-certificates/fullchain.pem secrets/https-certificates/tls.crt
       - mv secrets/https-certificates/privkey.pem secrets/https-certificates/tls.key
