### ISSUE TITLE
Gitpod is not loading the workspaces

### ISSUE THREAD

**Issue by tommygonzaleza** [gitpod-io/gitpod#4825]
### Bug description

When I try to open the workspace, this is what I get:
![Uploading C1BB7889-D89F-4D20-BDAA-2EA3620395E9.jpeg…]()

### Steps to reproduce

It happens when I open the workspace, it just never opens it

**Comment by tommygonzaleza** [comment]
![Uploading 87A84E1D-9376-49A6-95F9-5850018414D6.jpeg…]()

**Comment by jabuwu** [comment]
I was having the same issue until just now.. so maybe it's fixed?

**Comment by jelaniwoods** [comment]
This has been happening to me too with new and old workspaces. The workspace gets stuck in the preparing stage and then fails with the error
```
Oh, no! Something went wrong!

Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
```

one new workspace did open eventually, but I'm unable to open old ones.

**Comment by mikenikles** [comment]
Hi everyone, I'm looking into this but haven't been able to reproduce it just yet.

Does anyone have a workspace ID you could share? Also, I wonder if it may be happening in the Europe region 🤔 (I connect to the US based on my location).

**Comment by jelaniwoods** [comment]
I'm located in the US.

Some workspace IDs are:
- cyan-kite-5pv8xjk4 
- teal-lemming-njnhd1ws
- olive-vicuna-o0b22ljz

**Comment by mikenikles** [comment]
Thank you @jelaniwoods 🙏.

A colleague of mine restarted one of the underlying systems. In his words, "I see activity now".

Could you all please check and see if you're back up and running?

**Comment by jelaniwoods** [comment]
@mikenikles Yes, my workspaces now start successfully!

**Comment by smacintyre** [comment]
@mikenikles No, The workspace start but with the default image and no prebuilds.

**Comment by aledbf** [comment]
@smacintyre prebuilds are being restarted now

**Comment by mikenikles** [comment]
☝️ he's the man of the hour 😄. Thank you @aledbf for getting us back up and running 🙏!

**Comment by smacintyre** [comment]
@mikenikles and @aledbf  Also ports are stuck in detecting and are unreachable I try open anything:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/361689/125707953-0bc84af0-9d75-40b8-b724-5d20ed4c04b6.png">

**Comment by smacintyre** [comment]
@mikenikles  and @aledbf Still not working, just tried again. The workspace loads but is unusable.

* The incorrect Docker image is being loaded to the workspace, ignoring what's specified in `.gitpod.yml`
* Prebuilds aren’t working, or even running commands from the `.gitpod.yml` isn't working when the workspace loads
* Ports can’t be opened – Even if you manually install the software and do your builds

**Comment by aledbf** [comment]
@smacintyre please post the name of the workspace

**Comment by smacintyre** [comment]
@aledbf This applies to every workspace I try to create new; it's 100% reproducible from what I am experincing. I just created a new one: blush-quail-venl89wf

**Comment by smacintyre** [comment]
Hi @aledbf -- any update on this? Acknowledgement or ETA? It's the start of the workday here in Asia, so I'm concerned about this blocking my team.

**Comment by mikenikles** [comment]
Hey Shawn, we see some long-running prebuilds but nothing that points to the cause of what you experience yet. Investigation is ongoing at the moment.

**Comment by smacintyre** [comment]
@mikenikles Thank you!

**Comment by mikenikles** [comment]
You're welcome - and my apologies for the unnecessary added stress to start your day!

Ports look fine from a monitoring perspective now. Do you still see them stuck?

As for the incorrect Docker image that is used, I wonder if it for whatever reason falls back to the default `gitpod/workspace-full`...

**Comment by smacintyre** [comment]
@aledbf and @mikenikles 

Here is our `.gitpod.yml`:

```yaml
image:
  file: .gitpod.Dockerfile
tasks:
  - command: yarn gitpod:start
    init: yarn gitpod:prebuild
github:
  prebuilds:
    addCheck: true
    addBadge: true
    addLabel: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
ports:
  - port:
      port: 3000
      onOpen: ignore
  - port:
      port: 4000
      onOpen: ignore
  - port:
      port: 8000
      onOpen: open-browser
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - csstools.postcss
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - AmazonWebServices.aws-toolkit-vscode
    - GraphQL.vscode-graphql
    - streetsidesoftware.code-spell-checker
```

**Comment by akosyakov** [comment]
Ports section does not look valid and all .gitpod.yml ignore. It should be:
```
ports:
  - port:3000
     onOpen: ignore
  - port: 4000
     onOpen: ignore
  - port: 8000
     onOpen: open-browser
```
