### ISSUE TITLE
init not working as expected with pre-build

### ISSUE THREAD

**Issue by jmcelreavey** [gitpod-io/gitpod#4838]
### Bug description

I currently have the following logic in place:

```
tasks:
  - before: |
      printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    prebuild: |
      docker-compose up -d
      yarn install
      yarn run database:migrate
    command: |
      docker-compose down
      docker network prune -f
      yarn run dev
```

This works perfectly, however, the documentation is telling me `prebuild` has been deprecated and I should replace it with `init` however when I do this it doesn't rebuild the init step, it runs during startup. 

### Steps to reproduce

Gitpod up the repository:
https://gitpod.io/#https://github.com/jmcelreavey/dev-job

### Expected behavior

I would expect the GitHub pre-build functionality to see the init and run it prior to me starting the workspace

### Example repository

https://github.com/jmcelreavey/dev-job

**Comment by faisal-m16** [comment]
Same Issue. When creating a new workspace with extension no task is running.

```yml
tasks:
  - name: Run Client
    before: cd client
    init: yarn install
    command: yarn start
    env:
      DANGEROUSLY_DISABLE_HOST_CHECK: true
    openMode: tab-after
  - name: Run Server
    init: npm install
    command: npm run server
    openMode: tab-after

vscode:
  extensions:
    - formulahendry.auto-close-tag
    - coenraads.bracket-pair-colorizer
    - pkief.material-icon-theme
    - eamodio.gitlens
    - usernamehw.errorlens
    - >-
      https://marketplace.visualstudio.com/_apis/public/gallery/publishers/eg2/vsextensions/tslint/1.0.47/vspackage

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 4000
    onOpen: ignore
    visibility: public
```
