### ISSUE TITLE
http://gitpod.ocp4.paco.com:30370/sorry#Please%20allow%20Cookies%20in%20your%20browser%20and%20try%20to%20log%20in%20again.

### ISSUE THREAD

**Issue by pacopeng** [gitpod-io/gitpod#4874]
### Bug description

git clone https://github.com/gitpod-io/gitpod
git checkout -b v0.9.0 v0.9.0

######values.yaml################
```
hostname: gitpod.ocp4.paco.com:30370
certificatesSecret:
  secretName: null
authProviders:
  - id: "Public-GitLab"
    host: "10.10.1.63"
    type: "GitLab"
    oauth:
      clientId: "5c0a41ba9205edfae440dbb28811a581e514697bd9ec8d5ed583c037aae90595"
      clientSecret: "1ae924f385dd2bf8c9e29c22ad938e4a9139a5f6ded5a821ea81d5992525debc"
      callBackUrl: "http://gitpod.ocp4.paco.com:30370/auth/10.10.1.63/callback"
      settingsUrl: "https://10.10.1.63/-/profile/applications"
    description: ""
    icon: ""

components:
  wsDaemon:
    containerRuntime:
      enabled: false
      nodeRoots:
      - /var/lib/kubelet/pods
  workspace:
    defaultImage:
      imagePrefix: "10.10.1.61:50002/gitpod/"
      imageName: "workspace-full"
    pullSecret:
      secretName: "registry-credit"
  imageBuilder:
    dindImage: 10.10.1.61:50002/docker:19.03-dind
    alpineImage: 10.10.1.61:50002/apine:latest
    selfBuildBaseImage: 10.10.1.61:50002/selfbuild:latest
    registryCerts: []
    registry:
      name: 10.10.1.61:50002/gitpod-ws
      secretName: "registry-credit"
    bypassProxy: true
  #registryFacade:
  #  disabled: true
  proxy:
  #  disabled: true
    ports:
      http:
        expose: true
    serviceType: "NodePort"
  #  initContainers:
  #    image: 
  #      registry:10.10.1.61:50002
  #      repositroy: apline
  #      tag: 3.13
  server:
    definitelyGpDisabled: "true"
  wsProxy:
    disabled: true
docker-registry:
  enabled: false
rabbitmq:
  fullnameOverride: "messagebus"
  image:
    registry: 10.10.1.61:50002
    repository: bitnami/rabbitmq
    tag: 3.8.14-debian-10-r0
  auth:
    username: paco
    password: paco12345678
minio:
  fullnameOverride: minio
  image:
    repository: 10.10.1.61:50002/minio/minio
    tag: RELEASE.2020-11-06T23-17-07Z
  accessKey: fDhEkcdeTb8Hq9VNbVJPEPFNZn6AVDAVX7hccu2y
  secretKey: fU6fm63LX4Pm64DRq9dr4nB55dr6NX9eYo8cP87Q
  persistence:
    enabled: false
mysql:
  #fullnameOverride: mysql
  image: 
    registry: 10.10.1.61:50002
    repository: bitnami/mysql
    tag: 8.0.25-debian-10-r37
  primary:
    persistence:
      enabled: false
      #storageClass: nfs-client
busybox:
  image:
    repository: 10.10.1.61:50002/busybox
    tag: 1.32
  persistence:
    enabled: false
#############

```
****
helm upgrade  --install -f .gitpod-config/values.custom-eu.yaml gitpod .  --set version=0.9.0

login page --worked
![image](https://user-images.githubusercontent.com/5043946/126271357-3d24b007-ba3a-4d92-ba61-20943dc88d28.png)

jumped to gitlab for authentication --worked
![image](https://user-images.githubusercontent.com/5043946/126271476-024a4917-34bc-41e8-b88b-38476113b831.png)

authorized with gitlab ----failed
once I clicked the "authorize" button , it will forward to the login page again with below error message 

![image](https://user-images.githubusercontent.com/5043946/126271687-662a1b83-f112-433b-874b-c82bc50378c1.png)

##########gitpod status ####################

please ignore this error "ws-daemon-nmd5s                                    0/2     Init:0/2 " , it seems not work for CRI-O , I have both CRI-O and Containerd for runtime . 
please ignore this error "image-builder-788dbcdd8-76r26                      2/3     CrashLoopBackOff   38". , since I use a private registry without https. 

![image](https://user-images.githubusercontent.com/5043946/126271980-be9ca854-d2db-47fe-a462-48e82000c978.png)

###########gitpod service status ######
![image](https://user-images.githubusercontent.com/5043946/126272371-67f8f026-5f65-4722-bb7c-76cd8b9b41e9.png)

##########added a DNS recored for githost hostname #############
10.10.1.66 gitpod.ocp4.paco.com

##########kubenetes status ######################
![image](https://user-images.githubusercontent.com/5043946/126272503-0b194e04-9e4a-4b93-91a8-7f7aab3fbac0.png)

### Steps to reproduce

Self-Hosted integrate with Self Hosted gitlab  
gitpod: v0.9.0
platform: kubenetes 1.21.1
gitlab: 1.3.11.2-ee

### Expected behavior

once authorized with gitlab  it will logged into the gitpod
