### ISSUE TITLE
Make `gp preview <url>` wait for `<url>` to be available

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#496]
It would be cool to make `gp preview <url>` wait for `<url>` before opening the preview.

Suggestions:
- Add `--wait-for-it` option to `gp preview`
- Or make waiting the default behavior for `gp preview` (see also #495)
- Or add `path` attribute to port specification

Use case:
- Create `.gitpod.yml` with a `tasks` entry that starts a server with its `command` (and maybe does some `init` first)
- Create a second `tasks` entry that waits for the server to be running, and then opens a given preview URL

Could look like this:

```yaml
tasks:
  - init: npm install
    command: npm start
  - openMode: split-right
    command: gp preview --wait-for-it $(gp url 3000)custom/page.html
```

Or like this:

```yaml
ports:
- port: 3000
  onOpen: open-preview
  path: /custom/page.html
```

**Comment by svenefftinge** [comment]
I believe having a default timeout of e.g. 60secs in `gp preview` would make sense. I.e. instead of wait-for-it we allow changing that default time-out?

Also allowing executing commands when a port opens seems nice:
```yaml
ports:
- port: 3000
  onOpen: gp preview http://localhost:3000/custom/page.html
```
