### ISSUE TITLE
.gitpod.yml not read, Custom Docker container not created

### ISSUE THREAD

**Issue by alxmhe** [gitpod-io/gitpod#4967]
### Bug description

I am unable to bootstrap my workspace with an initial setup from a Dockerfile.
When editing my fairly simple `.gitpod.yml`, I have this error:
```
Unable to load schema from 'https://gitpod.io/schemas/gitpod-schema.json': No content.
```

Here is the file :
```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn && yarn storybook

ports:
  - port: 6006
    onOpen: open-preview
```

Tasks and ports configurations are also not read, so I believe the problem would be with the `.gitpod.yml` file.

### Steps to reproduce

Clone repository from Github, add a .gitpod.yml and .gitpod.Dockerfile, terminate workspace, launch workspace.
The instructions in the Dockerfile are not used to bootstrap the workspace.

### Expected behavior

.gitpod.yml should be used to configure the workspace on boot.
