### ISSUE TITLE
Local Companion not working with self-hosted Gitpod Docker Image

### ISSUE THREAD

**Issue by bennothommo** [gitpod-io/gitpod#5019]
### Bug description

Per https://community.gitpod.io/t/local-companion-and-self-hosted-docker-image/4351/3.

When using a v0.10.0-1 Docker Image build of Gitpod, the Local Companion app does not seem to work. From what I can tell, the Oauth Authorize endpoint in the Docker Image either does not exist or is not configured to accept requests.

The following error is displayed on the browser window that is opened when running the Local Companion app:

![image](https://user-images.githubusercontent.com/15900351/127592221-0f3f766c-7d16-47fd-8982-c5c5074329b8.png)

### Steps to reproduce

1. Build and run Docker Image with Docker Compose - `docker-compose.yaml`

```
version: '3'
services:

  gitpod:
    image: eu.gcr.io/gitpod-core-dev/build/gitpod-k3s@sha256:b3280468152027221dfa109bf7c0753dd1dfec9bdd66057b076eb0b0890b336c
    privileged: true
    restart: unless-stopped
    volumes:
      - gitpod-docker:/var/gitpod/docker
      - gitpod-docker-registry:/var/gitpod/docker-registry
      - gitpod-minio:/var/gitpod/minio
      - gitpod-mysql:/var/gitpod/mysql
      - gitpod-workspaces:/var/gitpod/workspaces
      - ./values:/values
      - ./certs:/certs
    ports:
      - 443:443
      - 80:80
    environment:
      - DOMAIN=[your domain]

volumes:
  gitpod-docker:
  gitpod-docker-registry:
  gitpod-minio:
  gitpod-mysql:
  gitpod-workspaces:
```

2. Run Local Companion app with Gitpod host specified:

```
./gitpod-local-companion-linux --gitpod-host="[your domain]"
```

### Expected behavior

Local Companion app connects and allows for usage.

### Example repository

None.

### Anything else?

Please let me know if you need any further info to get this specific setup working.
