### ISSUE TITLE
Rust: Because of wrong modified timestamp cargo rebuilds every time

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#524]
**Describe the bug**
Between workspace restarts, the precision of the 'modified' timestamp on files under `/workspace` degrades from nanosecond to second precision.

As of now, `cargo` [relies on this timestamp](https://github.com/rust-lang/cargo/blob/fb35120644a3dc2a5c8d71f25db1a887876dca02/src/cargo/core/compiler/fingerprint.rs#L413) to detect dirty dependencies. The effect is that cargo rebuilds the whole project including all dependencies on each restart because it things the present artifacts are outdated.

**To Reproduce**
 1. Create new workspace
 2. `touch test`
 3. `stat test`
 4. Stop and restart workspace
 5. `stat test`

**Expected behavior**
Workspace should have identical timestamps after restart.

**Comment by svenefftinge** [comment]
Oh, could that be the reason why `cargo-watch` is constantly rebuilding a project?
See https://spectrum.chat/gitpod/general/rust-rocket-web-server-port-not-served~cf954a11-8b39-4979-9ebb-5b02949ddf63

**Comment by geropl** [comment]
No, that sounds like something different. I'll try it, though.

**Comment by geropl** [comment]
Oh, forgot about this one. Will verify and see if I can fix it.

**Comment by geropl** [comment]
Still the case, cmp. mtime here:
![image](https://user-images.githubusercontent.com/32448529/167125010-5a950d09-4462-4822-8fb0-bcc5e21c1559.png)

**Comment by axonasif** [comment]
Here's a workaround, use the following task structure in `.gitpod.yml`:

```yaml
tasks:
  - name: Build and run
    init: |
      cargo build

      # workaround for https://github.com/gitpod-io/gitpod/issues/524
      find target -exec stat --format='%.Y %n' {} + > /workspace/.ts

    command: |
      # workaround for https://github.com/gitpod-io/gitpod/issues/524
      while read -r ts file; do touch -d "@${ts}" "${file}"; done < /workspace/.ts

      cargo run
```
