### ISSUE TITLE
psql not working

### ISSUE THREAD

**Issue by M-Gonzalo** [gitpod-io/gitpod#5445]
### Bug description

I'm having an issue with my postgresql server, which won't start.
Message:

`createdb: error: could not connect to database template1: FATAL:  role "gitpod" does not exist`

### Steps to reproduce

sudo update && sudo apt install postgresql 
psql

### Expected behavior

postresql prompt

**Comment by ghuntley** [comment]
0. 👋
1. Can you please create a repository which replicates this?
2. Are you using your own Dockerfile?
3. What does your .gitpod.yml look like :)

**Comment by M-Gonzalo** [comment]
Hi! Sorry for the delay
1) How do I do that?
2) Nope.
3) gitpod.yml
```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: pushd api && npm i ; popd && pushd client && npm i ; popd
    command: 'echo "TODO: Replace with command to start project"'
  - init: cd api && npm start
```

.gitpod.Dockerfile: 
```
FROM gitpod/workspace-postgres

# Install custom tools, runtimes, etc.
# For example "bastet", a command-line tetris clone:
# RUN brew install bastet
#
# More information: https://www.gitpod.io/docs/config-docker/

```
