### ISSUE TITLE
Unable to load docker image hosted at Docker Hub

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/gitpod#547]
**Describe the bug**

Today I'm unable to create the intended Gitpod workspace from a `.gitpod.yml` pointing to a docker image hosted at Docker Hub. What happens instead is that the default Gitpod image is used in place of the original. 

Everything was working just fine until a couple of days ago, before the announcement that the transition period for early adopters to use private repositories is about to end.

Anyway, this condition doesn't apply to this context since the repository in question is **public**. 

**To Reproduce**

The repository is https://github.com/pattacini/technical-evaluation.

**Comment by pattacini** [comment]
It came out that `.gitpod.yml` contained the use of a tag that is not in production yet.
Rolling it back fixed the problem. Sorry for the noise I generated.

However, it would be good to notify somehow the presence of an error in the configuration file and only then pick up a default image as a fallback.

**Comment by kk86bioinfo** [comment]
I tried using gitpod/workspace-mysql via 3 ways below:
- Direct using image tag in .gitpod.yml
- Using image file tag and defind in .gitpod.Dockerfile
- Using gp init and change only in .gitpod.Dockerfile 

All above still using default image. Kindly assist.

**Comment by jankeromnes** [comment]
@pattacini Thanks for the feedback! And sorry about the confusion. I agree that Gitpod should give much more direct feedback when there is a problem with your Dockerfile (not detected because of typo in file name, or Docker syntax problem, etc.)

@kk86bioinfo Could you please share your repository URL? (If it's public of course.) Normally, this is how you would install MySQL in your project:

1. Add `image: gitpod/workspace-mysql` in your `.gitpod.yml` file (please be careful with typos in that file name, as otherwise it won't be detected)
2. Add and commit the `.gitpod.yml` file, and push it to your repository
3. Open your repository in Gitpod again, creating a new workspace
4. The new workspace should have `mysql` installed

Please let me know if that doesn't work.

**Comment by kk86bioinfo** [comment]
Hi @jankeromnes ,

![image](https://user-images.githubusercontent.com/2483401/70485172-25cca880-1b29-11ea-8850-c6c1876b6e14.png)

I have tried with that but still getting default image loaded instead of mysql image. 

Kindly assist. Thank you.

**Comment by kk86bioinfo** [comment]
```
image: gitpod/workspace-mysql

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
    command: composer install -d /workspace/gitpod-playground/src
    command: cd /workspace/gitpod-playground/src && npm install
    command: echo 'Building application DONE!'

```

**Comment by kk86bioinfo** [comment]
@jankeromnes ,
I think I figure out why it failed. I have using multiple commands in tasks. The following seems working fine.

```
image: gitpod/workspace-mysql

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - command: composer install -d /workspace/gitpod-playground/src
  - command: cd /workspace/gitpod-playground/src && npm install
  - command: echo 'Building application DONE!'

```
