### ISSUE TITLE
[self-hosted][v.0.10.0] builtin registry reverse proxy is not right. 

### ISSUE THREAD

**Issue by hgye** [gitpod-io/gitpod#5491]
### Bug description

I'm using non-default kubedomain.

Try to access builtin registry, it will failed with 
>
>HTTP/1.1 502 Bad Gateway
>Content-Length: 0
>Date: Thu, 02 Sep 2021 02:59:21 GMT
>Server: Caddy

And logs from proxy container

```yaml
{
  "level": "error",
  "ts": 1630551561.3087926,
  "logger": "http.log.error.log2",
  "msg": "dial tcp: lookup registry.gitpod.svc.cluster.local on 169.254.25.10:53: no such host",
  "request": {
    "remote_addr": "172.16.10.11:59782",
    "proto": "HTTP/1.1",
    "method": "GET",
    "host": "registry.gitpod.himix.io",
    "uri": "/",
    "headers": {
      "User-Agent": [
        "HTTPie/2.4.0"
      ],
      "Accept-Encoding": [
        "gzip, deflate"
      ],
      "Accept": [
        "*/*"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Authorization": [
        "Basic Z2l0cG9kOmdpdHBvZA=="
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "http/1.1",
      "proto_mutual": true,
      "server_name": "registry.gitpod.himix.io"
    }
  },
  "duration": 0.211602697,
  "status": 502,
  "err_id": "4v9xi6n72",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:861)"
}
```

### Steps to reproduce

I'm trying to install gitpod self-hosted service via helm, verison 0.10.0, my values.custom.yaml as below:
```yaml
hostname: gitpod.my-company.domain
imagePrefix: core.harbor.my-company.domain/gitpod-io/self-hosted/
installation:
  kubedomain: "svc.my-company.cluster.local"
rabbitmq:
  clusterDomain: my-company.cluster.local
  auth:
    username: my-company
    password: b0ec4b8c4a94495ec3b5662a06e8e775b0a075262e7dd0a99756dec5769a0e69
  extraEnnVars:
    - name: RABBITMQ_NODE_NAME
      value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.my-company.cluster.local"
    - name: K8S_HOSTNAME_SUFFIX
      value:  ".$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.my-company.cluster.local"
minio:
  accessKey: 637e76c8bc1c343828d1eb92af1e40860bd3e0186b0533e6ddb95f206910d96a
  secretKey: 01b1e5a4a7f6d49525a4c83cde9085e41f118a7c9f2bbac53eba2297f800fd2c
components:
  agentSmith:
    disabled: true

  wsDaemon:
    containerRuntime:
      nodeRoots:
        - /run/containerd/io.containerd.runtime.v2.task/k8s.io

  # server:
  #   defaultBaseImageRegistryWhitelist:
  #     - "core.harbor.my-company.domain"

  proxy:
    loadBalancerIP: 172.16.10.48

  # imageBuilder:
  #   bypassProxy: true
  #   registryCerts: []
  #   registry:
  #     # name must not end with a "/"
  #     name: core.harbor.my-company.domain/gitpod
  #     secretName: image-builder-registry-secret
  #     # baseImageName: "core.harbor.my-company.domain/gitpod/workspace-base"
  #     # workspaceImageName: "core.harbor.my-company.domain/gitpod/workspace-full"
  #     # path: secrets/registry-auth.json

  # workspace:
  #   pullSecret:
  #     secretName: image-builder-registry-secret
  #   defaultImage:
  #     imagePrefix: "core.harbor.my-company.domain/gitpod/"

docker-registry:
  enabled: true
  authentication:
    username: gitpod
    password: gitpod
```

after installation. I find configmap proxy-config are still using svc.cluster.local instead of svc.my-company.cluster.local
```
apiVersion: v1
data:
  vhost.docker-registry: |
    https://registry.{$GITPOD_DOMAIN} {
      import enable_log
      import remove_server_header
      import ssl_configuration

      basicauth bcrypt "Docker Registry" {
        gitpod JDJhJDEwJGF4bUxISFhFQ0RaaXU2TnNJNzdqN3VVclZUYTFGWUpHUGZNQk9tanpYTXRHRDg4N1RmbmZh
      }

      reverse_proxy https://registry.gitpod.svc.cluster.local {
        flush_interval -1
        transport http {
          tls_trusted_ca_certs /etc/caddy/registry-certs/ca.crt
        }
      }
    }
  vhost.empty: |
    # Placeholder to avoid errors loading files using a glob pattern
  vhost.minio: |
    https://minio.{$GITPOD_DOMAIN} {
      import enable_log
      import remove_server_header
      import ssl_configuration

      reverse_proxy minio.gitpod.{$KUBE_DOMAIN}:9000 {
        flush_interval -1
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2021-09-02T01:34:17Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    chart: gitpod-0.10.0
    heritage: Helm
    release: gitpod
  name: proxy-config
  namespace: gitpod
  resourceVersion: "56022025"
  uid: 61467ddb-d4c2-477e-af12-fe464c7001b9
```

### Expected behavior

I can see
```
     reverse_proxy https://registry.gitpod.svc.cluster.local 
```
I think it should be      

```reverse_proxy https://registry.gitpod.svc.{kubedomain} ```

I'm also check helm template, I can see file
chart/templates/_helpers.tpl
```
{{- define "gitpod.builtinRegistry.name" -}}
{{- if .Values.components.imageBuilder.registry.bypassProxy -}}
{{ include "gitpod.builtinRegistry.internal_name" . }}
{{- else -}}
registry.{{ .Values.hostname }}
{{- end -}}
{{- end -}}

{{- define "gitpod.builtinRegistry.internal_name" -}}
{{- $ := .root -}}
{{- $gp := .gp -}}
{{ index .Values "docker-registry" "fullnameOverride" }}.{{ .Release.Namespace }}.{{ $gp.installation.kubedomain | default "svc.cluster.local" }}
{{- end -}}
```
file chart/templates/proxy-configmap.yaml
```
    https://registry.{$GITPOD_DOMAIN} {
      import enable_log
      import remove_server_header
      import ssl_configuration

      basicauth bcrypt "Docker Registry" {
        {{ .username }} {{ bcrypt .password | b64enc }}
      }

      reverse_proxy https://{{ include "gitpod.builtinRegistry.internal_name" . }} {
        flush_interval -1
        transport http {
          tls_trusted_ca_certs /etc/caddy/registry-certs/ca.crt
        }
      }
    }
{{- end }}
```

So I think the template are right. But why configmap proxy-config are not expected?

**Comment by hgye** [comment]
By now, does it any workaround to fix this problem?

**Comment by corneliusludmann** [comment]
I think the only option you have right now is to download the charts from the 0.10.0 release, path them, and run helm with your local patched charts. You could try to hard-code your registry hostname in `chart/templates/proxy-configmap.yaml` until we figured out what went wrong.

**Comment by roboquat** [comment]
@csweichel: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5491#issuecomment-912357799):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5491#issuecomment-912357811):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5491#issuecomment-912358117):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hgye** [comment]
@corneliusludmann 
When I using a local helm to upgrade my gitpod, I get following errors again:
```yaml=
{
  "level": "error",
  "ts": 1630924968.2532775,
  "logger": "http.log.error.log2",
  "msg": "x509: certificate is valid for registry.gitpod.svc.cluster.local, not registry.gitpod.svc.my-company.cluster.local",
  "request": {
    "remote_addr": "172.16.10.12:59056",
    "proto": "HTTP/1.1",
    "method": "GET",
    "host": "registry.gitpod.my-company.domain",
    "uri": "/",
    "headers": {
      "User-Agent": [
        "HTTPie/2.4.0"
      ],
      "Accept-Encoding": [
        "gzip, deflate"
      ],
      "Accept": [
        "*/*"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Authorization": [
        "Basic Z2l0cG9kOmdpdHBvZA=="
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "http/1.1",
      "proto_mutual": true,
      "server_name": "registry.gitpod.my-company.domain"
    }
  },
  "duration": 0.006369996,
  "status": 502,
  "err_id": "p413f654w",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:861)"
}
```

Any idea?
