### ISSUE TITLE
[Feature request] open-preview support suffix

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5663]
I am doing lots of graphql-server on gitpods 

My current config is
```yml
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
```

But it's quite inconvenient, because you usually open `baseurl\graphql` to test schema.
I am wondering we can add a new field for such 

Thx. Great experience with backend development with gitpods.
