### ISSUE TITLE
Database not persistent in between runs (gitpod self-hosted inside docker)

### ISSUE THREAD

**Issue by timon-schelling** [gitpod-io/gitpod#5666]
Dear all,

first, thanks for creating this awesome tool.

### Bug description

The default mysql database seems to be none persistent in between runs (gitpod self-hosted inside docker).

This is indicated by the following error on the gitpod main page:

```
Error: Request getLoggedInUser failed with message: ER_NO_SUCH_TABLE: Table 'gitpod.d_b_user' doesn't exist
    at main.js:449
```

Gitpod works perfectly fine after first startup with a `docker-compose.yml` that looks something like this:

```
version: "3.3"

services:

    gitpod:
        container_name: gitpod
        hostname: gitpod
        restart: always
        image: gcr.io/gitpod-io/self-hosted/gitpod-k3s
        privileged: true
        dns:
          - 1.1.1.1
        volumes:
          - './gitpod/certs:/certs'
          - './gitpod/data/docker:/var/gitpod/docker'
          - './gitpod/data/docker-registry:/var/gitpod/docker-registry'
          - './gitpod/data/minio:/var/gitpod/minio'
          - './gitpod/data/mysql:/var/gitpod/mysql'
          - './gitpod/data/workspaces:/var/gitpod/workspaces'
        ports:
          - 444:443
          - 80:80
        environment:
          DOMAIN: gitpod.example.com
```
(and certs in place)

But after a restart or recreation with the same `docker-compose.yml` and without modifying the mount (volume) directories, loading any gitpod page fails with the mentioned error.

```
Error: Request getLoggedInUser failed with message: ER_NO_SUCH_TABLE: Table 'gitpod.d_b_user' doesn't exist
    at main.js:449
```

The directories used to mount gitpod's persistent volumes (https://github.com/gitpod-io/gitpod/blob/main/contrib/docker/README.md):

- `/var/gitpod/docker`
- `/var/gitpod/docker-registry`
- `/var/gitpod/minio`
- `/var/gitpod/mysql`
- `/var/gitpod/workspaces`

Are all mounted correctly. Manual read and writes from within the container and from the host work as expected and while running the first time, the volumes: 

- `/var/gitpod/docker`
- `/var/gitpod/docker-registry`
- `/var/gitpod/minio`
- `/var/gitpod/workspaces`

are filled as expected, but `/var/gitpod/mysql` is not and stays empty.

On the host:
```
/> ls ./gitpod/data/*

./gitpod/data/docker:
XXXXXX.XXXXXX

./gitpod/data/docker-registry:
docker

./gitpod/data/minio:
gitpod-user-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

./gitpod/data/mysql:

./gitpod/data/workspaces:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX-daemon
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX .workspace.json
```

And inside the container:
```
/> ls /var/gitpod/*

/var/gitpod/docker:
XXXXXX.XXXXXX

/var/gitpod/docker-registry:
docker

/var/gitpod/minio:
gitpod-user-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

/var/gitpod/mysql:

/var/gitpod/workspaces:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX-daemon
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX .workspace.json
```

The persistent volume is there and used by the mysql instance.  

```
/> kubectl get pv

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   REASON   AGE
docker-registry                            50Gi       RWO            Retain           Bound    default/docker-registry   manual                  13h
minio                                      50Gi       RWO            Retain           Bound    default/minio             manual                  13h
mysql                                      8Gi        RWO            Retain           Bound    default/mysql             manual                  13h
pvc-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX   8Gi        RWO            Delete           Bound    default/data-mysql-0      local-path              12h
```

```
/> kubectl describe pv pvc-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX 

Name:              pvc-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX 
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: rancher.io/local-path
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      local-path
Status:            Bound
Claim:             default/data-mysql-0
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          8Gi
Node Affinity:     
  Required Terms:  
    Term 0:        kubernetes.io/hostname in [gitpod]
Message:           
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/k3s/storage/pvc-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX _default_data-mysql-0
    HostPathType:  DirectoryOrCreate
Events:            <none>
```

```
/> ls /var/lib/rancher/k3s/storage/pvc-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_default_data-mysql-0/*

auto.cnf    ca.pem           client-key.pem  gitpod@002dsessions  ib_logfile0  ibdata1  my_database  mysql_upgrade_info  private_key.pem  server-cert.pem  sys
ca-key.pem  client-cert.pem  gitpod          ib_buffer_pool       ib_logfile1  ibtmp1   mysql        performance_schema  public_key.pem   server-key.pem
```

### Steps to reproduce

Create `docker-compose.yml` that looks something like this:

```
version: "3.3"

services:

    gitpod:
        container_name: gitpod
        hostname: gitpod
        restart: always
        image: gcr.io/gitpod-io/self-hosted/gitpod-k3s
        privileged: true
        dns:
          - 1.1.1.1
        volumes:
          - './gitpod/certs:/certs'
          - './gitpod/data/docker:/var/gitpod/docker'
          - './gitpod/data/docker-registry:/var/gitpod/docker-registry'
          - './gitpod/data/minio:/var/gitpod/minio'
          - './gitpod/data/mysql:/var/gitpod/mysql'
          - './gitpod/data/workspaces:/var/gitpod/workspaces'
        ports:
          - 444:443
          - 80:80
        environment:
          DOMAIN: gitpod.example.com
```
and place certs for `gitpod.example.com` at `./gtipod/certs`.

Run `docker-compose up` or `docker-compose up -d`.

Open a browser and go to `gitpod.example.com` and complete gitpod setup.

Stop and remove container to example with `docker-compose down`.

Recreate container to example with `docker-compose up` or `docker-compose up -d`.

Open a browser and go to `gitpod.example.com`.

The following error should accrue:

```
Error: Request getLoggedInUser failed with message: ER_NO_SUCH_TABLE: Table 'gitpod.d_b_user' doesn't exist
    at main.js:449
```

### Expected behavior

When gitpod's persistent volumes (https://github.com/gitpod-io/gitpod/blob/main/contrib/docker/README.md):

- `/var/gitpod/docker`
- `/var/gitpod/docker-registry`
- `/var/gitpod/minio`
- `/var/gitpod/mysql`
- `/var/gitpod/workspaces`

are preserved between runs, gitpod should be in the same state after a restart, should work like before.

### Anything else?

While trying to solve the issue by myself, I stumbled over these lines in the image's `entrypoint.sh`
https://github.com/gitpod-io/gitpod/blob/2c70b97ac1ed5b5ec8856e49f5c0551637a37092/contrib/docker/gitpod-image/entrypoint.sh#L42
https://github.com/gitpod-io/gitpod/blob/2c70b97ac1ed5b5ec8856e49f5c0551637a37092/contrib/docker/gitpod-image/entrypoint.sh#L43

Is there the possibilities that a similar thing cloud fix this?
