### ISSUE TITLE
.gitpod.yml will not run

### ISSUE THREAD

**Issue by andrisole92** [gitpod-io/gitpod#5761]
### Bug description

Hi there,

So I need to install Ruby 3 and npm dependencies automatically, maybe even run the server. I have the following `.gitpod.yml` in the root directory, but it will not run.

```
tasks:
  - name: Install Ruby 3
    init: rvm install ruby-3.0.0
    command: >
      rvm default ruby-3.0.0
      rvm use ruby-3.0.0
      gp sync-done ruby3
  - name: Run Bundle && Start Rails Server
    init: >
      gp sync-await ruby3
      bundle
    command: rails s
  - name: Run Yarn
    init: yarn install --check-files
`````

### Steps to reproduce

Please see above.

### Expected behavior

I am opening workspace and having ruby-3.0.0 installed as well as all other tasks finished running (or at least start executing)

### Anything else?

Many thanks, Andrey

**Comment by akosyakov** [comment]
I have not tried yaml file, probably there is some parsing issue. But to install tools is better to use Dockerfile not tasks: https://www.gitpod.io/docs/config-docker

Please see https://www.gitpod.io/docs/languages/javascript#node-versions and https://www.gitpod.io/docs/languages/ruby#ruby-versions

**Comment by lechien73** [comment]
I am having a similar issue. The `init_tasks.sh` file runs when the workspace is initialised, but the `command` task does not run when it is restarted.

```
image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
```
