### ISSUE TITLE
Use GitHub Discussions instead of `community.gitpod.io`

### ISSUE THREAD

**Issue by HonkingGoose** [gitpod-io/gitpod#5808]
## Problem

The `community.gitpod.io` site requires a new account.
I don't like having many accounts for things like this. I would much prefer to be able to use my GitHub account to get help. 😉 

## Proposed solution:

I would like this project to use the GitHub Discussions feature, instead of using a separate site.
Learn more about GitHub discussions in the official GitHub docs: https://docs.github.com/en/discussions

You can move issues to a discussion, or create a new issue based on a discussion.
This means that the support work and the related issues now live together.

You can add a link to the GitHub discussions for the Gitpod program in all your repositories, by adding a `contact_links` entry to the `config.yml` file in: `.github/ISSUE_TEMPLATE/config.yml` in each repository.

A example from Renovate bot: https://github.com/renovatebot/renovate/blob/main/.github/ISSUE_TEMPLATE/config.yml

```yaml
blank_issues_enabled: false
contact_links:
  - name: Start a discussion (config, doubts, docs)
    url: https://github.com/renovatebot/renovate/discussions/new
    about: If you have any questions about bot configuration or doubts about whether you should create a feature request or bug report, or have problems with the documentation please click here to create a Discussion instead of an Issue.
```

To see how a big project uses discussions, see: https://github.com/renovatebot/renovate/discussions

## Discussion:

Maybe this idea has been proposed internally already, and maybe you have good reasons to keep things as they are.
I searched for "discussions" on the issues, and couldn't find anything that seemed related.

I don't mean to be rude or to force you into anything. If you're happy with the current setup, please close the issue. 😉
