### ISSUE TITLE
Prebuild doesn't execute after restarting terminal

### ISSUE THREAD

**Issue by rajin100000** [gitpod-io/gitpod#5883]
### Bug description

I was gonna install java using sdk and I didn't want to install it everytime I open the workspace. That's why I have written a `.gitpod.yml` file in root of my workspace. Here is the file:-
```Yaml
tasks:
  - name: Install Java
    command: sdk install java 17-open
```

But the sdk version is not the latest, that's why I have added a new line in the file:
```Yaml
tasks:
  - name: Install Java
    command:
      sdk update &&
      sdk install java 17-open
```
But we need to restart our terminal after updating SDKMAN. I searched in google and knew that `bash` command restarts the terminal. That's why I updated the code:
```Yaml
tasks:
  - name: Install Java
    command:
      sdk update &&
      bash &&# Also used exec bash but both didn't work :(
      sdk install java 17-open
```
But it only executes the first part of command and never executes the part after `bash` or `exec bash`. So, please fix this issue or help me if I'm doing something wrong.

### Steps to reproduce

I noticed that prebuild never runs program if I restarts terminal at middle of command.
