### ISSUE TITLE
[vscode] editor opens with uninitialized git repository

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5892]
Feedback through email:
"""
One thing I did notice is that sometimes it also opens up, and seems like things are fine, but Source Control says that I don't have a git repository initialized yet.  If I reload the page, that problem resolves and everything loads up as expected, with the correct information in the Source Control tab.  This reload sometimes also opens up some prompts and information tabs for some extensions, like the IDE opened, but it wasn't fully initialized yet, and the reload forces the state of the browser to catch up to the state of the environment.  This is when using the VS Code option that is not 'LATEST'.
"""

**Comment by akosyakov** [comment]
We need more info to act on that. His frontend logs, workspace id if possible.

**Comment by bwklein** [comment]
Example: https://orange-thrush-ew0nnwto.ws-us18.gitpod.io/

How the Source Providers tab looks at first.

![image](https://user-images.githubusercontent.com/12104446/135141080-0a2a8d85-ab4a-4148-9e24-2461412f425d.png)

Switching back to the SP tab after the command completes and the server is running.

![image](https://user-images.githubusercontent.com/12104446/135141150-1a1c33ea-bf82-45cd-855d-dc783e5e247a.png)

All of the Gitpod options are greyed out in the File menu.

![image](https://user-images.githubusercontent.com/12104446/135141226-7e779571-fc52-4c98-814a-ff7013381f20.png)

This is my .gitpod.yml file.

```
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal 1
    init: npm install
    command: hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

ports:
  - port: 1313
    onOpen: open-browser  

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode@2.8.4
    - budparr.language-hugo-vscode@1.2.0
    - dendron.dendron-markdown-preview-enhanced@0.10.11
    - robole.markdown-snippets@0.6.0
    - GrapeCity.gc-excelviewer@2.1.35
    - aaron-bond.better-comments@2.1.0
    - dendron.dendron-paste-image
```

This is the .gitpod.Dockerfile 

```
FROM ubuntu:latest

ENV HUGO_VERSION 0.76.4
ENV HUGO_BINARY hugo_extended_${HUGO_VERSION}_Linux-64bit.deb

ARG asciidoctor_version=2.0.10
ARG asciidoctor_pdf_version=1.5.3

ENV ASCIIDOCTOR_VERSION=${asciidoctor_version} \
  ASCIIDOCTOR_PDF_VERSION=${asciidoctor_pdf_version}

ENV TZ America/Chicago
ENV DEBIAN_FRONTEND noninteractive

RUN apt update \
  && apt --no-install-recommends -y install \
  git ruby-full build-essential cmake zlib1g-dev \
  bison flex jpegoptim optipng ghostscript default-jre \
  graphicsmagick graphicsmagick-imagemagick-compat \
  graphicsmagick-libmagick-dev-compat graphviz lsyncd \
  libffi-dev libxml2-dev libgdk-pixbuf2.0-dev \
  libcairo2-dev libpango1.0-dev fonts-lyx python3-pip \
  plantuml wget curl

# Install Node.js and npm

RUN curl -sL https://deb.nodesource.com/setup_13.x | bash - \
  && apt-get install --no-install-recommends -y nodejs

# Installing Ruby Gems needed in the image
# including asciidoctor itself

RUN gem install --no-document \
  "asciidoctor:${ASCIIDOCTOR_VERSION}" \
  asciidoctor-bibtex \
  asciidoctor-confluence \
  asciidoctor-diagram \
  asciidoctor-mathematical \
  asciimath \
  "asciidoctor-pdf:${ASCIIDOCTOR_PDF_VERSION}" \
  asciidoctor-revealjs \
  asciidoctor-html5s \
  coderay \
  haml \
  pygments.rb \
  prawn-gmagick \
  rake \
  rghost \
  rouge \
  slim \
  thread_safe \
  tilt

# Installing Python dependencies for additional
# functionnalities as diagrams or syntax highligthing
RUN pip3 install --no-cache --upgrade pip setuptools wheel \
  && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
  && pip install --no-cache-dir \
  actdiag \
  'blockdiag[pdf]' \
  msal \
  nwdiag \
  Pygments \
  requests \
  seqdiag \
  pypdf2

# Install HUGO

RUN wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY} \
  &&  dpkg -i ${HUGO_BINARY} \
  &&  rm -r ${HUGO_BINARY}

RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod
RUN mkdir -p /builds/thunderheadeng/web
RUN ln -s /workspace/support /builds/thunderheadeng/web/support
RUN chown -R gitpod:gitpod /builds

```

Please let me know if there is anything else I can provide.
