### ISSUE TITLE
port ignore is not working as expected

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#5929]
### Bug description

I have this config:

```yaml
# Ports to expose on workspace startup
ports:
  - port: 3000-3379
    onOpen: ignore
  - port: 3380
    onOpen: open-browser
  - port: 3381-32000
    onOpen: ignore
```

![image](https://user-images.githubusercontent.com/1100969/135327260-1e2b36af-2b78-4ea6-a101-27a1dfec1612.png)

In I don't expect to see that message boxes like they are visible for that ignored ports

### Steps to reproduce

use the yaml and have a service that open ports in the ignored space

### Expected behavior

see decs
