### ISSUE TITLE
gp sync-await for init commands

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#5930]
If you are building complex init / command preBuild jobs it getting tricky to handle all cases that can happen.

1. init is started parallel to command (because no prebuild available and user click on without prebuild)
2. preBuild is available

To handle this I have at the moment the following code that is not nice:

```yaml
tasks:
  - name: Dependencies
    init: |
      #.... doing INIT stuff
      touch /workspace/.installDone

  - name: Create things that can not be done in init
    command: |
      printf "Wait for finish of init: ."; until [ -f /workspace/.installDone ]; do printf "."; sleep 5; done
```

It would be great if just all task with it names (example above "Dependencies")
are available for gp sync-await Dependencies.

**Comment by jankeromnes** [comment]
Thanks for the useful feedback!

A potential workaround here could be to add an awaiting `init` task the the second `command`, e.g. like so:

```yml
tasks:
  - name: Dependencies
    init: |
      #.... doing INIT stuff
      gp sync-done init

  - name: Create things that can not be done in init
    init: gp sync-await init
    command: |
      #.... doing other stuff
```

I think this should handle all cases well (e.g. prebuild vs no prebuild).

**Comment by konne** [comment]
@jankeromnes thanks for that idea. I will try
I didn't get the idea from the docu to have an init & command in one block.
So it would be great if you can maybe add some more docu around using of those prebuild tasks.

**Comment by jankeromnes** [comment]
@konne Aha, in this case, you could also simplify like this:

```yml
tasks:
  - name: Everything
    init: |
      #.... doing INIT stuff
    command: |
      #.... doing other stuff
```

Then there is no need to synchronize. 🙂

>  So it would be great if you can maybe add some more docu around using of those prebuild tasks.

Good point. Which docs did you look at specifically? (I ask because https://www.gitpod.io/docs/getting-started#init-script seems to have an example with both a `init` and a `command` for the same terminal)

**Comment by konne** [comment]
@jankeromnes
yes. I can confirm your solution is perfectly working.

I have another use case if the wait could be even on the task level.
I fully install another shell and make adjustments for configs,...
```yaml
 - name: Create .env file
    init: gp sync-await init
    command: |
      # copy default configs for home dir
      cp -r .gitpod/HOME/.  ~/
      sudo chsh -s /usr/bin/zsh
      # create .env file from ENV Variable
      echo $VARIABLE | sed 's/||/\n/g' >.env
      gp sync-done prepenv
      exit
  - name: Start app
    command: |
      gp sync-await prepenv
      npm run start
```

The issue for me is now, that the second terminal is already opened in the beginning and so my changes to the
shell and other stuff is not applied.

My Idea is to have something like:

```
tasks:
   - name: preTask
      command: gp async-done init
   - name: late
      async-wait: init
```

thx
