### ISSUE TITLE
Allow prebuilds for specific branches

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#5936]
In the `.gitpod.yml`, we have the following option to enable prebuilds on all branches:

```yaml
github:
  prebuilds:
    branches: true
```

I would like more granularity either through a regex, an array of branch names or a combination of the two.

_Regex_
```yaml
github:
  prebuilds:
    branches: feature/*
```

_Branch names_
```yaml
github:
  prebuilds:
    branches:
      - main
      - gp-code
```

_Combination of regex & array_
```yaml
github:
  prebuilds:
    branches:
      - main
      - gp-code
      - feature/*
```

A good use case is https://github.com/gitpod-io/openvscode-server. Prebuilds run for the `main` branch, but not `gp-code`. The repo has 263 branches, for all but `main` and `gp-code` we don't need prebuilds.
