### ISSUE TITLE
Is there any way to open an empty bash

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#5942]
Is there any way to open an empty bash instead of the last mentioned tab in gitpod.yml?

![image](https://user-images.githubusercontent.com/69431456/135382301-933bc0d7-79b9-413a-83a0-a5856ccc10ff.png)

It would be great if `bash` is opened instead of `Dev Server: node`

My config

```yml
image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup
    init: >
      yarn --network-timeout 100000;
      cp .env.example .env;
      echo "BASE_URL=\"$(gp url 3000)\"" >> .env;
      yarn prisma:migrate;
      yarn prisma:seed;
      yarn prepare;
      gp sync-done setup;
    command: yarn codegen:graphql --watch
  - name: Hardhat Node
    init: gp sync-await setup
    command: npx hardhat node
  - name: Prisma Studio
    init: gp sync-await setup
    command: BROWSER=none yarn prisma studio
  - name: Dev Server
    before: redis-server &
    init: gp sync-await setup
    command: >
      npx hardhat run scripts/deploy.js --network localhost;
      yarn dev;

ports:
  - port: 3000 # Web app
    onOpen: open-preview
    visibility: public
  - port: 5555 # Prisma Studio
    onOpen: ignore
    visibility: public
  - port: 8545 # Hardhat Node
    onOpen: ignore
    visibility: public
  - port: 6379 # Redis
    onOpen: ignore
  - port: 3306 # MySQL
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - github.github-vscode-theme
    - gitlab.gitlab-workflow
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - editorconfig.editorconfig
    - pkief.material-icon-theme
```
