### ISSUE TITLE
Make "ignore" for ports consistent 

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#600]
This will expose all ports and do nothing when a port opens.
```yaml
 - port: 1234
   onOpen: ignore
 - port: 1235
   onOpen: ignore
 - port: 1236
   onOpen: ignore
```

This will *not* expose any port and do nothing when a port opens.
```yaml
 - port: 1234-1236
   onOpen: ignore
```

Earlier discusssion: https://github.com/gitpod-io/gitpod/issues/245#issuecomment-490120252

It would be nice if the semantics from `ignore` would be the same for individual ports and port-ranges.
