### ISSUE TITLE
[Installer]: uninstallation

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6290]
In Helm, you can uninstall an application with `helm uninstall <name>`. The Installer should have a `gitpod-installer uninstall` command - this must work whether the application has been installed via `render` or (the future) `install` command.

We may be able to achieve this by storing the top part of the rendered YAML in a ConfigMap: eg
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
```

I think this is enough for `kubectl delete -f -` to be able to delete the KubeObjects
