### ISSUE TITLE
[Installer]: allow custom config to be entered into Helm dependencies

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6292]
Whilst this might seem counterintuitive on the face of it, I think that the number of different options we would otherwise have to support would make it limiting. Suggest adding a `helm` object underneath the config and passing data in as-is. For instance:

```yaml
containerRegistry:
  inCluster: true
  helm: {}
```
