### ISSUE TITLE
Make Gitpod prebuilds show up as GitHub Status checks

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6450]
Q: “How do I get gitpod prebuilds to show up in my git commit checks?”

![E320DD41-D4F6-4A5B-9A35-C9364E5F84B7](https://user-images.githubusercontent.com/127353/139402802-35ebd398-f1fc-42c6-9916-04fee8fd0a12.png)

**Comment by ghuntley** [comment]
Have asked for more information. I think `addcheck: true` should be changed to be the default behaviour.

**Comment by schickling** [comment]
Facing the same problem here: https://github.com/contentlayerdev/contentlayer/blob/main/.gitpod.yml

```yml
tasks:
  - init: yarn install && yarn build && yarn examples:postinstall
github:
  prebuilds:
    addCheck: true
```

Doesn't show up in the checks:

![CleanShot 2021-11-01 at 09 29 14](https://user-images.githubusercontent.com/1567498/139643622-26ad9796-8998-4067-a174-9d74f935c2f5.gif)

However it seems to be working in the Gitpod dashboard:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/1567498/139643734-b0ccb051-da17-4750-abba-5495179d2fb1.png">

Am I missing something?
