### ISSUE TITLE
Can't set PYTHONPATH env through terminal.integrated.env.* settings

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod#6561]
### Bug description

PYTHONPATH env is a general way to let python import modules in custom locations.
When setting terminal environments variables through VSCode by adding key "terminal.integrated.env.linux" to settings.json, other environment variables work as expected. The PYTHONPATH env seems to be reset right before starting the terminal.

### Steps to reproduce

1. Open any workspace [whether the gitpod/workspace_full image, or images like python]
2. add the following to project_folder/.vscode/settings.json
    ```yml
      "terminal.integrated.env.linux": {
          "MY_ENV": "VALUE",
          "PYTHONPATH": "123"
      },
    ```
3. Open a new terminal to verify those changes, 
    ```bash
    echo $MY_ENV
    echo $PYTHONPATH
    ```
    and found that PYTHONPATH is not set while MY_ENV is set as expected.

> 

### Expected behavior

Expecting PYTHONPATH is set as expected.
