### ISSUE TITLE
NodePort does not work

### ISSUE THREAD

**Issue by yusufali94** [gitpod-io/gitpod#6675]
### Bug description

I am hosting on a cluster with no LoadBalancer capabilities. I am trying to install using NodePort. Version 0.10.0

when I run a curl onto this port, `curl http://myIP:30370`, it responds back with connection refused. All the pods are running, nothing is in failure

See values.yaml
```
hostname: myIP:30370
proxy:
    serviceType: "NodePort"
    ports:
      http:
        expose: true
        nodePort: 30370
```
