### ISSUE TITLE
[installer] mysql helm global.storageClass may need to be set

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/gitpod#6789]
I set a default storage class:

```
kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

minio and registry respect that. mysql does not. In the Bitnami Helm chart the option is: 

`global.storageClass` and by default its `nil`

When we render it down we might have to give it a value?

**Comment by metcalfc** [comment]
I tried adding a `StorageClassName` on the `volumeClaimTemplates`:
```
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: mysql
          app.kubernetes.io/instance: MySQL
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"
        storageClassName: "local-path"
```
Its not flowing through to the StatefulSet.
```
 k describe pvc data-mysql-0
Name:          data-mysql-0
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app.kubernetes.io/component=primary
               app.kubernetes.io/instance=MySQL
               app.kubernetes.io/name=mysql
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       mysql-0
Events:
  Type    Reason         Age                  From                         Message
  ----    ------         ----                 ----                         -------
  Normal  FailedBinding  25s (x142 over 35m)  persistentvolume-controller  no persistent volumes available for this clai
```
I've also set a default storageclass. So I would have thought it would have just been picked up.
```
k describe storageclasses.storage.k8s.io
Name:            local-path
IsDefaultClass:  Yes
```
