### ISSUE TITLE
Avoid prebuilds for some commits

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#6815]
## Is your feature request related to a problem? Please describe

Prebuild is triggered for ANY file that gets updated, for an example - update `README.md` and no one can use the repo until the prebuild process is done, even that it doesn't make sense to run prebuild for such change.

## Describe the behaviour you'd like

* Add a setting `auto` in `.gitpod.yml` to enable (current default) or disable triggering a prebuild for ANY file update.
* Add a section `watch` in `.gitpod.yml` to specify which specific files/folders should trigger a prebuild.
```
github:
  prebuilds:
    auto:
    - false

    watch:
    - src/
    - package.json
```
