### ISSUE TITLE
c++ debugging minimal project configuration

### ISSUE THREAD

**Issue by mfouesneau** [gitpod-io/gitpod#6843]
### Bug description

I've been spending a lot of time trying to understand how gitpod differs from local vscode configuration. No success. I've found many issues on the topic and could not identify a solution.

I have a simple hello-world code with CMake and I've trying to setup the workspace such that I can also use the debugging features. No success.

gitpod.yml
```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: "pip install conan"
  - command: "conan install . && cmake ."

vscode:
  extensions:
    - webfreak.debug
    - ms-vscode.cmake-tools
```

launch.json
```
{
    "configurations": [
        { "type": "gdb",
          "request": "launch",
          "name": "Debug (GDB)",
          "target": "${workspaceRoot}/bin/hello",
          "args": [],
          "cwd": "${workspaceRoot}",
          "valuesFormatting": "parseText",
          "preLaunchTask": "cmake && make"
        }
    ]
}
```
task.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cmake && make",
            "type": "shell",
            "command": "cd ${workspaceRoot} && cmake . && make",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

### Steps to reproduce

the simple code works. When trying to run in debug mode, any breakpoint will not be caught.

### Expected behavior

The debugger should stop on a breakpoint and display information.

### Example repository

https://github.com/mfouesneau/blackbodystars
