### ISSUE TITLE
[image-builder-bob]: cannot authenticate against external registries

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6849]
When using an external registry, the authentication token is not properly applied. This means that the image builder authentication retries expire, returning a 502 Bad Gateway error to the dashboard logs

## To recreate

```yaml
containerRegistry:
  inCluster: false
  external:
    URL: --URL of registry, eg gcr.io/<project-name>--
    certificate:
      kind: secret
      name: registry-secret
```

Create the `registry-secret` using `kubectl`:

```
kubectl create secret docker-registry registry-secret ...
```

Once running, deploy the application to your cluster and start a workspace (one of the example projects are fine)

I have clusters ready and waiting if you want to test/debug

---

See #6810 for debugging - internal registry is fixed with issue not related to this issue
