### ISSUE TITLE
[Installer]: change authProviders from raw data to a secret

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6867]
Currently, the `authProviders` in the config.yaml is an array of objects with sensitive data in. **THIS IS A BAD IDEA*** and will probably raise concern with self-hosted users with additional security/compliance requirements.

Current - array of objects

```yaml
authProviders:
  - id: Public-GitHub
    host: github.com
    type: GitHub
    oauth:
      clientId: xxx
      clientSecret: xxx
      callBackUrl: https://$DOMAIN/auth/github.com/callback
      settingsUrl: https://github.com/organizations/$ORG_ID/settings/applications/$APP_ID
```

Proposed - array of secrets

```yaml
authProviders:
  - kind: secret
    name: auth-provider-github
  - kind: secret
    name: auth-provider-gitlab
```

Each secret would then have the data in an expected format similar to the current auth provider config.

One of the difficulties with this is that this is injected into `server` as a [ConfigMap](https://github.com/gitpod-io/gitpod/blob/8884ea28db71304895234a791f09cb5827e554fb/installer/pkg/components/server/configmap.go#L53), so the object would need to be amended to accept a file location and then read the content from the file
