### ISSUE TITLE
Building image fails with failed commit on ref

### ISSUE THREAD

**Issue by stefanhoelzl** [gitpod-io/gitpod#7130]
### Bug description

The Building image steps fails with the following error message
```
#3 [internal] load metadata for localhost:8080/base:latest
#3 ERROR: failed commit on ref "manifest-sha256:6fc89f28be45acdaffdf2f152df857fbe6edb5dc2cbc112a3b9cedf325bf9246": unexpected commit digest sha256:3ff3760e13a5d0ffef21e072a0b05025a0847be10de1ef218aa819a2ed0fd7b4, expected sha256:6fc89f28be45acdaffdf2f152df857fbe6edb5dc2cbc112a3b9cedf325bf9246: failed precondition
------
 > [internal] load metadata for localhost:8080/base:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM localhost:8080/base:latest
--------------------
error: failed to solve: localhost:8080/base:latest: failed commit on ref "manifest-sha256:6fc89f28be45acdaffdf2f152df857fbe6edb5dc2cbc112a3b9cedf325bf9246": unexpected commit digest sha256:3ff3760e13a5d0ffef21e072a0b05025a0847be10de1ef218aa819a2ed0fd7b4, expected sha256:6fc89f28be45acdaffdf2f152df857fbe6edb5dc2cbc112a3b9cedf325bf9246: failed precondition
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","command":"build","error":"exit status 1","level":"error","message":"build failed","serviceContext":{"service":"bob","version":""},"severity":"ERROR","time":"2021-12-08T19:02:44Z"}
exit
exit

Error: headless task failed: exit status 1
```

with the `.gitpod.yml` having this content:
```yaml
image: python:3.10
tasks:
  - init: |
      pip install -r requirements.txt
      pip install --use-feature=in-tree-build --editable .
ports:
  - port: 9000
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
```

### Steps to reproduce

try to open https://gitpod.io/#https://github.com/stefanhoelzl/python-project-tools

### Expected behavior

opening a workspace

### Example repository

https://gitpod.io/#https://github.com/stefanhoelzl/python-project-tools
