### ISSUE TITLE
ws-scheduler leaves workspaces in pending state if ephemeral storage is configured

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7222]
### Bug description

N/A

### Steps to reproduce

configure ephemeral storage and try to start a workspace 

```yaml
 workspaceSizing:
    requests:
       ephemeral-storage: "3Gi"
    limits:
      ephemeral-storage: "5Gi"
```

### Expected behavior

Working workspaces
