### ISSUE TITLE
[installer]: workspace resource requests are not implemented

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7253]
In the config.yaml, there is a snippet for request limits:

```yaml
workspace:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
```

This has not yet been implemented or used inside the Installer.

Potentially related, the ghosts are set to `0` as they spin out of control when set to a greater-than-zero value (typically, we want this set to `10`)
