### ISSUE TITLE
Python packages not installed after installing in prebuild

### ISSUE THREAD

**Issue by dsbowen** [gitpod-io/gitpod#7306]
### Bug description

Python packages aren't installed after I pip install them in a prebuild.

### Steps to reproduce

I have a repo in gitlab with 1 file:

`.gitpod.yml`

``` yaml
tasks:
  - init: pip install black
    command: python -c "import black"

vscode:
  extensions:
    - ms-python.python
```

The workspace opens with

``` bash
ModuleNotFoundError: No module named 'black'
```

### Expected behavior

The `black` package should be recognized. Commands like the following should work:

``` bash
$ black --version
$ pip show black
```

### Example repository

Snapshot: https://gitpod.io#snapshot/db244596-5f38-43ae-817c-6c9ff620742b

Repo: https://gitlab.com/dsbowen/gitpod-test

### Anything else?

I tried this with the python:3.9 image and ran into the same issue.
