### ISSUE TITLE
Master branch not pre-building

### ISSUE THREAD

**Issue by dunnry** [gitpod-io/gitpod#732]
**Describe the bug**
We are not seeing our master images getting pre-built.

**To Reproduce**
Make a commit to master, wait a few hours and launch gitpod on master branch.

**Expected behavior**
We were expecting to see most of the yarn build process already done when the dev environment launched.

.gitpod.yml 
```
ports:
- port: 3000
tasks:
  - init: >
      language-server/gradlew -p language-server assemble &&
      yarn --cwd theia
    command: >
      yarn --cwd theia/browser-app start --hostname 0.0.0.0
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
```
