### ISSUE TITLE
Add Traefik as proxy

### ISSUE THREAD

**Issue by gopherpro** [gitpod-io/gitpod#7373]
# Current state

At the moment GitPod only use NGINX as proxy. If you want to an other proxy like Traefik, you have to change the proxy service type to `clusterip` and now you cloud run Traefik in front of NGINX.

```yaml
components:
  proxy:
    # REMOVE: serviceType: "LoadBalancer"
    serviceType: "clusterip"
```
link to [values.yaml](https://github.com/gitpod-io/gitpod/blob/b53c34d330ca30ae7cf3476f5896a32223540c69/chart/values.yaml#L444)

# Idea

To make GitPod better and more usable for everyone, I would like to see support for Traefik (and other solutions) as proxy. To enable other solutions, GitPod needs a option to use the ingress object (instead of NGINX).

GitPod then will create a ingress for the dashboard, MinIO, Registry & every workspace.

### Simple 

```yaml
hostname: gitpod.example.com

components:
  proxy:
    enable: false

  ingress:
    enable: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
```
### Advanced

```yaml
hostname: gitpod.example.com

components:
  proxy:
    enable: false

  ingress:
    enable: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

# Create ingress for dashbaord
  dashboard:
    ingress: true

# Create ingress  MinIO with costume hostname and middleware
minio:
  ingress: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: allow-only-local-ip@kubernetescrd
  hosts:
    - minio.gitpod.example.com # or minio.exmaple.com

# or leave it empty for no ingress
```

**Comment by aledbf** [comment]
> At the moment GitPod only use NGINX as proxy.

@gopherpro Gitpod does not use NGINX as reverse proxy. It uses Caddy. You can find the [definition here](https://github.com/gitpod-io/gitpod/blob/main/components/proxy/Dockerfile#L15)

Also, we are deprecating the helm chart, in favor of the [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer)

**Comment by aledbf** [comment]
> GitPod then will create a ingress for the dashboard, MinIO, Registry & every workspace.

Thank you for the suggestion, but for now, we are not planning to use Ingress as entry point for Gitpod.

**Comment by gopherpro** [comment]
Thanks for your fast feedback. It seems like I got the wrong information about the reverse proxy. My fault.

Maybe my idea is something for the future. :smile:

**Comment by zeroZshadow** [comment]
Traefik can currently be used, although it's not entirely idea.
You can change the deployment to use ClusterIP instead of LoadBalancer in the advanced settings, and then apply the following Traefik IngressRoutes to get the right traffic forwarding.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitpod-public
  namespace: gitpod
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNIRegexp(`gitpod.example.com`, `{subdomain:[[:ascii:]]+}.gitpod.example.com`, `{subdomain:[[:ascii:]]+}.ws.gitpod.example.com`)
      services:
        - name: proxy
          port: 443
  tls:
    passthrough: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitpod-ssh-public
  namespace: gitpod
spec:
  entryPoints:
    - ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: proxy
          port: 22
```

Make sure to update the namespace and domain names accordingly.

Sadly I havn't been able to use a normal `IngressRoute` due to gitpod not supporting an insecure access, enforcing TLS termination on its own. So you will be rather limited in available Middlewares.
