### ISSUE TITLE
Gitpod badge is not displayed when PR doesn't have description

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#7488]
### Bug description

After adding `addBadge: true` to `.gitpod.yml` 
```yaml
github:
  prebuilds:
    # add a "Open in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
```
When creating a new PR with no description, a Gitpod badge is not added to PR description.

### Steps to reproduce

Make sure your repo has this code in `.gitpod.yml` -
```yaml
github:
  prebuilds:
    # add a "Open in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
```

Create a new PR, make sure to only give a title to the PR, but no descirption.
Confirm that the PR has no Gitpod badge in its description.

### Expected behavior

When `addBadge: true` is added to `.gitpod.yml`, I expect the Gitpod badge to be displayed in all PRs, including PRs without a descirption.

### Example repository

https://github.com/shaal/gitpod-test--no-gitpod-badge-in-pr-without-description

I created 2 PRs -
* PR with description (work as expected, Gitpod badge is displayed) - https://github.com/shaal/gitpod-test--no-gitpod-badge-in-pr-without-description/pull/2
* PR without description (this is the bug, no Gitpod badge is displayed) - https://github.com/shaal/gitpod-test--no-gitpod-badge-in-pr-without-description/pull/1
