### ISSUE TITLE
Epic: Multi-repo Workspaces

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7608]
## Goal

Enable workspace configuration consisting of multiple repositories without compromising on any of the contextual functionality of Gitpod. I.e. I want to be able to start a dev environment that has all the repos cloned and prebuild from any context of the participating repositories.

Additional discussion also in https://github.com/gitpod-io/gitpod/issues/7249

This should allow Gitpod to work well for scenarios where the code for different components of a project is not maintained in a monorepo, but rather in separate git repos. A common example is back-end services and front-end implementations for different target platforms.

See [this RFC](https://www.notion.so/gitpod/RFC-Multi-Repo-Support-247be8565ed14d8e88cf4147a740c9fc) for a deeper discussion about the approach.

## Proposed solution

The outlined solution will make it possible to compose multiple repos to one by introducing references in the `.gitpod.yml`. Conceptually it makes such multi-repo projects work very similar to how large mono-repos work.

- Introduce a `mainConfiguration: string` property on workspace config, that marks any sub repositories as such and points to a main repo that has a proper `.gitpod.yml`.
- Introduce a `additionalRepositories: string[]` property on workspaces config, that lists the sub repositories. They should also list the relative path to where the repo should be cloned, default is next to the main repo using the simple name of the sub-repository. So it’s a bi-directional relationship, that needs to be consistent. It’s necessary to be bi-directionally specified in order to be able to resolve all the participating repos.
- Make all clients of workspace starts aware of this composition, such that if I start a workspace on a sub repo, it creates the whole repo based on the context (see below). This includes prebuilds, i.e. users should install webhooks (resp. GH app) on all additional repositories, which will trigger a prebuild for the given context. Prebuilds are listed on the main repo, i.e. in Gitpod there is only one project for such multi-repo projects.

### Example Setup

```yaml
# Project A (https://github.com/my-org/project-a)
additionalRepositories:
 - url: https://github.com/my-org/sub1
   checkoutLocation: ./../sub1 # optional
image: 
   file: .gitpod.Dockerfile
tasks:
 - before: cd ./../sub1
   init: npm install
   command: npm run sub1
 - before: cd ../sub2
   init: npm install
   command: npm run sub2
```

```yaml
# Sub 1 (https://github.com/my-org/sub1)
mainConfiguration: https://github.com/my-org/project-a
```

```yaml
# Sub 2 (https://github.com/my-org/sub2)
mainConfiguration: https://github.com/my-org/project-a
```

### Contexts

Context URLs will work as usual, but the implications (e.g. branch creation on issues, branch checkout on PRs) only happen on the context’s repository. All other repository will checkout the default branch.

### Benefits of this solution

- Relatively easy to set-up
- All the Gitpod concepts work (prebuilds, context URLs)
- No need for external port forwarding
- Equivalent to local dev environment setups
