### ISSUE TITLE
[installer] Empty minio section is rendered when gcp is used as storage

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7746]
### Bug description

```
"minio": {
	"endpoint": "",
	"accessKey": "",
	"accessKeyFile": "",
	"secretKey": "",
	"secretKeyFile": "",
	"region": ""
},
```

### Steps to reproduce

configure

```
objectStorage:
  cloudStorage:
    serviceAccount:
      kind: secret
      name: gcloud
```
