### ISSUE TITLE
[installer] imagebuild template is not rendered

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7750]
### Bug description

Setting imagebuild section do not produces any configuration in ws-manager `podTemplate` configuration file

```
workspace:
  templates:
    imagebuild:
      <spec>
```

### Steps to reproduce

-
