### ISSUE TITLE
Terminal window close from task

### ISSUE THREAD

**Issue by Vlaaaaaaad** [gitpod-io/gitpod#782]
Hi,

When having multiple tasks( be they `init`, `before`, or `command`) a lot of terminals end up remaining open with... misleading titles. I'd love to be able to close the terminal on successful execution of the task.

I've tried both `exit` which just closes the running command, but not the terminal window. Combinations of `kill -9` and `ps` led nowhere either.

Going further, for failing tasks I'd like the option to pretty print some helpful instructions: _Hey, this failed cause X so please try running this command: ****_, but that's more intense I think.

**Comment by jankeromnes** [comment]
Hi @Vlaaaaaaad!

Normally, multiple tasks (`init`, `before`, `command`) should run in a single Terminal. I'm guessing that you have multiple `-`s in your `.gitpod.yml`:

```yml
tasks:
  - before: # ...
  - init: # ...
  - command: # ...
```

This will run all tasks in parallel in multiple Terminals. I think what you want instead is:

```yml
tasks:
  - before: # ...
    init: # ...
    command: # ...
```

This will open a single Terminal (only one `-`), and run `before`, `init` and `command` sequentially.

**Comment by jankeromnes** [comment]
Also, on a random note, you can give more relevant names to each Terminal, like so:

```yml
tasks:
  - name: DB
    init: ./install-db.sh
    command: ./start-db.sh
  - name: Server
    init: ./install-server.sh
    command: ./start-server.sh
```

**Comment by jankeromnes** [comment]
> Going further, for failing tasks I'd like the option to pretty print some helpful instructions: _Hey, this failed cause X so please try running this command: ****_, but that's more intense I think.

What you can do is use Bash's `||` operator for that, e.g.:

```yml
tasks:
  - command: cat ohno.txt || printf "\nPlease try running 'touch ohno.txt' first.\n\n"
```

**Comment by Vlaaaaaaad** [comment]
Yes, I had two tasks in `.gitpod.yml`, like so:
```
image:
  file: .gitpod/.gitpod.dockerfile

tasks:
  - name: Install pre-commit hooks
    command: pre-commit install --install-hooks && printf "\n \n \n Please close this window"

  - name: SSH setup and Terraform init
    command: >
      .gitpod/ssh-terraform.sh
```

I wanted the user to see the _SSH setup and Terraform init_ window when the workspace starts and the _Install pre-commit hooks_ terminal window to close if it ran successfully.


Buuuut I think I can break _SSH setup and Terraform init_ into two tasks and maaaybe combine them nicely. I will experiment now and report back -- I am planing to open-source this when it's ready either way.

Thank you so much!

**Comment by Vlaaaaaaad** [comment]
I'd still like to have the option to close the Terminal window from a task so I will leave this open. Is that ok?

The following works great meanwhile:
```yaml
image:
  file: .gitpod/.gitpod.dockerfile

tasks:
  - name: Prepare workspace
    before: >
      pre-commit install --install-hooks
      && printf "\n \n \n Please close this window"
    init: > # This runs only on fresh workspace creation
      .gitpod/ssh-keys-setup.sh
      && terraform init -backend=false -input=false
      && printf "\n \n \n Please close this window"
```
