### ISSUE TITLE
prebuilds stopped working

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#8118]
### Bug description

I only get prebuilds in my team if I manually trigger them:

![image](https://user-images.githubusercontent.com/1100969/153194302-2d80b3a0-a976-4f3c-ba5e-8b7e2857a2c4.png)

until 16 days ago (15 from yesterday) it stopped to have automatic prebuilds:

![image](https://user-images.githubusercontent.com/1100969/153194404-3992e294-1ccd-4a81-a55a-9898ad3fe9f1.png)

incremental preBuilds are turned off:

![image](https://user-images.githubusercontent.com/1100969/153195150-acd7c9c9-3957-445c-bbf5-4aa0c512070b.png)

my gitpod yaml:
```
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
```

### Steps to reproduce

look into my tenant, you will find it via my github username (konne)
