### ISSUE TITLE
Update python version 2.7 to 3.6

### ISSUE THREAD

**Issue by vanphudhsp2015** [gitpod-io/gitpod#827]
Please update version

**Comment by jankeromnes** [comment]
Hi @vanphudhsp2015, both Python versions 2.7 and 3.7 are installed side-by-side using `pyenv`:

```bash
$ pyenv versions
  system
* 2.7.16 (set by /home/gitpod/.pyenv/version)
* 3.7.4 (set by /home/gitpod/.pyenv/version)
```

You can switch to `3.7.4` by default like so:

```bash
$ pyenv local 3.7.4
```

This will create a `.python-version` file locally. To make this version change persistent, you can either commit this file and push it to your repository, or you can add the `pyenv local` command to your project's `.gitpod.yml`, like so:

```yml
tasks:
  - init: pyenv local 3.7.4
    command: # your normal start-up command
```
