### ISSUE TITLE
Container Registry and S3 Clarification In The Docs

### ISSUE THREAD

**Issue by eiymba** [gitpod-io/gitpod#8321]
The EKS installer's bash script modifies this parameter such that it it reads:

```yaml
containerRegistry:
  ...
  s3storage:
    bucket: <bucket>
  ...
```

However, the actual readme of the installer suggests this yaml format:

```yaml
containerRegistry:
  inCluster: false
  external:
    url: <url of registry>
    certificate:
      kind: secret
      name: container-registry-token
```

So, am I correct it thinking that we can either use S3 as a container registry, or use an external private container registry?
