### ISSUE TITLE
.gitpod.yml in project gets overwritten by gitpod on launch

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#8445]
### Bug description

If I launch a project, the existing .gitpod.yml is overwritten with a dummy .gitpod.yml.

This is a serious problem - The existing .gitpod.yml should be respected. This completely breaks everything that has a .gitpod.yml. Is there any workaround? This completely breaks https://github.com/drud/ddev-gitpod-launcher and really... everybody that ever had a .gitpod.yaml. I don't need this silly replacement .gitpod.yml:

```yaml
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
```

This is  a super-critical bug, gitpod should never be replacing existing files.

### Steps to reproduce

Just launch https://drud.github.io/ddev-gitpod-launcher/ with the defaults. The code is in https://github.com/drud/ddev-gitpod-launcher

### Expected behavior

.gitpod.yml should not be overwritten.

### Example repository

https://github.com/drud/ddev-gitpod-launcher
