### ISSUE TITLE
registry facade won't start in air gap network

### ISSUE THREAD

**Issue by SirLemyDanger** [gitpod-io/gitpod#8462]
### Bug description

After a fresh installation of GitPod (Jan'22) the registry facade pod is crashing permanently. 

Environment: K3s on Ubuntu
I set up K3s to pull images from a proxy (artifactory) by having a /etc/rancher/k3s/registries.yaml like this:

```yaml
mirrors:
  docker.io:
    endpoint:
      - "<my container proxy>"
  gcr.io:
    endpoint:
      - "<my container proxy>"
  eu.gcr.io:
    endpoint:
      - "<my container proxy>"
  quay.io:
    endpoint:
      - "<my container proxy>"
```

This works fine; all containers are being pulled and I can manually pull images with `crictl`.

However the registry-facade pod tries to access `https://eu.gcr.io/v2/gitpod-core-dev/build/supervisor/manifests/commit-dbe106c19401e780829827dc50a0154c1b93b96c` which times out, as the machine has no direct access to the internet. See log at the end.

In a postpressing step of the gitlab.config.yaml I changed the runtime setting to (not sure though if this is a good idea):

```yaml
workspace:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/k3s/containerd/containerd.sock
    fsShiftMethod: shiftfs
```

error log:
```
Head \"https://eu.gcr.io/v2/gitpod-core-dev/build/supervisor/manifests/commit-dbe106c19401e780829827dc50a0154c1b93b96c\": dial tcp 108.177.15.82:443: i/o timeout
es/docker.(*request).do
	github.com/containerd/containerd@v1.5.5/remotes/docker/resolver.go:569
github.com/containerd/containerd/remotes/docker.(*request).doWithRetries
olver.go:576
github.com/containerd/containerd/remotes/docker.(*dockerResolver).Resolve
	github.com/containerd/containerd@v1.5.5/remotes/docker/resolver.go:280
github.comceFromImage
	github.com/gitpod-io/gitpod/registry-facade/pkg/registry/layersource.go:227
github.com/gitpod-io/gitpod/registry-facade/pkg/registry.buildStaticLayer
	githy.go:48
github.com/gitpod-io/gitpod/registry-facade/pkg/registry.NewRegistry
	github.com/gitpod-io/gitpod/registry-facade/pkg/registry/registry.go:104
github.com/gitpod-od-io/gitpod/registry-facade/cmd/run.go:113
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.1.3/command.go:856
github.com/spf13/cobra.(*Command).Exeb.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/gitpod-io/gitpod/registry-facade/cmd.Execute
	github.com/gitpod-io/gitpod/od-io/gitpod/registry-facade/main.go:10
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581","host":"eu.gcr.io","level":"info","message":"trying
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"cannot source layer from eu.gcr.io/gitpod-core-dev/build/supervisor:coom/gitpod-io/gitpod/registry-facade/pkg/registry.buildStaticLayer
        github.com/gitpod-io/gitpod/registry-facade/pkg/registry/registry.go:50
  - Head \"https://eu.gcr106c19401e780829827dc50a0154c1b93b96c\": dial tcp 108.177.15.82:443: i/o timeout
    failed to do request
    github.com/containerd/containerd/remotes/docker.(*request).doer/resolver.go:569
    github.com/containerd/containerd/remotes/docker.(*request).doWithRetries
    	github.com/containerd/containerd@v1.5.5/remotes/docker/resolver.go:57kerResolver).Resolve
    	github.com/containerd/containerd@v1.5.5/remotes/docker/resolver.go:280
    github.com/gitpod-io/gitpod/registry-facade/pkg/registry.NewStaticSouade/pkg/registry/layersource.go:227
    github.com/gitpod-io/gitpod/registry-facade/pkg/registry.buildStaticLayer
    	github.com/gitpod-io/gitpod/registry-facade/pkg/regry-facade/pkg/registry.NewRegistry
    	github.com/gitpod-io/gitpod/registry-facade/pkg/registry/registry.go:104
    github.com/gitpod-io/gitpod/registry-facade/cmd.glob.d/run.go:113
    github.com/spf13/cobra.(*Command).execute
    	github.com/spf13/cobra@v1.1.3/command.go:856
    github.com/spf13/cobra.(*Command).ExecuteC
    	github/cobra.(*Command).Execute
    	github.com/spf13/cobra@v1.1.3/command.go:897
    github.com/gitpod-io/gitpod/registry-facade/cmd.Execute
    	github.com/gitpod-io/gitpod.com/gitpod-io/gitpod/registry-facade/main.go:10
    runtime.main
    	runtime/proc.go:255
    runtime.goexit
    	runtime/asm_amd64.s:1581","level":"fatal","message":ry-facade","version":"commit-c6fdc8f36defd46b07ede1dd7a294846f1093c51"},"severity":"CRITICAL","time":"2022-02-25T15:21:29Z"}

```

### Steps to reproduce

K3s without traeffik, single node; configured with /etc/rancher/k3s/registries.yaml

install GitPod with installer of the Jan'22 release

### Expected behavior

no request to the internet
