### ISSUE TITLE
[installer] Host all images needed for install in a Gitpod registry

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/gitpod#8586]
Currently, the installer pulls images from three registries including two public registries:

```
quay.io/brancz/kube-rbac-proxy
docker.io/bitnami/bitnami-shell
docker.io/bitnami/minio
docker.io/bitnami/mysql
docker.io/bitnami/rabbitmq
docker.io/gitpod/workspace-full
docker.io/library/alpine
docker.io/library/registry
docker.io/library/ubuntu
```

Docker Hub rate limits are a challenge at large companies that use NAT gateways, VPNs, or HTTP proxy because Docker Hub rate limits anonymous pulls by IP address.  We also don't want to rely on their uptime. We should move all the images we need for an installation into our registry.

**Comment by SirLemyDanger** [comment]
We have an artifactory as a mirror. I was then able to install gitpod from there using a regestries.yaml for k3s like this:
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://mirror.example.com"
  gcr.io:
    endpoint:
      - "https://mirror.example.com"
  eu.gcr.io:
    endpoint:
      - "https://mirror.example.com"
  quay.io:
    endpoint:
      - "https://mirror.example.com"
```

(What I didn't achive is to teach the build in registry to pull images from there as well :( )
