### ISSUE TITLE
Add option to configure blockNewUsers

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8906]
When creating a Gitpod instance, it would make sense to prevent users from being able to sign up to that instance. As many users will be enterprises with a specific domain name, this should be considered an easy win

Config to allow `gitpod.io` users to login

```yaml
blockNewUsers:
  enabled: true
  passlist: 
    - gitpod.io
```
