### ISSUE TITLE
The hightliter for default of python is very very bad

### ISSUE THREAD

**Issue by jefer94** [gitpod-io/gitpod#8945]
## Is your feature request related to a problem? Please describe

The hightliter for default of python is very very bad

## Describe the behaviour you'd like

Can pull a version of docker image as insider

```dockerfile
# .gitpod.Dockerfile
FROM gitpod/workspace-postgres:insider
```

```yml
# .gitpod.yml
vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
```

## Describe alternatives you've considered

Can use Pylance, or set in .gitpod.yml the version of vscode

```yml
# .gitpod.yml
vscode:
  version: insider
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
```
