### ISSUE TITLE
One frame running phase for every workspace start

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#8990]
### Bug description

One frame running phase for every workspace start

This ~~is~~ part because of the time diff between `contentAvailable` and `ideReady`

This PR https://github.com/gitpod-io/gitpod/pull/8313 will wait until `contentAvailable` to get `.gitpod.yml` file to parse extensions and download extensions via URL first, and then start IDE

So `ideReady` will always be after `contentAvailable`, but after `contentAvailable`, workspace phase turns to `Running`.

We can verify it here https://gitpod.io/#github.com/mustard-mh/test/tree/hw/large-file which will download some large files

```yaml
vscode:
  extensions:
    - http://ipv4.download.thinkbroadband.com/1GB.zip
    - http://212.183.159.230/1GB.zip
    - https://speed.hetzner.de/10GB.bin
```

|Image|
|:-:|
|<img width="1512" alt="iShot2022-03-29 15 50 04" src="https://user-images.githubusercontent.com/20944364/160561238-0f535e68-da4f-4a8f-baeb-2ef4a915d8fc.png">|

### Steps to reproduce

Start a workspace
