### ISSUE TITLE
group and give description for gitpod ports

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#9285]
the current port list just contains all currently shared ports.

This is very confusing because we open for example a lot of nodejs debugging ports that are not needed to be used by the users.
It would be great to first have a possibility in the gitpod.yml to give a group name

```yaml
ports:
  - port: 33000-33999
     group: debugging
     state: closed
     onOpen: ignore
   - port: 80-2000
     group: web
     state: opened
   - port: 6008
     group: VNC
     state: closed
```

On Top it would be even great to give each port also a description that would be visible beside the port number like

ports:
  - port: 33000-33999
...

  - port 330100
       - description: Debug API gateway
  - port 330101
       - description: Debug Service1  
  - port 6008
       - description: VNC
```
