### ISSUE TITLE
Python workspaces are broken

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#930]
**Describe the bug**
So I have a private repository that I'm opening in Gitpod, and my configuration looks like:
```yaml
ports:
- port: 5000

tasks:
  - before: python3 -m pip install --upgrade -r requirements.txt
```
(and yes, I've tried with both `init` and `before`)

the issue is that I can now open the code, only to see:
![Screenshot 2019-11-15 at 12 25 36 PM](https://user-images.githubusercontent.com/34555510/68962683-27fa4c00-07a3-11ea-8ec9-1f271750a25e.png)
all my external dependencies seemingly missing!

**To Reproduce**
Private so I can't sorry

**Expected behavior**
My dependencies should be in site packages

**Additional Information**
This only happens for **external** dependencies, like `sentry_sdk`, but not with `builtins` like `os` and package-private classes (in the project's package, meaning they are in the same folder).

Please help, this is a bit urgent as it is slowing down my workflow!
