### ISSUE TITLE
Support taint tollerations

### ISSUE THREAD

**Issue by locomoco28** [gitpod-io/gitpod#9618]
## Is your feature request related to a problem? Please describe

Gitpod only gets deployed on nodes with specific labels, but other workloads can be deployed on these nodes aswell. To fix this, the nodes can have taints applied to them. The Gitpod config should imo have an easy option to set taint tolerations instead of relying on post-processing the rendered manifest, because that's not recommended.

## Describe the behaviour you'd like
A config in the `gitpod.config.yaml` that specified the tolerations for the Gitpod workloads.

```yaml
# Following the recommendation to group the meta and ide nodes
# and the workspace nodes separately
# We can set the value to "gitpod" on both as we can control which
# node gets meta/ide workloads, and which workspace workloads,
# using affinity labels, but it might still be useful for some people
# to have separate tolerations for both (like differentiating VM sizes)
taintTolerations:
  meta: # meta/ide
    - name: app
      value: gitpod
      effect: NoSchedule
  workspaces: # workspace
    - name: app
      value: gitpod
      operator: Equal
      effect: NoSchedule
    - name: size
      value: NDv2
      effect: NoSchedule
```

<details>
  <summary>Example outputs</summary>

```yaml
# apps/v1/Deployment minio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      tolerations:
        - key: "app"
          value: "gitpod"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gitpod.io/workload_meta
                    operator: Exists
---
# apps/v1/Deployment ws-manager
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-manager
spec:
  template:
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "gitpod"
          effect: "NoSchedule"
        - key: "size"
          value: "NDv2"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gitpod.io/workload_workspace_services
                    operator: Exists
```
</details>
