### ISSUE TITLE
Intellij plugin docs seem incorrect

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#9902]
### Bug description

According to the docs you can add

```
jetbrains:
  intellij:
    prebuilds:
      version: stable

```
and 

```
jetbrains:
  intellij:
    - zielu.gittoolbox
    - izhangzhihao.rainbow.brackets
```

to your gitpod yaml file, but surely the plugins block is missing a plugins descriptor or something? Cause that doesn't look like it would make a valid yaml file.

### Steps to reproduce

Read the docs
